### PR TITLE
refactor(components): update software keyboard styling

### PR DESCRIPTION
**Pull request by koji**
# Overview
Update software keyboard layout
close RCORE-753

# Test Plan

# Changelog
- update NormalSoftware Keyboard Layout
- update text/character on backspace button, space button, shift button, and buttons to switch keyboard layout 

# Review requests

# Risk assessment
low

### CODE REVIEW

**Comment by koji** [comment]
- [x] fix the keys' layout (Mel's confirmation is needed)
- [x] test on a dev kit

**Review by jerader — APPROVED** [review]
lgtm!

**Comment by ewagoner** [comment]
On the robot naming screen, the instructions say "letters and numbers only" but the keyboard has a spacebar. Should we change the copy?

**Comment by koji** [comment]
> "letters and numbers only

oh that is a good point.

**Comment by koji** [comment]
> On the robot naming screen, the instructions say "letters and numbers only" but the keyboard has a spacebar. Should we change the copy?

Talked about this with Mel in person.
We decided to remove `enter` and `space`

**Review by ewagoner — APPROVED** [review]

**Pull request merged**
