### PR TITLE
refactor(app): optimize images

### PR DESCRIPTION
**Pull request by koji**
# Overview
Optimized images under `src/assets/images` and converted svg to png.
This will close RAUT-237
edge: 25.1 MB
this branch: 7.2 MB

This PR adds fixed values to `image` and `Box` to align with the design. We need them because the app uses svg which includes a white rectangle to adjust the space.  

# Changelog
- optimize images
- convert svg that is used base64 data: png to png
- remove unused old images and gif 
- change image names, `heatershaker` and `heater-shaker` into `heater_shaker`

# Review requests
- [ ] optimized images looks okay
- [ ] converted pngs works as expected

# Risk assessment
low

### CODE REVIEW

**Review by jerader — COMMENTED** [review]
Hey Koji, thank you for doing this! I went through the app to take a look at the images and noticed a few things:

1. `app/src/assets/images/screwdriver_oriented_left.png` needs adjusting
Screen Shot 2022-09-28 at 9 21 22 AM
2. the Thermocycler image on module card looks blurry in comparison to the other modules (I think?)
Screen Shot 2022-09-28 at 9 22 16 AM

**Comment by koji** [comment]
> Hey Koji, thank you for doing this! I went through the app to take a look at the images and noticed a few things:
> 
> 1. `app/src/assets/images/screwdriver_oriented_left.png` needs adjusting
> 
> Screen Shot 2022-09-28 at 9 21 22 AM
> 
> 2. the Thermocycler image on module card looks blurry in comparison to the other modules (I think?)
> Screen Shot 2022-09-28 at 9 22 16 AM

@jerader thank you for your feedback

1 You mean centralize don't you?

2 I will check it

**Comment by jerader** [comment]
@koji, not sure but the screwdriver should look like this:

Screen Shot 2022-09-28 at 9 32 01 AM

Screen Shot 2022-09-28 at 9 32 35 AM

**Comment by koji** [comment]
@jerader updated the images you pointed out. Could you check them when you are available?
Thanks!

**Comment by koji** [comment]
- [x] solve conflicts

**Comment by koji** [comment]
- [x] fix test issues

**Comment by jerader** [comment]
One thing I noticed: the `app/src/assets/images/thermocycler_open_transparent.png` added image looks wrong. The seal should be orange (here is the[ design qa ticket](https://opentrons.atlassian.net/jira/software/c/projects/RUXD/boards/125?modal=detail&selectedIssue=RUXD-512&search=thermocyc&assignee=612fa9a0b1894f007176753e) I addressed in a PR recently for reference)

**Comment by jerader** [comment]
The screwdriver still isn't appearing properly

Screen Shot 2022-10-06 at 9 25 06 AM

**Comment by koji** [comment]
> The screwdriver still isn't appearing properly

Screen Shot 2022-10-06 at 6 06 22 PM

**Comment by koji** [comment]
Screen Shot 2022-10-10 at 4 05 03 PM

**Comment by koji** [comment]
@jerader 
Thank you for your feedback. I found an issue that the wizards aren't responsive.
I talked about this with Brian.
For this PR, I add fixed values to keep the current app's design.

The fix plan is 👇
https://opentrons.atlassian.net/browse/RAUT-256

**Review by jerader — APPROVED** [review]
lgtm! Did some smoke testing to take a look at the images in the app. Thank you for doing this!

**Pull request merged**
