### PR TITLE
fix(api, hardware-testing): update plunger speed/currents

### PR DESCRIPTION
**Pull request by andySigler**
# Overview

- 96ch plunger max-speed increased from `5` to `15` mm/sec
- 96ch plunger run-current decreased from `2.2` to `0.8` amps (because of resonance)
- 1/8ch plunger max-speed increased from `45` to `70` mm/sec

# Test Plan

# Changelog

# Review requests

# Risk assessment

### CODE REVIEW

**Review by Laura-Danielle — CHANGES_REQUESTED** [review]
Can we also edit the run current in the 96 channel `general` definition for the v2 configs?

**Review by sfoster1 — APPROVED** [review]
Okay, cool!

**Review by ryanthecoder — APPROVED** [review]
LGTM

**Review by Laura-Danielle — APPROVED** [review]
ty!

**Pull request merged**
