### PR TITLE
chore(release): 6.1.0

### PR DESCRIPTION
**Pull request by shlokamin**
## Overview

This is the final release PR for the upcoming 6.1.0 release

## Changelog

See commit list below

## Review requests

- [ ] Review user-facing App release notes 
- [ ] Review user-facing Robot release notes 
- [ ] Review auto-generated technical change log 

## Risk assessment

High. This is a major software release that touches many files across the entire stack

### CODE REVIEW

**Review by nusrat813 — APPROVED** [review]
LGTM

**Review by ecormany — APPROVED** [review]
Release notes look good 🚀

**Review by sanni-t — APPROVED** [review]
🚢✨

**Review by bndo — APPROVED** [review]
LGTM 🔥

**Pull request merged**
