### PR TITLE
fix(protocol-designer): fix issues in select pipette screen

### PR DESCRIPTION
**Pull request by koji**
# Overview
fix issues in select pipette screen

close AUTH-762 RQA-3265 RQA-3267 RQA-3269

## Test Plan and Hands on Testing
AUTH-762
1. select a pipette
2. click add a pipette button
3. select a pipette and tips
4. click go back
check that PD displays the screen before the step3 (like the following)

2024-10-02 16_14_30-NVIDIA GeForce Overlay DT

RQA-3265 RQA-3269
1. select a pipette
check the info card has remove button and switch pipettes button is displayed
2. click remove button in the info card
check only one EmptySelectorButton is displayed and switch pipettes button is not displayed

RQA-3267
1. select a pipette
add a pipette and tips button is displayed
2. click swap pipettes
check add a pipette and tips button is below the pipette info
3. click add pipette and tips 
check add a pipette and tips button is not in the wizard

## Risk assessment
low

### CODE REVIEW

**Review by ncdiehl11 — COMMENTED** [review]
Hm, is this the intended functionality for go back if we have already added a pipette? 
https://github.com/user-attachments/assets/f4f1412e-b5b0-4228-b321-7b7696870c4b

**Comment by koji** [comment]
> Hm, is this the intended functionality for go back if we have already added a pipette? https://github.com/user-attachments/assets/f4f1412e-b5b0-4228-b321-7b7696870c4b

oh good point, let me ask about this to Felix.
actually I feel that displaying the selected pipette list would be natural.

**Comment by koji** [comment]
@ncdiehl11

**Comment by koji** [comment]
@ncdiehl11 


https://github.com/user-attachments/assets/0ba8b011-fca0-41e7-a6fc-f17d765f7adc

**Review by ncdiehl11 — APPROVED** [review]
This go back behavior works as I would expect. Thanks for clarifying with desing!

**Pull request merged**
