### PR TITLE
refactor(app): display protocol page banners once a run has started

### LINKED ISSUE #8570: On Protocols page, after a run has begun, display a banner and adjust button availability
Once a protocol run has started, the protocols page functionality will need to be adjusted as follows:

**Display a banner at the top of the page when the following conditions exist:**
1. a run has been started: show a warning banner
2. a run has failed: show an error banner
3. a run has been canceled: show an error banner
4. a run is complete: show a success banner

**Disable the following functionality when any of the above conditions are met:**
1. disable the "Recalibrate" button for tip length calibration
2. disable the "Run Labware Position Check" button

see figma for details:
https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0:-Protocol-Upload-Revamp?node-id=7548%3A180274

### PR DESCRIPTION
**Pull request by brenthagen**
# Overview

This PR displays banners on the protocol page based on run status, and disables tip length calibration and labware position check (with tooltips). I refactored `useRunStatus` to return 'idle' status as 'running' after a run has started based on the common usage pattern with `RunTimeControl`. Also added a test file for `TipLengthCalibration`, because I didn't see an existing one.

closes #8570

# Changelog

 - Displays protocol page banners once a run has started
 - Adjusts tip length calibration and labware position check availability once a run has started

# Review requests

Confirm banners and disabled states work as expected:

Screen Shot 2021-11-23 at 9 58 19 AM

Screen Shot 2021-11-23 at 10 07 13 AM

Screen Shot 2021-11-23 at 10 07 27 AM

Screen Shot 2021-11-23 at 10 07 38 AM

Screen Shot 2021-11-23 at 10 11 28 AM

Screen Shot 2021-11-23 at 10 13 20 AM

# Risk assessment

low

### CODE REVIEW

**Comment by emilywools** [comment]
hey @brenthagen thanks for this!!

1. can both of the success banners be the same width? aka make the protocol in progress banner a little wider to match the LPC complete banner.
2. does the LPC success banner stay forever until the user dismisses it? It seems like it should go away after x seconds (do we have a standard for this)?
3. the protocol completion success message seems a bit odd, because its a success message saying that something is not going to work. What do you think of rewording this to something like 
`Protocol run complete. This protocol can now be closed.`

cc @mikecardarelli on 3.

**Review by sakibh — COMMENTED** [review]
Just gave this a run on my robot. I have been unable to do TLC, so I still have the "Calibrate Now" button. Does this button also need to be disabled when a run is taking place? Other than this, everything else appears to work just fine!

image

**Comment by brenthagen** [comment]
> hey @brenthagen thanks for this!!
> 
> 1. can both of the success banners be the same width? aka make the protocol in progress banner a little wider to match the LPC complete banner.
> 2. does the LPC success banner stay forever until the user dismisses it? It seems like it should go away after x seconds (do we have a standard for this)?
> 3. the protocol completion success message seems a bit odd, because its a success message saying that something is not going to work. What do you think of rewording this to something like
>    `Protocol run complete. This protocol can now be closed.`
> 
> cc @mikecardarelli on 3.


@emilywools updates to banner width and copy:

Screen Shot 2021-11-24 at 11 06 38 AM

I think the LPC success banner is in progress - don't think it's been wired up yet, not sure what the behavior will be when wired

**Review by emilywools — APPROVED** [review]
LGTM, thanks @brenthagen

**Comment by brenthagen** [comment]
> Just gave this a run on my robot. I have been unable to do TLC, so I still have the "Calibrate Now" button. Does this button also need to be disabled when a run is taking place? Other than this, everything else appears to work just fine!
> 
> image

@sakibh spoke briefly with brian about this - eventually the run tab will be gated on a complete tip length calibration, so in the future a user should not be able to start a run with an incomplete tip length calibration.

**Comment by brenthagen** [comment]
there will be some possible conflicts with https://github.com/Opentrons/opentrons/pull/8896, so probably best to hold off merging until that PR is merged

**Review by b-cooper — APPROVED** [review]
Looks good to me 🚢

**Pull request merged**
