### PR TITLE
feat(shared-data): add heater shaker 2d render key

### PR DESCRIPTION
**Pull request by sakibh**
# Overview

This PR adds the 2D render key for the heater shaker.

### CODE REVIEW

**Review by jerader — CHANGES_REQUESTED** [review]
This is looking very cool! Thank you for making this!

I plugged it into the `PowerOn` component so I can see what it looks like. And I think you have to change a few of the `"style": "fill:#999999;"` to better match the other 2d renders. I looked at an example of the other modules and looks like they use `#FAFAFAF4` as the fill color throughout.

Screen Shot 2022-03-17 at 2 02 48 PM

**Comment by howisthisnamenottakenyet** [comment]
@mmencarelli @jerader The last conversation I had about SVG module styling/colors is captured in this figma frame: https://www.figma.com/file/JcVc9XgI0nCZfOHUsiC4CM/Modules-Overview?node-id=507%3A1751

**Comment by sakibh** [comment]
image

I updated the colors so that it matches the other modules for now. We can definitely make changes in follow up PRs.

**Comment by mmencarelli** [comment]
> image
> 
> I updated the colors so that it matches the other modules for now. We can definitely make changes in follow up PRs.

works for me! Thanks for handling that @shlokamin

**Review by jerader — APPROVED** [review]
LGTM! 🌮

**Review by shlokamin — APPROVED** [review]
Thank you @sakibh this looks great 😄

**Pull request merged**
