### PR TITLE
build(app-shell): add OT-3 on device display build task

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview
This PR adds an app-shell make task to build an on device display build on the app. 

To make the app-shell bundle in linux arm64, we had to make `usb-detection` an optional import, because there is no linux arm 64 dist of usb-detection, and it's not necessary for the on device app.

Pairing credit to @mcous 

Closes [RCORE-64](https://opentrons.atlassian.net/browse/RCORE-64)

# Changelog

- Add ot-3 on device display build task

# Review requests
Run `make -C app-shell dist-ot3`, you should see a bundle show up in `app-shell/dist/linux-arm64-unpacked`

Theoretically this bundle should be able to be moved onto the OT-3 in `/opt/opentrons-app/` and just...work

# Risk assessment

Low

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
This looks good. I can't test it today, but I will Monday - ok if I merge it then?

One thing I'm kind of worried about is the exact optional dependency mechanism here. A while back we had some problems with something being stealth not installed; can we add a makefile task that does like `find node_modules/ -name usb-detection` and screams if it can't find it or something?

**Comment by shlokamin** [comment]
> can we add a makefile task that does like find node_modules/ -name usb-detection and screams if it can't find it or something?

well it won't be in there in the linux arm 64 dist cuz electron builder won't bundle it. it'll only ever bundle it in for our other OS dists. do you mean that in the app shell source code we should check if we're in the non on device app, and if so, scream if we can't find usb detection?

**Comment by sfoster1** [comment]
Also closes RET-225

**Comment by brenthagen** [comment]
@mcous @shlokamin we added a handful of changes:

 - `node_modules/usb-detection` was still making it into the electron build, confirmed by unpacking the asar bundle. we added an electron builder files pattern to exclude that directory.
 - apparently, the files patterns listed in the electron builder config are sensitive to order - none of the patterns after the app/dist -> ui FileSet rule, including `!Makefile` etc, were being recognized.
 - we added the `make push-ot3 host=192.168.1.153` task from https://opentrons.atlassian.net/browse/RCORE-75 : build, transfer, restart the app.

**Review by sfoster1 — APPROVED** [review]
Tested by pushing locally and it works! Awesome!

**Pull request merged**
