### PR TITLE
fix(api): throw error if no valid nozzle has tip

### PR DESCRIPTION
**Pull request by aaron-kulkarni**
Provide a check in all LLD functions(called manually or automatically during aspirate) that makes sure that if it's a 96-channel pipette, that at least one of the nozzles with a pressure sensor has a tip on it.

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

### CODE REVIEW

**Review by sfoster1 — CHANGES_REQUESTED** [review]
Tests please

**Review by CaseyBatten — COMMENTED** [review]
Some thoughts on this pertaining to partial tip:
Do we intend to allow LLD when handling partial tip configurations? Partial tip layouts of our pipettes can result in situations where the tip sensor is not actually covered by the tips we pick up, which could complicate this kind of check. Theres a handful of approaches to take to that problem, the simplest is probably to raise an error if you are attempting LLD with a partially configured pipette. The second case we could attempt is to only ensure we check for tips on the valid nozzles when we are in Full configuration, otherwise don't bother checking. 

Long term, we may want an adaptive approach, where we only check for validation if we are in a pipette configuration that should result in tips overlapping with sensors. This would be the most "accurate" approach, but would introduce a double standard for some configurations, but not others.

**Comment by sfoster1** [comment]
> Some thoughts on this pertaining to partial tip: Do we intend to allow LLD when handling partial tip configurations? Partial tip layouts of our pipettes can result in situations where the tip sensor is not actually covered by the tips we pick up, which could complicate this kind of check. Theres a handful of approaches to take to that problem, the simplest is probably to raise an error if you are attempting LLD with a partially configured pipette. The second case we could attempt is to only ensure we check for tips on the valid nozzles when we are in Full configuration, otherwise don't bother checking.
> 
> Long term, we may want an adaptive approach, where we only check for validation if we are in a pipette configuration that should result in tips overlapping with sensors. This would be the most "accurate" approach, but would introduce a double standard for some configurations, but not others.

The current implementation fixes this I think @CaseyBatten

**Review by sfoster1 — APPROVED** [review]
Great! Thank you!

**Pull request merged**
