### PR TITLE
feat(protocol-designer): Add defaults for air gap and delay

### LINKED ISSUE #6058: PD: getDefaultsForStepType default values for new air gap / delay fields
## Overview

This ticket addresses changes needed for the `getDefaultsForStepType` fn

### Defaults

```
aspirate_airGap_checkbox: false
aspirate_airGap_volume: null,

aspirate_delay_checkbox: false,
aspirate_delay_seconds: '1', // NOTE: factor out as a constant eg DEFAULT_DELAY_SECONDS
aspirate_delay_mmFromBottom: `${DEFAULT_MM_FROM_BOTTOM_ASPIRATE}`,

dispense_delay_checkbox: false,
dispense_delay_seconds: '1', // NOTE: factor out as a constant eg DEFAULT_DELAY_SECONDS
dispense_delay_mmFromBottom: `${DEFAULT_MM_FROM_BOTTOM_DISPENSE}`,
```

## Acceptance criteria

- New `moveLiquid` forms (aka Transfer step forms) should populate with default values for these fields
- To make things simpler for us, these fields should only be added when the `OT_PD_ENABLE_AIR_GAP_AND_DELAY` FF is enabled. If the FF is disabled, the fields should NOT exist as keys in the form.

(Note: it might be gross/difficult to pass the FF redux state to this fn, if that's the case, use `process.env.OT_PD_ENABLE_AIR_GAP_AND_DELAY` for now??)

### PR DESCRIPTION
**Pull request by Kadee80**
# Overview

closes #6058 

# Changelog

- feat(protocol-designer): Add defaults for air gap and delay

# Review requests

- [ ] defaults match ticket

_Question: The constants are all numbers, should we cast to strings here? I followed the pattern for other constants in this file and they are all numbers._

# Risk assessment

Low PD behind FF

### CODE REVIEW

**Review by IanLondon — APPROVED** [review]
that's a good point, we should probably cast all the numbers in `getDefaultsForStepType` to strings. We get away with it because the `value` of input fields automatically casts stuff to strings, but if FormData was actually flow-typed, it would expect `string` or in some cases `string | null` but not `number`

**Review by IanLondon — CHANGES_REQUESTED** [review]
Looks like `createPresavedStepForm.test.js` needs to be updated to include the new fields, and it expects a string `'1'` not number `1`

**Comment by Kadee80** [comment]
> that's a good point, we should probably cast all the numbers in `getDefaultsForStepType` to strings. We get away with it because the `value` of input fields automatically casts stuff to strings, but if FormData was actually flow-typed, it would expect `string` or in some cases `string | null` but not `number`

Should I cast the other constants as well? we have:

```
  DEFAULT_CHANGE_TIP_OPTION,
  DEFAULT_MM_FROM_BOTTOM_ASPIRATE,
  DEFAULT_MM_FROM_BOTTOM_DISPENSE,
  DEFAULT_DELAY_SECONDS,
```

**Review by IanLondon — APPROVED** [review]
:+1:

**Review by shlokamin — APPROVED** [review]
LGTM!

**Pull request merged**
