### PR TITLE
fix(app): Persist UpdateBuildroot during robot restart

### PR DESCRIPTION
**Pull request by mjhuff**
Closes RAUT-571, RAUT-769

# Overview

This PR adds the nice-modal-react library to create a top-level modal manager and refactors UpdateBuildroot to utilize the new modal manager. This enables the robot update flow to persist throughout the entire update process - no longer will UpdateBuildroot abruptly close during robot restart. 

See RAUT-571, the nice-modal-react library's Motivation section, and recent slack conversations addressing the need for a top level modal solution (and why nice-modal-react is a good choice). In short - decoupling modal rendering from conditions that control the rendering of ancestor components makes controlling modal rendering much simpler and helps future-proof modal development. NMR is a lightweight and zero-dependency solution.

### UpdateBuildroot persisting through robot restart
persistent update

# Test Plan
- Build this branch (make -C app-shell package). The signature validation warning is ok to ignore. 
- If necessary, downgrade a robot via zip-file.
- Update the robot to the latest version through the update banner that appears on DevicesLanding.

# Changelog
- Added the nice-modal-react library.
- Refactored UpdateBuildroot to the top-level modal manager.

# Review requests
- Test on a physical robot, please!

# Risk assessment
low

### CODE REVIEW

**Review by jerader — COMMENTED** [review]
Sure, why not ✨ i can't test this but `@ebay/nice-modal-react` seems easy to use and straightforward.

**Comment by jerader** [comment]
Also the package is licensed under MIT https://github.com/eBay/nice-modal-react/blob/main/LICENSE.md so i think we might need a copy of the license text & copyright notice in our documentation or something? 🤷

**Comment by sfoster1** [comment]
We have MIT-licensed deps already

**Review by jerader — APPROVED** [review]
lgtm!!

**Pull request merged**
