### PR TITLE
docs(api): replace single quotes with double quotes

### PR DESCRIPTION
**Pull request by erictleung**
# Overview

Replaced single quotes with double quotes in tutorial docs, both v1 and v2 docs. 

This also changes some example protocols, located in `api/docs/v2/example_protocols/`, which are Python files.

And a minor change, this also changes some random non-standard single quotes at the beginning of `api/docs/v2/tutorial.rst` to regular single quotes.

# Test Plan

N/A

# Changelog

- Replaced single quotes with double quotes in v1 docs
- Replaced single quotes with double quotes in v2 docs
- Replaced single quotes with double quotes in v2 example protocols

# Review requests

# Risk assessment

Low

### CODE REVIEW

**Comment by SyntaxColoring** [comment]
Thanks for the consistency cleanup!

@ecormany Thoughts on this? In the Python community in general, I don't think there's a strong convention for whether to use single- or double-quotes in API docs. [h11 uses double](https://h11.readthedocs.io/en/latest/api.html), [requests uses single](https://requests.readthedocs.io/en/latest/)...

The [Black](https://github.com/psf/black) formatter, which we use, prefers double-quotes, so I'd probably prefer switching everything to that.

**Comment by ecormany** [comment]
Thanks for opening this PR, Eric! I agree with Max that our standard _should be_ double quotes. We don't 100% adhere to Black (our code blocks use shorter line lengths and we tend to get rid of trailing commas in docs), but the fewer manual changes we have to make to Black-formatted code, the better.

That said, the branch name still states the goal: `make-quotes-consistent`. Eric, I'll leave it up to you if you want to keep this PR open to standardize in the opposite direction, or to close it.

**Comment by erictleung** [comment]
@SyntaxColoring @ecormany thanks for considering my PR! Happy to keep this open and ensure the docs have double quotes. I'll tag y'all again once I have an update.

**Comment by erictleung** [comment]
@SyntaxColoring @ecormany updates made. I went ahead and changed both v1 and v2 docs for thoroughness. I've updated the main PR body message as well to summarize all the changes. Thanks for reviewing!

**Review by ecormany — APPROVED** [review]
Thanks again for this, Eric. Above and beyond, going back to the v1 docs! (Those are effectively archived, but there's no prohibition against changing them, so we'll accept your edits.)

In reviewing, I tested:
- All modified .py protocol files pass `opentrons_simulate`.
- Built v2 documentation locally and visually inspected.

There are a couple remaining improvements that can wait until follow-up PRs. For example, the images on the Tutorial page contain code with single quotes. I don't think there's any possibility for confusion until I get a chance to update those (I have the source files for those images). And the docstrings that compose the API Reference also have some single quotes. I've ticketed both of those internally for a rainy day ☔

**Comment by ecormany** [comment]
@erictleung just so you know, even though these changes are merged, they won't go live until the next time we do a documentation deploy. I expect there will be one sometime this month.

**Comment by erictleung** [comment]
@ecormany awesome, I appreciate the heads up! Looking forward to it

**Comment by ecormany** [comment]
This is now deployed as part of the `docs@2.16_1` tag.

**Pull request merged**
