### PR TITLE
(chore)app: update labware image

### PR DESCRIPTION
**Pull request by skyewindsor**
Fixes a black line on a labware library image

### CODE REVIEW

**Review by koji — CHANGES_REQUESTED** [review]
5.1.0 is using a different folder so you need to update the following folder.
https://github.com/Opentrons/opentrons/tree/edge/app/src/organisms/Labware/LabwareDetails/images

Screen Shot 2022-05-10 at 4 37 23 PM


You need to put this modified image into `app/src/organisms/Labware/LabwareDetails/images`.

@mikecardarelli we will solve this issue first and put images into one folder(#10163), correct?

**Comment by skyewindsor** [comment]
@koji Got it! I updated the file in that location too. Let me know if that is correct, thanks

**Review by koji — APPROVED** [review]
The change looks good to me!

**Comment by koji** [comment]
Screen Shot 2022-05-10 at 6 35 47 PM

**Pull request merged**
