### PR TITLE
test(labware-creator): mock specific utils, not all utils

### LINKED ISSUE #8090: LC: don't mock ALL utils in a test
# Overview

Unless there's a specific reason, it's a bad practice to mock out `utils/` because that broadly replaces all utils with mocks. This can cause false positives and negatives depending on implementation details that shouldn't be the concern of the tests

# Acceptance Criteria

Audit all `jest.mock` calls of `utils` and eg instead of mocking the entire utils directory, mock just the functions you actually care about mocking, eg `jest.mock('../../../utils/isEveryFieldHidden')`.

### PR DESCRIPTION
**Pull request by IanLondon**
# Overview

Closes #8090 -- see ticket

# Changelog

# Review requests

- Good idea?
- This PR should only change tests, not app code, so as long as tests still pass we should be good

# Risk assessment

Low, LC tests only

### CODE REVIEW

**Comment by mcous** [comment]
> Good idea?

IMHO, no, this is a bad idea. The code under test treats the `utils` module like a single opaque thing:

```ts
// labware-library/src/labware-creator/components/sections/Description.tsx
// ...
import { isEveryFieldHidden } from '../../utils'
```

This is good! The TL;DR of why the change that this PR introduces is a bad idea is that if the test subject treats a thing as opaque, the tests should treat the dependency as opaque, too.

If we only mock out the single utility we are using, we're introducing two potential problems:

- We're turning the `utils` that the test subject "sees" into a [partial mock](https://github.com/testdouble/contributing-tests/wiki/Partial-Mock)
    - Read the linked post above, it explains why this is potentially bad far better than I can
    - TL;DR: mocks should be either complete or not used
        - If the mock is complete, the value of our test is to drive APIs and test interactions, and it will fail if we mess up our interactions in the test subject
        - If there is no mock, the value of the test is that it tests "does this thing work", and it will fail if our logic is bad anywhere in the tree
        - If the mock is partial, the value of the test is in question, because that sort-of-real-sort-of-not dependency means the test may fail for any number of reasons, not all of which are useful, which means a test suite that's harder to maintain and reason with
- Unnecessary couple of the tests to the implementation details of the `utils` dependency
    - The code under test is free to treat `utils` as an opaque thing
    - We could, hypothetically, turn `utils` into one giant `utils.ts` file (it would be a bad idea, but the point is we've structured our code to hide the implementation details of the `utils` dependency from its users)
    - If we restructured `utils` like this, tests would start failing for no reason because our tests for downstream users of the `utils` module are coupled to the implementation detail that `utils` splits itself up in a certain way

**Comment by IanLondon** [comment]
@mcous hmm it doesn't make any sense to me to treat `utils` as a module. It's just a directory gathering a bunch of functions that don't otherwise have a home.

What motivated this move was that I extracted some reused code into a new util, `getIsOpentronsTubeRack`, but because all of `utils` is mocked out indiscriminately in the tests, I'd have to go into each test that happened to use this util and set up a `when` return value for the util. But really I don't want to mock that out, it wasn't mocked before.

**Comment by mcous** [comment]
In a fit of mild stupidity, I also [responded to the original ticket](https://github.com/Opentrons/opentrons/issues/8090#issuecomment-880122507) instead of keeping all my feedback in one place. To keep things simpler, posting here too:

>Hard disagree. Mocking things out partially is a bad idea. I'm not totally familiar with the codebase, but if the problem is "utils is hard to mock", the root problem is not the mocking but either the tests, the dependency module, or the test subject itself. utils looks to contain a few entirely unrelated pieces of logic. If it can't be mocked wholesale without breaking the tests, either:
>
> 1. The tests are not written to be solely collaboration tests
> 2. The test subject is not written to be solely a collaborator, and is instead mixing delegation with actual logic
> 3. The dependency is not scoped to do one specific thing or set of things
>
> With anything named "utils", I'd say (3) is definitely in play. I'm not super familiar with this codebase, but I'd say (1) and (2) are likely in play, as well.
> 
> I post this talk all over the place, and I'll probably keep posting it for a while, but definitely give it a watch. It goes over my points above with much more eloquence (and actual examples) than I am capable of: https://blog.testdouble.com/talks/2018-03-06-please-dont-mock-me/

So, with that:

> hmm it doesn't make any sense to me to treat utils as a module. It's just a directory gathering a bunch of functions that don't otherwise have a home.

Our code _is_ treating `utils` like a module. If you think it doesn't make sense as its own module, it shouldn't be one. In general, I think `utils` modules (bags of functions that don't have a home) are a bad idea. Make a home for function based on theme, even if that theme only has one function, and things become more predictable, and you can mock precisely without risk of breaking random things.

> What motivated this move was that I extracted some reused code into a new util, `getIsOpentronsTubeRack`, but because all of utils is mocked out indiscriminately in the tests, I'd have to go into each test that happened to use this util and set up a when return value for the util. But really I don't want to mock that out, it wasn't mocked before.

This is definitely a warning sign! The tests are trying to tell you something here. But I don't think what they're trying to tell you is "the mock is too broad". I'd say they're telling you the `utils` dependency is too broad, and probably a bit of (1) and (2), above, as well

**Comment by IanLondon** [comment]
I'm down to delete `utils/index.js`, but I don't want these fns just floating around at the top level, I like having a `utils/` folder, but not a "utils module".

**Comment by mcous** [comment]
I think `utils` folder is slightly better than a `utils` module, but doesn't really solve the underlying problem, which is "we have a bunch of unrelated logic in one place that does / doesn't interact with each other in unexpected ways."
I would check out the four (?) functions in `utils` and see if any of these options were viable:

- Move closer / into a React component module that uses them, if they're only used in one React subtree
- Move the functions to existing modules that make sense
    - e.g. There is already a `labware-creator/fields` module, would it makes sense to put the `isEveryFieldHidden` logic somewhere in that module?
- Create new modules that aren't names `utils` that are more scoped by single-responsibility principle

**Comment by shlokamin** [comment]
Super late to this party, but I think i agree with @mcous about partial mocks. i've been keeping all of my utils in the labware position check separate for this reason

**Comment by mcous** [comment]
Closing after discussion in Slack

**Pull request closed without merging**
