### PR TITLE
fix(odd): fix SmallButton size for modals for Running Protocol screen

### PR DESCRIPTION
**Pull request by koji**
# Overview
Fix buttons' size in modals for Running Protocol screen (Brian's PR fixed SmallButton's sizing issue)

Screenshot 2023-04-21 at 2 39 17 PM

updated the modal type to the red frame version
Screenshot 2023-04-24 at 3 40 32 PM

# Test Plan
- Run a protocol and cancel run
- Run a protocol that will fail and wait til the failed modal shows up

# Changelog

# Review requests

# Risk assessment
low

### CODE REVIEW

**Comment by ewagoner** [comment]
There needs to be some padding between the two paragraphs but other than that it looks good. 

image

**Comment by koji** [comment]
> There needs to be some padding between the two paragraphs but other than that it looks good.
> 
> image

@ewagoner Thank for pointing out that.
I talked about the modal with Brian. I removed the code from RunningProtocol and I will re-activate the FailedModal when implement the Result screen.
Also I switched Run cancel modal from desktop modal to odd modal for Setup screen.

**Review by ewagoner — APPROVED** [review]
There's still no padding between the two paragraphs of text to match the design, but other than that they look good to me!

**Comment by koji** [comment]
> There's still no padding between the two paragraphs of text to match the design, but other than that they look good to me!

Got a response from Mel. I will set gridGap: 12px

**Review by ewagoner — APPROVED** [review]

**Pull request merged**
