### PR TITLE
fix(app) truncate module temps

### PR DESCRIPTION
**Pull request by sfoster1**
We display temperature as only integer values, and that's something that should be enforced in the view layer.

## Risk Assessment
Low, just about displaying values set in the protocol

### CODE REVIEW

**Review by nusrat813 — APPROVED** [review]
Tested - working as intended

**Review by sanni-t — CHANGES_REQUESTED** [review]
Would this affect thermocycler temperatures? I think thermocycler temperatures should show fractional temperatures because you can actually set them as such.

**Comment by sfoster1** [comment]
> Would this affect thermocycler temperatures? I think thermocycler temperatures should show fractional temperatures because you can actually set them as such.

Wait you can? That's actually precisely what this was intended to change

**Comment by sanni-t** [comment]
Yep, you should be able to set fractional temperatures for thermocycler. The module has +-0.5C accuracy and the firmware allows you to set fractional temperatures

**Comment by sfoster1** [comment]
Not the underlying issue

**Pull request closed without merging**
