### PR TITLE
fix(app): fix UpdateAppModal style

### PR DESCRIPTION
**Pull request by ncdiehl11**
Closes [RQA-2675](https://opentrons.atlassian.net/browse/RQA-2675)

# Overview

fix padding, border, and buttons on UpdateAppModal according to designs

Screenshot 2024-05-09 at 4 37 17 PM

# Test Plan

- trigger update app modal
- verify style fixes

# Changelog

- convert footer buttons to `PrimaryButton` and `SecondaryButton` components
- add border to top of footer
- add padding to footer

# Review requests

js

# Risk assessment

low

[RQA-2675]: https://opentrons.atlassian.net/browse/RQA-2675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jerader — APPROVED** [review]
lgtm!

**Review by mjhuff — APPROVED** [review]
Looks good, thanks for updating

**Comment by mjhuff** [comment]
Looks good with the the `hr`s 🚀

**Review by mjhuff — APPROVED** [review]
Looks good with the the new `hr`s 🚀

**Pull request merged**
