### PR TITLE
test(robot-server): add test for openapi.json endpoint

### PR DESCRIPTION
**Pull request by y3rsh**
# Overview

TDD beginning of the fix for [this bug](https://opentrons.atlassian.net/browse/RSS-182) 

# Test Plan

- This test passes.
- Consider test for /redoc? Cannot be in Tavern, Tavern can't validate text response?
- Test for the /docs?
- Unit test needed around the actual model issue causing the bug?

# Review requests

# Risk assessment

### CODE REVIEW

**Review by mcous — DISMISSED** [review]
This is a good start. FastAPI will only 2xx on this endpoint if the response is a valid OAS

**Review by SyntaxColoring — COMMENTED** [review]
If you want to avoid the full integration test server startup/shutdown overhead, you can also call `robot_server.app.openapi()` from a regular pytest test.

```
pipenv run python

Python 3.7.13 (default, May 25 2022, 15:43:09)
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import robot_server

>>> robot_server.app
<fastapi.applications.FastAPI object at 0x101110350>

>>> robot_server.app.openapi()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maxpm/.local/share/virtualenvs/robot-server-VZRI-xOE/lib/python3.7/site-packages/fastapi/applications.py", line 146, in openapi
    servers=self.servers,
  File "/Users/maxpm/.local/share/virtualenvs/robot-server-VZRI-xOE/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 388, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "/Users/maxpm/.local/share/virtualenvs/robot-server-VZRI-xOE/lib/python3.7/site-packages/fastapi/utils.py", line 28, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.dataclasses.CalibrationStatus'>
```

I'm getting déjà vu. I really thought we had a test like this already, and I made the same suggestion. But I can't find it, so I guess not. Unless this rings a bell for anyone else?

**Comment by sanni-t** [comment]
@y3rsh do you plan on adding more tests? If not, and if this PR is ready for merging, maybe we can merge it into #12175

**Comment by y3rsh** [comment]
Added this as an integration test on #12175

Thank you for the comments.  I like what Max showed.  I was not sure where/how exactly to get that into test form.
Leaving it integration for now, but want to come back around.

**Pull request closed without merging**
