### PR TITLE
feat(robot-server): add modules field to /runs responses

### LINKED ISSUE #10432: feat(robot-server): add top-level `modules` field to `/runs` response models
## Overview

As an HTTP client, I would like to quickly get the IDs of loaded modules so that I can issue live commands over HTTP on those modules.

The `Run` resource model from the various `/runs` response models had fields for loaded `pipettes` and `labware`, but lacks a similar field for `modules`.
This change would establish more symmetry between the `ProtocolAnalysis` and the `Run` resource models.

## Implementation details

- The object that feeds `labware` and `pipettes` is the `StateSummary`
- `StateSummary` has a `modules` field, populated by `LoadedModule` Pydantic models
    - I _think_ there's a TODO comment on `StateSummary` that this ticket will address 
- `StateSummary.modules` can feed directly into a new `Run.modules` field

## Acceptance criteria

All endpoints that return `Run` resources return them with `modules`

- [ ] `GET /runs`
- [ ] `POST /runs`
- [ ] `GET /runs/:runId`
- [ ] `PATCH /runs/:runId`

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR takes existing modules data from the ProtocolEngine / persistence layer to populate the `/runs` responses with a `modules` field to match `pipettes` and `labware`.

Closes #10432

## Changelog

- add modules field to /runs responses
- remove module definition from public `LoadedModule` model
    - For the same reason we do not return labware definitions in the `LoadedLabware` model

``` js
// GET /runs/:run_id, after load commands have been handled
{
    "data": {
        "id": "17681ee6-2725-4cab-a2f8-710a9d79d0cd",
        "protocolId": "20a74150-8cb1-4361-af9b-4f7d20b84d9a",
        // ...
        "modules": [
            {
                "id": "module-0",
                "model": "magneticModuleV1",
                "location": {
                    "slotName": "4"
                },
                "serialNumber": "dummySerialMD"
            }
        ],
        "pipettes": [
            {
                "id": "pipette-0",
                "pipetteName": "p300_single",
                "mount": "right"
            }
        ],
        "labware": [
            {
                "id": "fixedTrash",
                "loadName": "opentrons_1_trash_1100ml_fixed",
                "definitionUri": "opentrons/opentrons_1_trash_1100ml_fixed/1",
                "location": {
                    "slotName": "12"
                }
            },
        ],
    }
}
```

## Review requests

Other than code and test review, smoke testing on a robot or emulator would be helpful. I expect these changes to be friendly to our persistence layer (even if your table has data from `edge`, where module definitions were still part if `LoadedModel`), so if you encounter any persistence issues, please highlight them!

## Risk assessment

Low

### CODE REVIEW

**Comment by mcous** [comment]
I _think_ CI failures are due to this PR relying on the Decoy update in #10459. I must've had my local virtualenv still set to the deps in that branch rather than `edge` when I pushed _this_ branch up

**Review by b-cooper — APPROVED** [review]
🌡️ 🏑 🏃

**Review by sanni-t — APPROVED** [review]
Haven't tested but code changes lgtm!
Good call on removing module definitions.

**Comment by mcous** [comment]
Smoke tested on OT-2R, behavior checks out

**Pull request merged**
