### PR TITLE
feat(protocol-designer): create color enhancement announcement modal

### PR DESCRIPTION
**Pull request by jerader**
closes RLIQ-424

# Overview

Creates announcement modal for the PD 6.2 release features

# Changelog

- add object with modal info to `announcements` and format.
- add the gif

# Review requests

- look in sandbox, does the gif work as expected and look high enough quality?

# Risk assessment

low

### CODE REVIEW

**Comment by koji** [comment]
@jerader could you share the sandbox link?

**Comment by koji** [comment]
I'm not familiar with pd code but for this AnnouncementModal, it would be good without `overflow-y: scroll`.

Screenshot 2022-12-15 at 4 47 17 PM

**Comment by jerader** [comment]
> @jerader could you share the sandbox link?

@koji sure - http://sandbox.designer.opentrons.com/pd_announcement-modal-liquid-enhancements/

Basically, to get the sandbox for any PD branch, after the build is complete, you do  `http://sandbox.designer.opentrons.com/branchName/`

**Review by koji — APPROVED** [review]
On sandbox I don't see overflow-y thing and gif is displayed properly. 


Screenshot 2022-12-15 at 7 15 34 PM

**Comment by koji** [comment]
> > @jerader could you share the sandbox link?
> 
> @koji sure - http://sandbox.designer.opentrons.com/pd_announcement-modal-liquid-enhancements/
> 
> Basically, to get the sandbox for any PD branch, after the build is complete, you do `http://sandbox.designer.opentrons.com/branchName/`

@jerader thanks, that is good to know!

**Pull request merged**
