### PR TITLE
chore(api,robot-server): remove aiohttp endpoints

### LINKED ISSUE #5726: chore(api): delete web service code
Now that robot-server is handling HTTP requests using fastAPI, we can remove the aiohttp service in api project.

In the process of porting to fastapi much of the logic in the aiohttp http handlers was moved to other parts of the api project. That means that all code under `api/src/opentrons/server` should be ready for removal.

- [ ] All needed code not directly related to http handling is moved out of `api/src/opentrons/server`
- [ ] `api/src/opentrons/server` removed
- [ ] api's aiohttp dependency is removed

### PR DESCRIPTION
**Pull request by amitlissack**
## overview

Remove aiohttp endpoints from opentrons package.

## changelog

Remove the entire server package and tests

## review requests

- [x] Is it too soon to lose this? Serving from fastapi has been active since 3.18
- [x] Should `opentrons.main` be renamed? There is no entry point there. `api_initialize.py`? `opentrons_initialize.py`? Move everything to `__init__.py`?

## risk assessment

none. this code is not used.

closes #5726

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
🙌 

This is just the http endpoints right? Would you mind retitling the pr to reflect that?

**Comment by Laura-Danielle** [comment]
> Should opentrons.main be renamed? There is no entry point there. api_initialize.py? opentrons_initialize.py? Move everything to __init__.py?

I think we should move everything to `__init__.py` since most of the functionality is gone. 

In terms of whether this is too soon, I'm OK with deleting it now. If a user encounters a bug with the robot-server, they can either downgrade while we fix the bug and/or wait to fix the bug.

**Comment by sfoster1** [comment]
> > Should opentrons.main be renamed? There is no entry point there. api_initialize.py? opentrons_initialize.py? Move everything to **init**.py?
> 
> I think we should move everything to `__init__.py` since most of the functionality is gone.
> 
> In terms of whether this is too soon, I'm OK with deleting it now. If a user encounters a bug with the robot-server, they can either downgrade while we fix the bug and/or wait to fix the bug.

I disagree with that - package level `__init__` is not the right place because that's the one file guaranteed to be executed when this package is imported for any purpose. I think a `setup` or `initialize` package is a good idea.

**Review by sfoster1 — APPROVED** [review]
Hmm looking at what's in `__init__` it's not actually that much code, looks good to me!

**Review by sanni-t — APPROVED** [review]
LGTM!
Did a quick smoke test on the robot and everything worked as expected 
👾

**Pull request merged**
