### PR TITLE
fix(api):  can't find pipettes

### PR DESCRIPTION
**Pull request by amitlissack**
# Overview

When smoothie is echoing commands in responses the read pipette id and name fail and pipettes are not identified.

`_remove_unwanted_characters` needs to be able to remove the whole echoed command.

## Background

The recent change to `SmoothieDriver_3_0_0` standardized commands to separate gcodes and parameters with a space.  `_remove_unwanted_characters` relied on a lack of spaces to remove echoed commands in response.

If command was `M369L M370L`, `_remove_unwanted_characters` would split the command at space and remove each substring from the response. Hence it would remove `M369L` and `M371L`.

## Bugs

After gcode refactor the command became `M369 L`. 
A response like this:
`M369 L \r\n\r\nL:5032304D56323032303230303432323036000000000000000000000000000000`
would become:
`:5032304D56323032303230303432323036000000000000000000000000000000`
This is a bug! The `L` was removed because `L` was considered a command by `_remove_unwanted_characters`. This results in a parse error. There's no mount.

## This bug

The partial hacky remedy was to not count 1 letter tokens as commands.
so `M369 L \r\n\r\nL:5032304D56323032303230303432323036000000000000000000000000000000`
became `L L:5032304D56323032303230303432323036000000000000000000000000000000`
This was still a bug. The response parser splits the response at colon and would think the mount is `L L`. This was from poor unit test from yours truly.

# Changelog

This change removes the entire command from the echoing response along with the partial command components.

# Review requests

Make sure that smoothie communication is working even when command echo is on.

I don't understand this function. Why does it not just remove the echoed portion in one piece? Why does it split the command and remove the parts?

# Risk assessment

Pretty high.

### CODE REVIEW

**Review by mcous — APPROVED** [review]
I have no clue what's going on with our Smoothie comms but the test case you added looks good

**Review by sfoster1 — APPROVED** [review]
The smoothie communication is awful but this does fix it on my robot and the code and test look good

**Review by Laura-Danielle — APPROVED** [review]
LGTM and makes sense, but we should have QA test to verify.

**Review by nusrat813 — APPROVED** [review]
LGTM

**Review by ahiuchingau — APPROVED** [review]
Solved the problem on my robot! ⚡️ Code looks good to me

**Pull request merged**
