### PR TITLE
chore(bump): 4.2.1

### PR DESCRIPTION
**Pull request by Laura-Danielle**
# Overview
Please review the release notes in `api/release-notes.md` and `app-shell/build/release-notes.md`

### CODE REVIEW

**Review by asogluizzo — APPROVED** [review]
LGTM

**Review by ahiuchingau — APPROVED** [review]

**Review by sfoster1 — CHANGES_REQUESTED** [review]
Sorry but can you remove the alpha versions from the changelogs so the entry for `4.2.1` contains all the changes since `4.2.0`

**Review by nusrat813 — APPROVED** [review]
LGTM after seths comments

**Review by sfoster1 — APPROVED** [review]
Looks good to me!

**Review by bndo — APPROVED** [review]
NICE! 👏

**Pull request merged**
