### PR TITLE
refactor(api): move PAPIv2 brokers and offset provider to legacy core

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR starts work on RCORE-103 by moving some equipment loading interfaces out of the public `ProtocolContext` class to ease the upcoming refactor of module loading. The two interfaces moved downwards in the stack are:

- `LabwareOffsetProvider`
    - Only needed for non-`ProtocolEngine` cores to read labware offsets from the `ProtocolEngine` (supplied via HTTP)
    - In the `ProtocolEngine`-based core, the offsets are loaded automatically
- `EquipmentBroker`
    - The `EquipmentBroker` is used by the `ProtocolRunner` to map equipment load events in PAPIv2 protocols to `ProtocolEngine` load commands
    - The `ProtocolEngine`-based core, native engine load commands are / will be used
 
## Review requests

Smoke test a LPC + protocol run with the feature flag off for safety. Probably requires real hardware to verify offsets are applied properly.

- [ ] LPC works with feature flag turned off

Manual smoke testing with the feature flag on isn't worth it for this PR, there are likely other issues that would prevent one from even getting to LPC. Look for a full smoke test plan in the final PR in this stack, which is still in progress.

## Risk assessment

Low. The main problems here are would be integration problems rather than logic problems. Most integration is well tested by our automated tests, but as stated above, **LPC needs manual to verification** that offsets continue to be applied after this refactor.

### CODE REVIEW

**Comment by mcous** [comment]
Current dependencies on/for this PR:
* edge
  * **PR #11443** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11443" target="_blank">Graphite</a>  👈
    * **PR #11437** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11437" target="_blank">Graphite</a> 
      * **PR #11449** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11449" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11443?utm_source=stack-comment).

**Comment by mcous** [comment]
Current dependencies on/for this PR:
* edge
  * **PR #11443** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11443" target="_blank">Graphite</a>  👈
    * **PR #11437** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11437" target="_blank">Graphite</a> 
      * **PR #11449** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11449" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11443?utm_source=stack-comment).

**Comment by mcous** [comment]
Current dependencies on/for this PR:
* edge
  * **PR #11443** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11443" target="_blank">Graphite</a>  👈
    * **PR #11437** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11437" target="_blank">Graphite</a> 
      * **PR #11449** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11449" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11443?utm_source=stack-comment).

**Comment by mcous** [comment]
Current dependencies on/for this PR:
* edge
  * **PR #11443** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11443" target="_blank">Graphite</a>  👈
    * **PR #11437** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11437" target="_blank">Graphite</a> 
      * **PR #11449** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11449" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11443?utm_source=stack-comment).

**Comment by mcous** [comment]
Current dependencies on/for this PR:
* edge
  * **PR #11443** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11443" target="_blank">Graphite</a>  👈
    * **PR #11437** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11437" target="_blank">Graphite</a> 
      * **PR #11449** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11449" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11443?utm_source=stack-comment).

**Review by jbleon95 — APPROVED** [review]
LGTM, reviewed this on screen share call as well

**Comment by mcous** [comment]
Smoke tested on an OT-2 and confirmed that LPC offsets are still properly used by a production PAPIv2 run

**Pull request merged**
