### PR TITLE
refactor(robot-server, api): Robot server move calibration

### LINKED ISSUE #5986: refactor(api,robot-server): move `opentrons.calibration` from api to robot-server
# Overview

The calibration flows belong in the `robot-server`. Reasons:
- The actions in the flow are exclusively driven by HTTP requests. 
- The flow code would benefit from using models and constants defined in robot-server and vice versa
- The calibration flow is not meant to be used by customers except via HTTP requests. Hence no need for it to be in distributed package.
- Isolate pydantic to robot-server

# Acceptance criteria

- [ ] `opentrons.calibration` is moved to `robot-server`

### PR DESCRIPTION
**Pull request by amitlissack**
# Overview

Move calibration check and tip length calibration flows to robot-server fro api

# Changelog

Created `robot_server.robot` package and moved `opentrons.calibration` into it.
Integrated `robot_server.robot.calibration` into robot-server
removed pydantic as dependency in API

# Review requests

Do you approve of `robot_server.robot` as a top level package?

# Risk assessment

Nearly None. Just a moving of code.

closes #5986

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
Nice, good step forward!

One worry - is this going to cause nasty conflicts with ongoing work from for  instance @b-cooper ?

**Review by b-cooper — APPROVED** [review]
Looks good to me. Also, in response to @sfoster1 's concern about ongoing work.  We planned on this reorganization anyway, so I've been ready to rebase my stuff either way. Should be all good. 🧊

**Review by Laura-Danielle — APPROVED** [review]
Makes sense to me

**Review by mcous — APPROVED** [review]
🎥

**Review by sanni-t — APPROVED** [review]

**Pull request merged**
