### PR TITLE
refactor(app):  making the selectors unique for LabwareInfoOverlay

### PR DESCRIPTION
**Pull request by reachojhaneha**
id={`LabwareInfoOverlay_slot_${labwareLocation.slotName}_offsetBox`}
id={`LabwareInfoOverlay_slot_${labwareLocation.slotName}_displayName`}
id={`LabwareInfoOverlay_${labwareLocation.slotName}_x`}
id={`LabwareInfoOverlay_${labwareLocation.slotName}_xValue`}
id={`LabwareInfoOverlay_${labwareLocation.slotName}_y`}
id={`LabwareInfoOverlay_${labwareLocation.slotName}_yValue`}
id={`LabwareInfoOverlay_${labwareLocation.slotName}_z`}
id={`LabwareInfoOverlay_${labwareLocation.slotName}_zValue`}

### CODE REVIEW

**Review by shlokamin — CHANGES_REQUESTED** [review]
id changes LGTM, you just need to add a semantic PR title!

**Comment by reachojhaneha** [comment]
the PR title semantic is changed.

**Comment by shlokamin** [comment]
this isn't adding a new feature so we don't want this showing up in our change logs. can you change it to a `refactor`?

**Comment by reachojhaneha** [comment]
changed to refactor

**Review by shlokamin — APPROVED** [review]
LGTM, though norrmally in our commit messages we use present tense: `making` => `make` so that the change logs read nicely. 

Check out the other commit messages in edge here: https://github.com/Opentrons/opentrons/commits/edge

**Pull request merged**
