### PR TITLE
docs(api): update broken and redirecting support links

### PR DESCRIPTION
**Pull request by ecormany**
# Overview

A couple links to support articles on the Welcome page were broken, and a couple more were redirecting. Updated all to directly to go the right URL.

# Changelog

- Updated 5 link URLs.

# Review requests

Click all the links under the Support header.

# Risk assessment

None, docs only.

### CODE REVIEW

**Review by SyntaxColoring — DISMISSED** [review]
The "Using Opentrons Software" and "troubleshooting" links ask me for a Salesforce login.

**Comment by ecormany** [comment]
@SyntaxColoring strange, they seem to be working for me [in the sandbox](http://sandbox.docs.opentrons.com/docs-fix-support-links/v2/)

**Comment by koji** [comment]
@SyntaxColoring @ecormany 
On my end, all links work without a salesforce login.

**Review by jerader — APPROVED** [review]
the links all work for me!

**Comment by SyntaxColoring** [comment]
Yep, sorry for the false alarm!

I think what happened is if you go to sandbox.docs.opentrons.com/docs-fix-support-links (without `/v2` at the end), that redirects you to docs.opentrons.com/v2 (without the `sandbox` at the beginning). So I was looking at the wrong version.

**Comment by ecormany** [comment]
Oh yeah, I made that "fix" to the infinite redirect loop #9918 which is OK in production but totally introduced a pitfall in the sandbox. (April! I was so naive then! 😅) Maybe we can improve that on a rainy day…

**Pull request merged**
