### PR TITLE
refactor(protocol-designer): remove basename from router

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview

I guess hash router does not need a basename 🤷🏽  This PR fixes an issue where no route gets picked up by the router due to the route not matching a basename. This only affects sandbox links. 

## Test Plan and Hands on Testing

Visit https://sandbox.designer.opentrons.com/pd_fix-router and play around with the different routes and try refreshing/copying urls and pasting them into the browser. you should not get a 404.

## Risk assessment

Low

### CODE REVIEW

**Review by jerader — COMMENTED** [review]
seems to work well. Quick question, if i refresh the url, it still stays on the specific path? don't we want it to remove the `overview` and go to the landing page?


https://github.com/user-attachments/assets/e1473ca6-bebf-46da-b5d2-b58641c98900

**Comment by shlokamin** [comment]
> Quick question, if i refresh the url, it still stays on the specific path? don't we want it to remove the overview and go to the landing page?

hm yeah probably but i guess it depends on what route you try to access. are you thinking of something similar to what we do in the landing page? 

```js
  React.useEffect(() => {
    if (metadata?.created != null) {
      console.warn('protocol already exists, navigating to overview')
      navigate('/overview')
    }
  }, [metadata, navigate])
```

i guess we just have to define the right rules for each route. ex. if theres no data should we always route to root? and what property do we read to determine if there is "no data" and we should redirect?

**Review by jerader — APPROVED** [review]
approving this to fix sandbox on edge but want to make a followup ticket to address the comment

**Comment by shlokamin** [comment]
sounds good ill merge for now

**Pull request merged**
