### PR TITLE
fix(protocol-designer): add Eppendorf to removeOpentronsPhrases

### PR DESCRIPTION
**Pull request by koji**
# Overview
add Eppendorf to removeOpentronsPhrases

### after
Screenshot 2024-10-11 at 2 25 22 PM

close RQA-3321

## Test Plan and Hands on Testing
1. select ot-2
2. single channel pipette + gen1 + 10ul
3. click show all tips button

## Changelog
- add Eppendorf to removeOpentronsPhrases and add a test

## Review requests
low

### CODE REVIEW

**Review by ncdiehl11 — APPROVED** [review]
Looks good. It just hit me that maybe we should make this util case insensitive?

**Comment by koji** [comment]
> Looks good. It just hit me that maybe we should make this util case insensitive?

oh, that is an interesting idea.

**Comment by ncdiehl11** [comment]
> > Looks good. It just hit me that maybe we should make this util case insensitive?
> 
> oh, that is an interesting idea.

Can always add on if needed. Not sure if super necessary right now

**Comment by koji** [comment]
> > > Looks good. It just hit me that maybe we should make this util case insensitive?
> > 
> > 
> > oh, that is an interesting idea.
> 
> Can always add on if needed. Not sure if super necessary right now

@ncdiehl11 I will test your idea next week.
The thing is that Skye says, cutting `Eppendorf` isn't enough 😭 
Mel/Felix will give a solution to us.
We'll need to update something, so I'll keep this PR open.

**Review by jerader — APPROVED** [review]
nice!

**Pull request merged**
