### PR TITLE
feat(app-shell): update desktop app user license agreement

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview
This PR adds an actual EULA generated by our Legal team to our desktop app installers for Mac, Linux, and Windows.

Closes AUTH-534

Screenshot 2024-07-10 at 11 45 42 AM

Mac build: https://builds.opentrons.com/app/Opentrons-v7.3.1-mac-b44920-app_shell-update-license-confirmation_app-build.dmg
Windows build: https://builds.opentrons.com/app/Opentrons-v7.3.1-win-b44920-app_shell-update-license-confirmation_app-build.exe
Linux build: https://builds.opentrons.com/app/Opentrons-v7.3.1-linux-b44920-app_shell-update-license-confirmation_app-build.AppImage

# Changelog

- Add EULA for desktop app installers on Mac, Linux, Windows

# Review requests
Make sure EULA confirmation shows up in our app installers before the app actually opens.

# Risk assessment

Low

### CODE REVIEW

**Review by ncdiehl11 — APPROVED** [review]
⚖️

**Comment by koji** [comment]
@shlokamin 
requested Derek try AppImage since I think he is the only one who has Ubuntu(native).

**Comment by DerekMaggio** [comment]
Verified on Linux that EULA is displayed and app waits to load until it is accepted. 
Also verified that if you click to decline the app does not load and does not incorrectly set that the license is accepted

**Comment by DerekMaggio** [comment]
@shlokamin, I noticed that the eulaAccepted file ends up going in ~/.config/opentrons/ instead of ~/.config/Opentrons. It doesn't affect the functionality but that file is all by its lonesome in that directory.

**Comment by shlokamin** [comment]
@DerekMaggio huh that's interesting. as far as i can see where it gets stored is not configurable by electron-builder. thats weird though.

thanks for testing this!

**Pull request merged**
