### PR TITLE
refactor(app): update robot software update flow for unboxing

### PR DESCRIPTION
**Pull request by koji**
# Overview
[design]
https://www.figma.com/file/AoTLAYuWawlaWItB1umOjr/Release%3A-Opentrons-Flex-Touchscreen-Designs?type=design&node-id=7147-91378&t=D58715chNPzn7LFs-0

update the robot software update flow to align with hi-fi design.

# Test Plan
edit `config.json` 
```json
"unfinishedUnboxingFlowRoute": "/welcome"
```
restart a robot/dev kit
command `/sbin/reboot`

1. set up network flow
2. 
3. go to software update
This process will take some time and it depends on your network situation (at office around 3-4 min). Maybe the progress bar's animation on ODD is laggy. 
If the odd app shows, the robot software is updated already something.
change currentVersion in`app/src/redux/buildroot/selectors.ts` to the following.

```ts
const currentVersion = '0.0.0'
```

4. after updating the software, the app should show the rename
unfinishedUnboxingFlowRoute should be update to the following.
```json
"unfinishedUnboxingFlowRoute": "/robot-settings/rename-robot"
```

# Changelog
- update components that are related to robot software update

# Review requests

# Risk assessment
low

### CODE REVIEW

**Comment by koji** [comment]
- [x] test this on a dev kit

**Comment by ewagoner** [comment]
I'm unable to force a software update, even when setting line 131 of `app/src/redux/buildroot/selectors.ts` to `const currentVersion = '0.0.0'` and pushing it to the DevKit and rebooting. Is there something else I might need to do?

**Comment by ewagoner** [comment]
Screenshot 2023-05-19 at 11 08 17 AM
Screenshot 2023-05-19 at 11 07 30 AM

I was able to get to the update screens, but couldn't complete it. I did notice some centering and button sizing issues on these screens.

**Comment by koji** [comment]
> Screenshot 2023-05-19 at 11 08 17 AM Screenshot 2023-05-19 at 11 07 30 AM
> 
> I was able to get to the update screens, but couldn't complete it. I did notice some centering and button sizing issues on these screens.

@ewagoner thanks.

added BODERS.size3 to both screen and centralized text

**Review by ewagoner — APPROVED** [review]

**Pull request merged**
