### PR TITLE
refactor(protocol-engine): add EngineStatus to Session responses

### LINKED ISSUE #7870: HTTP protocol: run status of engine-backed protocol session
## Overview

As an HTTP API user, I would like to know the status of a run of my protocol session so that I can monitor the run.

## Acceptance Criteria

- [ ] GET /sessions endpoint includes information about run status
- [ ] Currently supported status:
    - Ready to run
    - Running
    - Completed
    - Failed

## Implementation Notes

- The `SessionBuilder` class can be adapted to take the status value
- The status value can be fed into `SessionBuilder` via a call by the route controller
- Something under the `SessionRunner` will probably need to be tracking the run status
    - Potentially the `AbstractFileRunner`, potentially something else, see how it shakes out

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR add an `EngineStatus` enum to the ProtocolEngine and reports it via `Session` responses. Closes #7870

## Changelog

- add EngineStatus to Session responses

## Review requests

- Do these statuses make sense?
- Does the logic work when running a protocol?

## Risk assessment

N/A, feature flagged endpoints

### CODE REVIEW

**Review by SyntaxColoring — APPROVED** [review]
Code looks great to me. Haven't tested on a robot yet.

**Review by sanni-t — COMMENTED** [review]
LGTM! Tested on the robot and worked correctly!

Just one thought- when a cancel/stop is issued while a command is executing, an immediate error is raised because of which the command that's executing gets appropriately marked as `failed`. So now, the session/engine status is marked as `failed`, but it failed because I stopped the execution so shouldn't that be counted as as `stopped` instead?

**Comment by mcous** [comment]
> Just one thought- when a cancel/stop is issued while a command is executing, an immediate error is raised because of which the command that's executing gets appropriately marked as failed. So now, the session/engine status is marked as failed, but it failed because I stopped the execution so shouldn't that be counted as as stopped instead?

Ah, interesting! Yeah that's not intended, will fix that up

**Review by sanni-t — APPROVED** [review]
Status updates to `stopped` correctly after changes.
🚀

**Pull request merged**
