### PR TITLE
refactor(shared-data): update TC schema v6 commands

### LINKED ISSUE #10137: PE, App, PD, Step-Generation, Shared-Data: Rename TC module schema v6 commands
# Overview

Rename all TC command names and parameters outlined in [the schema change doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3184656624/Modules+JSON+SchemaV6+commands+vs.+PAPIv2+v3+method+names) across the entire stack

# Implementation details

Make changes across PE, PD, SG, all types, and the actual schema v6 spec.

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview

This PR updates JSON schema v6 TC commands to match our updated interface. All frontend + backend changes to accommodate the schema change should be made in this PR.

Will close https://github.com/Opentrons/opentrons/issues/10137

# Changelog

-  Update TC schema v6 commands

# Review requests

# Risk assessment
Med

### CODE REVIEW

**Review by smb2268 — APPROVED** [review]
JS changes look good 👍🏻

**Review by sanni-t — COMMENTED** [review]
Python changes look good. 
To address in follow-up PR:
- adding `blockMaxVolumeUl` param to json schema and also in the PE (protocol engine) set temp commands
- adding the `setTargetBlockTemperature` command to the schema

**Comment by shlokamin** [comment]
thank you! are y'all planning on doing that before the beta is cut, or should i revert this merge commit? cc: @b-cooper

**Comment by sanni-t** [comment]
Recapping from slack convo: We won't need to revert the commit since it doesn't break any existing behavior. 
- `blockMaxVolumeUl` isn't used by any clients nor PE
- `setTargetBlockTemperature` exists in PE but isn't consumed by any entity
- `waitForTargetTemperature` exists in schema and not in PE but is not used by client/ PD. (And hence is not immediately needed in PE)

**Pull request merged**
