### PR TITLE
fix(api): disable motors during the pipette attach and detach position

### PR DESCRIPTION
**Pull request by Laura-Danielle**
## Overview

We don't know what pipettes are attached on the hardware controller side until we actually detect the pipette. This means that when the 96 channel gets attached for the first time the mount falls because there isn't enough current on the head motors to support it. We should instead auto-disengage all the ZA motors which will trigger the ebrake on the head board.

The motors will get re-enabled as soon as any movement is issued.

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
Looks good to me!

**Review by ahiuchingau — APPROVED** [review]
LGTM if tested

**Review by sfoster1 — CHANGES_REQUESTED** [review]
got some extra commits in there

**Comment by Laura-Danielle** [comment]
Closes to re-do the commit. Rebasing is not working for some reason.

**Pull request closed without merging**
