### PR TITLE
feat(app): heater shaker wizard thermal adapter page

### PR DESCRIPTION
**Pull request by jerader**
re #9283 

# Overview

This PR adds the 4th page of the heater shaker wizard where you attach the thermal adapter.

Screen Shot 2022-02-22 at 12 59 42 PM

# Changelog

- adds to `AttachAdapter` component and creates test

# Review requests

- locally, change the code in `ModuleSetup/index` to search for a model that you have so you can see the heater shaker setup wizard banner. Click on starting the wizard and click to the 4th page. 
- the design should match figma (I changed margins/paddings to match with a SPACING constant so component is not design perfect)
- there should be 3 boxes, 2 images and text, check to make sure it matches the design. Additionally, are the images blurry? They are pngs exported from figma.

# Risk assessment

low, behind ff

### CODE REVIEW

**Comment by mmencarelli** [comment]
No design feedback needed! We're applying design polish to these wizards in 5.2 :)

**Review by shlokamin — APPROVED** [review]
looks great! noticed a few things:
1. the numbers on the left (`2a`, `2b`, `2c`) are gray in figma but black in code
2. when i hit the `continue to attach thermal adapter` CTA, all of the primary CTAs stay black until clicking somewhere else. i don't think thats related to this branch, just mainly making a note of this

**Comment by jerader** [comment]
> 1. the numbers on the left (`2a`, `2b`, `2c`) are gray in figma but black in code

@shlokamin the dark grey [updated](https://opentrons.slack.com/archives/C023G49G8AJ/p1644453477483269) but the design currently is using the old dark grey. I did notify @howisthisnamenottakenyet about this and I think she just hasn't updated it yet.

**Comment by shlokamin** [comment]
ah gocha, i say merge away then!

**Pull request merged**
