### PR TITLE
fix(protocol-designer): fix the slot information cutoff issue

### PR DESCRIPTION
**Pull request by koji**
# Overview
modify `viewBox` of deck view

## before
Screenshot 2024-09-20 at 4 40 40 PM

## after
Screenshot 2024-09-20 at 4 40 55 PM

close RQA-3187

## Test Plan and Hands on Testing
import the attached protocol and click edit protocol button in protocol overview
[PD_deck_test.json.zip](https://github.com/user-attachments/files/17080717/PD_deck_test.json.zip)

## Review requests
Do you think we should modify viewBox more?
Screenshot 2024-09-20 at 4 52 44 PM

## Risk assessment
low

### CODE REVIEW

**Comment by jerader** [comment]
is the slot above A1 slightly cut off now? judging by the screenshots in your PR description 🤔 but the button looks like enough clearance to me!

**Comment by koji** [comment]
@jerader 

> is the slot above A1 slightly cut off now?

i think answer is no

Screenshot 2024-09-20 at 5 43 56 PM

**Comment by koji** [comment]
also fix text alignment

Screenshot 2024-09-20 at 5 59 56 PM

**Review by jerader — APPROVED** [review]
nice! thanks for fixing this. hopefully there is enough bottom clearance for the slot information but i think you tested a good example of a long labware and long adapter name on top of a module.

**Pull request merged**
