### PR TITLE
fix(shared-data): reduce 96chan pickup distance

### PR DESCRIPTION
**Pull request by sfoster1**
Keeps the lifetime nice and long.

Numbers from hardware.

### CODE REVIEW

**Review by Laura-Danielle — APPROVED** [review]
We don't need to update the drop tip value as well?

**Comment by sfoster1** [comment]
> We don't need to update the drop tip value as well?

Nope, different stresses I guess

**Review by ahiuchingau — APPROVED** [review]
⚙️

**Review by caila-marashaj — APPROVED** [review]
long live the gears

**Pull request merged**
