### PR TITLE
feat(app, components): align Liquid Setup UI with Figma

### LINKED ISSUE #11037: UI Updates for Liquid Setup
Small UI fixes for Liquid Setup in App:

- [ ] Align labware name column in liquids list view
- [ ] Adjust flex shrink on total volume so it doesn't shrink when window does
- [ ] Modal should scroll to highlighted liquid card on open
- [ ] Match Figma for well highlight styling

### PR DESCRIPTION
**Pull request by smb2268**
fix #11037

# Overview

A few UI fixes on liquid setup to align with the Figma designs

# Changelog

1.  Align labware name column in liquids list view
2.  Adjust flex shrink on total volume so it doesn't shrink when window does
3.  Modal should scroll to highlighted liquid card on open
4.  Match Figma for well highlight styling
5. # Review requests

Look over changes, let me know if anything else needs to be fixed!
# Risk assessment

Low

### CODE REVIEW

**Comment by mmencarelli** [comment]
**First round review on Liquid Setup work**

[Figma link to annotated frame](https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=2497%3A199326)

Looks great!

- [x] (1) Update padding to be .5rem on the buttons (currently it's 1rem on left and right side) 
- [x] (2) Can we have the stroke of the button that's active to also turn blue? you can see when you zoom in that the blue button is a just a fraction smaller without it. 
- [x] (3) Remove the background colour change on the hover state. 
- [x] (4) My cursor isn't changing to the hand clicker when I hover over these clickable elements
- [ ] (5) Any chance we could get this button out of this container like we have in the designs? 
- [x] (6) Needs .5rem between the liquidsListItem elements
- [x] (7) Double check the states on these list items. Enabled has no border and the hover uses what you currently have as enabled. 
- [x] (8) Tested out large amounts of text and it looks like the text alignment goes astray? 
- [ ] (9) Can we center this modal within the viewport? 
- [ ] (10) Update padding to 1rem all around this box 
- [x] (11) Make sure this spacing here is 24px total, looks like it's a bit more? 
- [x] (12) Can we play around with the blue gradient for each well? Feel free to eye it so it's visually similar to the intensity we have in the designs
- [x] (13) Remove the .5rem padding on the text that makes this section over the intended 1rem 
- [x] (&&) Do you know why the order of the liquids is displaying the way it is? Purple, liquid 4 is first even though it's the middle wells. The second on the list is the first on the labware and is number 2? 
- [x] (14) When I highlight the pink liquid it actually looks like it's on top of the well? and tinting the colour? Want to make sure it's just on the outside or behind the well 
- [x] (15) We should be able to support the modal being responsive to the user shrinking the app screen size down to 600px. Designs are in figma! 
- [ ] (16) Would it be possible to update the SVG background that we're using? I know this is a bigger change and happy to chat through the implications. The updated version does not include a trash. 
- [x] (17) I've been working with @koji to reduce the size of the deck map in the other steps on the page. Would you be able to sync with him to display this one at that same size? Also, a convo to keep in mind when we update the SVG (step 16) 
- [x] (18) Could we actually change functionality here? So when the user clicks on one of these labware's and opens this module automatically the first on the list of liquids to the left is highlighted? 

Screen Shot 2022-07-12 at 9 59 00 AM
Screen Shot 2022-07-12 at 9 59 08 AM
Screen Shot 2022-07-12 at 9 59 19 AM
Screen Shot 2022-07-12 at 9 59 25 AM
Screen Shot 2022-07-12 at 9 59 30 AM
Screen Shot 2022-07-12 at 9 59 34 AM

**Review by mmencarelli — CHANGES_REQUESTED** [review]
Changes above!

**Comment by smb2268** [comment]
@mmencarelli I have addressed everything that is checked off above! For the note 

> (&&) Do you know why the order of the liquids is displaying the way it is? Purple, liquid 4 is first even though it's the middle wells. The second on the list is the first on the labware and is number 2?

This was previously unsorted, I changed it to be in load order so it would match the order of liquids in the list view. Does that work?

For the remaining unchecked boxes, I made the three follow up tickets: 
https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/11144
https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/11143
https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/11142

**Review by mmencarelli — CHANGES_REQUESTED** [review]
**Round 2 Design QA**

[Figma link](https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/6.2-Liquid-Setup%2C-Changing-Deck-State%2C-Wizards?node-id=2497%3A199326)

- [x] (1) .5rem margin between these labware list elements
- [x] (2) Make sure text is wrapping!
- [x] (3) Can we adjust the padding inside these buttons to have 6px top and 8px button
- [x] (4) Just want to note that the slot number isn't showing up, could be an emulator thing
- [x] (5) .5rem margin between these liquid card elements
- [ ] (6) Adjust the margins here to match design
- [x] (7) Noticing that the entire viewport has the clickable cursor on it. 
- [x] (8) These go smaller!
- [x] (9) this should actually be an h3
- [x] (10) Maybe we bump up to drop-shadow(0 0 1.8px rgba(0, 108, 250, 1))? 
- [x] (11) Just caught this, in the design this text starts 24px in its container


Screen Shot 2022-07-15 at 11 15 36 AM
Screen Shot 2022-07-15 at 11 15 40 AM
Screen Shot 2022-07-15 at 11 15 44 AM

**Comment by smb2268** [comment]
@mmencarelli just pushed the second round of updates! #6 is going to be handled in the modal ticket that I made since that padding is part of our base modal component

**Review by sakibh — APPROVED** [review]
This all looks really good!

**Review by mmencarelli — APPROVED** [review]
Just a few changes! Looking soooo good! Once you push these, it's g2g. 

- [x] (1) Change only the padding-bottom on the flex-box containing the header for the table to be .5rem instead of 1rem. Top can stay 1rem. 
- [x] (2) Just noticed, but I actually have the modal open up at 720px wide. Is that something we can replicate? 
- [ ] (3) Sorry, I've just made this a rule for the base modal component. When the screensize is at 600px, could we add a 1.5rem margin outside of the modal? Example to the left for the calibration flow. 

** Caught one more thing: Same area as point #1, that content "Location, Labware Name, volume" should be our "label" font-size**

Screen Shot 2022-07-20 at 8 13 12 AM
Screen Shot 2022-07-20 at 8 13 17 AM
Screen Shot 2022-07-20 at 8 13 21 AM

**Comment by smb2268** [comment]
@mmencarelli perfect - I fixed 1,2 and 4 but added 3 to the modal ticket I made

**Pull request merged**
