### PR TITLE
refactor(api): move v2 protocol implementations to separate package.

### PR DESCRIPTION
**Pull request by amitlissack**
# Overview

This is a minor refactor as preparation for protocol engine work. A new set of context interface implementations will be created that send commands to the protocol engine.

This PR moves the existing v2 implementations to `opentrons.protocols.implementations.protocol_api` from `opentrons.protocols.implementations`. 

The assumption is that we will want to add new classes to `opentrons.protocols.implementations.protocol_engine` or something.

# Changelog

- move the existing v2 implementations to `opentrons.protocols.implementations.protocol_api` from `opentrons.protocols.implementations`. 

# Review requests

Naming, as usual.  `protocol_api` so overloaded. `v2`? `default`? `reference`? Someone help me!!

# Risk assessment

None

### CODE REVIEW

**Comment by SyntaxColoring** [comment]
> Naming, as usual. protocol_api so overloaded. v2? default? reference? Someone help me!!

I agree `protocol_api` is overloaded.

So we need `implementations.something` backend distinguished against a `implementations.protocol_engine` backend...

* `implementations.direct`?
* `implementations.v2` is also fine if we think that switching the default to `protocol_engine` would bump us to APIv3.

**Review by SyntaxColoring — COMMENTED** [review]
> Naming, as usual. protocol_api so overloaded. v2? default? reference? Someone help me!!

I agree `protocol_api` is overloaded.

So we need an `implementations.something` backend distinguished against a `implementations.protocol_engine` backend...

* `implementations.direct`?
* `implementations.basic`?
* `implementations.no_protocol_engine` or `implementations.no_engine`?
* `implementations.v2` works if we think that, when we eventually switch the default to `protocol_engine`, that would bump us to APIv3.

**Review by SyntaxColoring — APPROVED** [review]
Oops, meant to approve. Naming suggestions above, but I don't think they have to block this.

**Comment by amitlissack** [comment]
Closing this ticket in favor of tackling in a proper ticket #7380

**Pull request closed without merging**
