### PR TITLE
fix(protocol-designer,components): fix dropdown menu expands direction issue

### PR DESCRIPTION
**Pull request by koji**
# Overview
fix dropdown menu expands direction issue.

update DropdownMenu's prop to make things more understandable.
modify, Toolbox's height.
https://opentrons.slack.com/archives/C07E9T2NAQK/p1731536325870079?thread_ts=1731525319.924009&cid=C07E9T2NAQK

For LiquidToolbox, the nested structure is deeper than others (expected) but the UI layout is fixed so set menuPlacement="bottom". SelectModules and SelectFixtures are the same.

Screenshot 2024-11-14 at 4 07 17 PM

close RQA-3563

## Review requests
low

### CODE REVIEW

**Comment by ncdiehl11** [comment]
Still seeing issue on move labware dropdown
Screenshot 2024-11-14 at 4 17 44 PM

**Comment by jerader** [comment]
is this expected? i guess we may want to give the dropdown menu a max height or something? 

https://github.com/user-attachments/assets/7089429d-46c3-47e4-b3d3-41704e82690f

**Comment by koji** [comment]
> is this expected? i guess we may want to give the dropdown menu a max height or something?
> 
>  Screen.Recording.2024-11-14.at.16.19.27.mov

that is an expected behavior because DropdownMenu's height is set to display 10 items(Mel's request.)

**Review by jerader — APPROVED** [review]
lgtm, thanks for fixing this

**Comment by koji** [comment]
> Still seeing issue on move labware dropdown Screenshot 2024-11-14 at 4 17 44 PM

@ncdiehl11 
I couldn't see that.
Could you share the protocol you used?

Screenshot 2024-11-15 at 2 43 00 PM

**Pull request merged**
