### PR TITLE
refactor(hardware): add current position to payload

### PR DESCRIPTION
**Pull request by ahiuchingau**
The MoveCompleted message now returns the current position when a move finishes.

### CODE REVIEW

**Review by sfoster1 — DISMISSED** [review]
I think it's not a good idea to use the full 64bit value there. It should also probably be in millimeters rather than steps, but we can do that later - the 64bit value I think is essentially an implementation detail though, we want the high 32 bits.

**Comment by sfoster1** [comment]
Oh also i think this wants to be `refactor(hardware)`

**Review by amitlissack — APPROVED** [review]
Rockem

**Review by Laura-Danielle — APPROVED** [review]
nice

**Pull request merged**
