### PR TITLE
feat(scripts): automate promote to staging/prod/rollback for LL/docs

### PR DESCRIPTION
**Pull request by jerader**
# Overview

The Labware Library and docs s3 buckets are still in the root account and haven't been moved over to the PL Production account. This PR updates the `promote to staging`, `promote to production`, and `rollback` scripts to have branching logic that assumes roles into the root account, leaving PD to assume roles into the PL production account.

Additionally, a newly made `checkCurrentAWSProfile` and `promptUser` fn is created to check the user's AWS creds before promoting to staging and prod to ensure the user is on the correct profile.

# Test Plan

Test with dry runs using each project's latest tags. Run each of these at the root of the monorepo

The beginning of each should prompt you to type "Y/N" if you're on the correct aws profile to run the scripts.

1. `node ./scripts/deploy/promote-to-staging docs.opentrons.com docs@2.16` -> should see the text `Promotion to staging done`
2. `node ./scripts/deploy/promote-to-production docs.opentrons.com` -> should see the text `Promotion to production done`
3. `node ./scripts/deploy/promote-to-staging labware.opentrons.com labware-library@2.1.0-candidate-b` -> should see the text `Promotion to staging done`
4. `node ./scripts/deploy/promote-to-production labware.opentrons.com` -> should see the text `Promotion to production done`
5. for the rollback: `node ./scripts/deploy/rollback labware.opentrons.com production`/ `node ./scripts/deploy/rollback labware.opentrons.com staging` , `node ./scripts/deploy/rollback docs.opentrons.com production`/ `node ./scripts/deploy/rollback docs.opentrons.com staging`, `node ./scripts/deploy/rollback designer.opentrons.com production`/ `node ./scripts/deploy/rollback designer.opentrons.com staging`

# Changelog

- branching logic to assume roles into another account 
- branching logic to invalidate cache for each (staging/production, LL/docs/PD)
- create new fns `promptUser` to prompt yes or no and `checkCurrentAWSProfile` to let the user know which aws profile they are on
- add assume roles logic to the rollback script that wasn't added previous for PD but also includes assuming roles for LL and docs

# Review requests

see test test plan

# Risk assessment

low

### CODE REVIEW

**Review by sfoster1 — COMMENTED** [review]
Let's add a way to specify an aws creds profile to use

**Review by ecormany — APPROVED** [review]
Tested for docs only. It works!

**Comment by jerader** [comment]
> Let's add a way to specify an aws creds profile to use

@sfoster1 good idea! I'll look into this now

**Comment by ecormany** [comment]
Prompt on command line works and dry runs still succeed. ✅

**Review by sfoster1 — APPROVED** [review]
Looks good and works for me, thank you! Would you mind adding a prompt for the forgetful (😅) about using `AWS_PROFILE` though?

**Pull request merged**
