### PR TITLE
chore(mypy): fix cache cleanup

### PR DESCRIPTION
**Pull request by ahiuchingau**
# Overview
We haven't been properly clearing the mypy cache for some python directories when we do `make clean-py` because we were using the wrong paths. 

It seems like we don't clear pytest caches in most directories in the cleanup rules, is that intentional?

### CODE REVIEW

**Review by sfoster1 — COMMENTED** [review]
Do we have to? It does tend to slow things down. Maybe we can make `clean-extra` targets if we really want to?

**Comment by ahiuchingau** [comment]
> Do we have to? It does tend to slow things down. Maybe we can make `clean-extra` targets if we really want to?

Do you mean the pytest cache or mypy or both? Do you propose that I move the mypy cache and add pytest cache to a different target (makes sense and I'm very ok with that)? 

For context, I noticed this only because I was switching between branches that have different pipenv requirements and for some reason mypy was not behaving unless I manually removed the cache first. So I thought not clearing the cache properly was the problem. But now I can't seem to reproduce the same issue I was having so I'm stumped.

**Comment by sfoster1** [comment]
> > Do we have to? It does tend to slow things down. Maybe we can make `clean-extra` targets if we really want to?
> 
> Do you mean the pytest cache or mypy or both? Do you propose that I move the mypy cache and add pytest cache to a different target (makes sense and I'm very ok with that)?
> 
> For context, I noticed this only because I was switching between branches that have different pipenv requirements and for some reason mypy was not behaving unless I manually removed the cache first. So I thought not clearing the cache properly was the problem. But now I can't seem to reproduce the same issue I was having so I'm stumped.

Yeah the thing is that running mypy over and over with no cache is slower, and we always clean when we build, so you'd end up with slow behavior when you do normal dev processes. 

That said we definitely shouldn't have wrong paths in there, i wonder if having like `clean-build` removing `build/` and such and `clean:` removing all caches would be a good idea. then the build targets depend on `clean-build` and `clean` is only ever run by humans.

**Review by sfoster1 — APPROVED** [review]
looks good, ty!

**Pull request merged**
