### PR TITLE
chore(release): merge v4.3.1 release changes into edge

### PR DESCRIPTION
**Pull request by mcous**
## Overview

Merge changes from 4.3.1 into `edge`

## Review requests

It looks like we merged some typos in the changelog into the release branch

## Manual merge tasks

- [ ] Fix merge conflict in `protocol-designer/package.json`
- [ ] Bump version of `step-generation/package.json`
- [ ] Fix title URL in `CHANGELOG.md`
- [ ] Fix title URL in `app-shell/CHANGELOG.md`

### CODE REVIEW

**Comment by sfoster1** [comment]
The PD package json has a conflict and is actually the symbol of a problem we faced in 4.3.0 as well - @shlokamin split out a step-generation library that has its own package.json and is marked as a dep in the pd package.json that didn't get updated. What I did for 4.3.0 is make a dedicated merge branch:
```
git checkout release
git checkout -b chore_merge-4.3.1
git merge edge
# fixups including manually changing the topline version in opentrons/step-generation/package.json and updating the step-generation dependency version in opentrons/protocol-designer/package.json
git push --set-upstream origin chore_merge-4.3.1
```
and then close _this_ pr, and open a pr for `chore_merge-4.3.1`->`edge`. when that's approved, do a command line merge as you would for this pr:
```
git checkout edge
git pull
git merge --no-fastforward chore_merge-4.3.1
```

**Review by sfoster1 — CHANGES_REQUESTED** [review]
Uh see previous comment should have been a review

**Comment by mcous** [comment]
Merge fixes:

```diff
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: protocol-designer/package.json
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ protocol-designer/package.json:23 @
    "license": "Apache-2.0",
    "dependencies": {
      "@hot-loader/react-dom": "16.8.6",
-     "@opentrons/components": "4.3.0",
-     "@opentrons/step-generation": "4.3.0",
+     "@opentrons/components": "4.3.1",
++    "@opentrons/step-generation": "4.3.1",
      "@typeform/embed": "0.16.0",
      "ajv": "6.10.2",
      "classnames": "2.2.5",
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: CHANGELOG.md
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ CHANGELOG.md:6 @
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.

-## [4.3.1](https://github.com/Opentrons/opentrons/compare/v4.3.1...v4.3.1) (2021-05-10)
+## [4.3.1](https://github.com/Opentrons/opentrons/compare/v4.3.0...v4.3.1) (2021-05-10)

 ### Bug Fixes

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: app-shell/CHANGELOG.md
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ app-shell/CHANGELOG.md:6 @
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.

-## [4.3.1](https://github.com/Opentrons/opentrons/compare/v4.3.1...v4.3.1) (2021-05-10)
+## [4.3.1](https://github.com/Opentrons/opentrons/compare/v4.3.0...v4.3.1) (2021-05-10)

 **Note:** Version bump only for package @opentrons/app-shell

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: step-generation/package.json
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ step-generation/package.json:13 @
   "name": "@opentrons/step-generation",
   "productName": "Opentrons Step Generation",
   "private": true,
-  "version": "4.3.0",
+  "version": "4.3.1",
   "description": "Step generation",
   "main": "src/index.js",
   "bugs": {
@ step-generation/package.json:22 @
   "homepage": "https://github.com/Opentrons/opentrons",
   "license": "Apache-2.0",
   "dependencies": {
-    "@opentrons/shared-data": "4.3.0",
+    "@opentrons/shared-data": "4.3.1",
     "core-js": "3.2.1",
     "immer": "5.1.0",
     "lodash": "4.17.15"
```

**Review by sfoster1 — APPROVED** [review]
Yeah that LGTM! @shlokamin ?

**Review by shlokamin — APPROVED** [review]

**Pull request merged**
