### PR TITLE
fix(app): use Trans component for LPC i18n value tag

### PR DESCRIPTION
**Pull request by jerader**
closes RAUT-739

# Overview

Fix the LPC copy where we needed to bold some words

# Test Plan

Run through LPC on desktop and ODD and make sure the text doesn't have any <bold> tags visible. Make sure the words are bolded instead.

# Changelog

- use trans component to use multiple stylings in the same i18n string

Screen Shot 2023-09-18 at 4 08 30 PM
Screen Shot 2023-09-18 at 4 11 46 PM

# Review requests

see test plan

# Risk assessment

low

### CODE REVIEW

**Review by ecormany — APPROVED** [review]
Looks great in the diff, thanks for fixing what I broke! 💥 

I leave it to @koji to approve the rest of the implementation and test — I can't get my simulated Flex to launch LPC 😖

**Comment by koji** [comment]
@jerader @ecormany 
I will test this branch with app&ui bot soon.

**Comment by koji** [comment]
The changes look good to me, but I still see.

Screenshot 2023-09-18 at 5 47 54 PM

`app/src/organisms/LabwarePositionCheck/PickUpTip.tsx` but I don't see the issue in the code.

**Review by koji — APPROVED** [review]
Never mind, I thought I pushed this branch but actually I pushed robot-server instead of this branch...
The changes look to good to me and bold was displayed correctly.

**Pull request merged**
