### PR TITLE
fix(app): add overflow prop for long name

### LINKED ISSUE #10505: 6.0 Feedback:  35 character name of robot moves the elements of robot details header to move right
### Overview

_No response_

### Current Behavior

Screen Shot 2022-05-27 at 11 48 28 AM

### Expected Behavior

_No response_

### Steps To Reproduce

1. Rename the robot of 35 character
2.  Goto robot details page
3.  components are moved to right in the header section

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
Add overflow prop to display robot name and protocol name without breaking ui
fix #10505 #10481

Screen Shot 2022-05-27 at 6 50 36 PM

Screen Shot 2022-05-27 at 6 50 45 PM

Screen Shot 2022-05-27 at 7 03 35 PM

# Changelog

# Review requests

# Risk assessment

### CODE REVIEW

**Comment by koji** [comment]
@mmencarelli 
Could you review this PR before requesting a review from devs?

**Review by jerader — APPROVED** [review]
lgtm!

**Comment by mmencarelli** [comment]
this also looks good to me!

**Review by sakibh — APPROVED** [review]
✅

**Pull request merged**
