### PR TITLE
refactor(app): h-S Adjust wizard order and add open latch button

### LINKED ISSUE #10563: Adjust order and add open latch button in set up wizard
# Overview

The DVT H-S latches are way tighter than the EVT version, so we'd like to offers users the open/close latch button during the set up step to make it easier to load labware.  In order to do this, we'll also need to adjust the order of steps so connecting to the module happens earlier, so that we can send the open latch command. 

# Implementation Details
- Swap "Power on" and "Attach thermal adapter" steps in the the set up wizard
-- Power on the module is moved from step 3 to step 2 of the set up wizard
-- Attach Thermal Adapter is moved from step 2 to step 3 of the set up wizard
- Add Labware Latch button in step 2a of attach thermal adapter step. The button has the same functionality as labware set up section of pre-run set up
-- If latch is open, button should read "Close Labware Latch"
-- if latch is closed, button should read "Open Labware Latch"
-- button is disabled if module is shaking or disconnected
- CTAs in each step need to be adjusted accordingly 
-- "Continue to power on module" is CTA for page 3
-- "Continue to attach thermal adapter" is CTA for page 4
-- "Continue to test shake" is CTA for page 5

# Design Links
- https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=4795%3A92514

# Acceptance Criteria
- [x] Power on the module is step 2 (page 4) of the set up wizard
- [x] Attach Thermal Adapter is step 3 (page 5) of the set up wizard
- [ ] Labware Latch button has been added to "Attach thermal adapter" step per design. The button has the same functionality as labware set up section of pre-run set up (If latch is open, button should read "Close Labware Latch"; if latch is closed, button should read "Open Labware Latch"; button is disabled if module is shaking or disconnected)
- [x] CTAs in each step have been adjusted to reflect the updated flow ("Continue to power on module" is CTA for page 3; "Continue to attach thermal adapter" is CTA for page 4; "Continue to test shake" is CTA for page 5)

### PR DESCRIPTION
**Pull request by jerader**
closes #10563

# Overview

Reorders the pages and adjusts the text accordingly. Also adds a labware latch button on the Attach adapter page.

Screen Shot 2022-06-03 at 10 13 50 AM

Screen Shot 2022-06-03 at 10 14 05 AM

Screen Shot 2022-06-03 at 10 13 31 AM

# Changelog

- adjust `HeaterShakerWizard`, `PowerOn`, and `AttachAdapter`

# Review requests

- go through the wizard without a protocol and with a protocol. It should match the designs. On the `AttachAdapter` page, there should be a button that allows you to open or close the labware latch. It should be wired up and working properly.
- if the heater-shaker is already shaking, the labware latch button should be disabled with a tooltip saying that the H-S is shaking. 

# Risk assessment

low, h-s

### CODE REVIEW

**Comment by vabruzzo** [comment]
This looks good to me and works as expected.

One small question, when I click the open/close latch button there seems to be a 1-2 second delay. At quick glance it doesn't seem like there is a way to give some kind of user feedback in this state, perhaps a disabled button or something, has that come up in ux discussions for buttons that do these kinds of async tasks?

**Review by vabruzzo — APPROVED** [review]

**Review by shlokamin — APPROVED** [review]
🚢

**Review by sakibh — APPROVED** [review]

**Review by howisthisnamenottakenyet — CHANGES_REQUESTED** [review]
I did notice on Step 1 of 4 I don't see the "Step 1 of 4" header. Is that just due to scrolling?
Otherwise looks good!

**Comment by jerader** [comment]
> I did notice on Step 1 of 4 I don't see the "Step 1 of 4" header. Is that just due to scrolling? Otherwise looks good!

@howisthisnamenottakenyet , yup that is due to scrolling, sorry! Here is the top bit of the page: 

Screen Shot 2022-06-07 at 12 55 45 PM

**Comment by jerader** [comment]
> One small question, when I click the open/close latch button there seems to be a 1-2 second delay. At quick glance it doesn't seem like there is a way to give some kind of user feedback in this state, perhaps a disabled button or something, has that come up in ux discussions for buttons that do these kinds of async tasks?

@vabruzzo, ya I've noticed this slight delay with all module commands. Not sure if there have been discussions about it.

**Review by howisthisnamenottakenyet — APPROVED** [review]

**Pull request merged**
