### PR TITLE
ci(api,shared-data): run test matrix on Python 3.7 thru 3.10

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR adds a CI matrix for Python 3.7 through 3.10 for our pip-installable packages: `opentrons` and `opentrons_shared_data`.

Takes over for the CI portion of #9368 for review and git history purposes.

## Changelog

- Bump pytest to v7 for Python 3.10 support
- Ensure `Pipfile.lock` behaves on Python 3.7 all the way to Python 3.10
- Add unit test runs to the CI matrix for Python >= 3.7 for these packages
- Mark `setup.py` with support for Python >= 3.7

## Review requests

- [ ] Changes look good
- [ ] This PR does not affect your local 3.7 dev environment
- [ ] This PR allows you to set up a local 3.10 dev environment

With this PR and a copy of Python 3.10 installed somewhere on your system (e.g. via `pyenv`), to set up a venv in a new Python version:

```shell
# tear down the old environment
make -C app teardown

# set up a new dev environment with the given Python version
make -C app setup pipenv_opts="--dev --python 3.10"
```

## Risk assessment

No risk to production environment. However, for our dev environment, runs the following risks:

- CI runs for `api` and `shared-data` will likely take more time
- Most developers will continue to run local 3.7 environments, so the risk of introducing changes that break in >= 3.8 is high
    - However, CI should catch these failures
    - So, this turns into a risk of time wasted rather than a risk of breaking stuff

### CODE REVIEW

**Review by sfoster1 — COMMENTED** [review]
I think this is going to make these tests take a) forever by wall clock and b) use way more github actions runners, which is something we're already fairly frequently rate limited on.

Can we investigate using something like [tox](https://tox.wiki/en/latest/) to do it inside a single runner?

**Comment by y3rsh** [comment]
@sfoster1 @mcous 

> I think this is going to make these tests take a) forever by wall clock and b) use way more github actions runners, which is something we're already fairly frequently rate limited on.
> 
> Can we investigate using something like [tox](https://tox.wiki/en/latest/) to do it inside a single runner?

I am not sure if tox solves our problem.  We would still need 3 OS runners customized to have the 4 versions of python installed making 3 long running runners.  Other folks seem to use the [matrix](https://github.com/tox-dev/tox-gh#workflow-configuration) even with tox. 

Regardless of this, I would like to know how we are hitting rate limits.  I see usage of runners increasing so I would like to spearhead solutions.  Besides @bndo who else might be good pull into conversation on this?

**Comment by mcous** [comment]
For reference, here's a full matrix run with everything passing from an earlier iteration of this branch: https://github.com/Opentrons/opentrons/actions/runs/1792647885

Each job in the matrix took 5 to 10 minutes, depending on OS

**Review by sfoster1 — APPROVED** [review]
Looks good to me, then! Love to see the changes

**Pull request merged**
