### PR TITLE
chore: remove worst log spam offenders

### PR DESCRIPTION
**Pull request by sfoster1**
robot-server
-------------

A lot of internal middleware was putting pretty verbose logs in both the unit log (i.e. journalctl -u opentrons-robot-server),which I think is reasonable, and to the syslog ident opentrons-api (i.e.journalctl -t opentrons-api), which I think is not. This includes every sql statement the robot server ever makes, every http route interaction...

By adding some handlers that specifically only log to journald without the syslog ident and some that have both, we can tune what goes where. Now,
- sqlalchemy output _above or at warn_ will go to the syslog ident, since it's likely to be an issue
- sqlalchemy output below warn will go only to robot-server unit logs
- http middleware output goes to only robot-server unit logs
- general robot_server logs originating from our code go to the syslog ident

Note that when a log "goes to the syslog ident", that's in addition to the unit logs. So if you want to know everything include http messages and such, do journalctl -u opentrons-robot-server and if you want to know just robotics relevant stuff do journalctl -t opentrons-api.

api and hardware
---------------

Don't log every dang motion group

# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

### CODE REVIEW

**Comment by sfoster1** [comment]
For an example of what this does, here's the output of `journalctl -t opentrons-api` during server startup:
```
Apr 24 18:01:26 be088a opentrons-api[52694]: API server version: 0.4.0
Apr 24 18:01:26 be088a opentrons-api[52694]: Robot Name: FlexyMCFlexFace
Apr 24 18:01:27 be088a opentrons-api[52694]: /data/robot_settings.json not found. Loading defaults
Apr 24 18:01:27 be088a opentrons-api[52694]: CAN connect: socketcan-can0-500000
Apr 24 18:01:27 be088a opentrons-api[52694]: Application startup complete.
Apr 24 18:01:27 be088a opentrons-api[52694]: Uvicorn running on unix socket /run/aiohttp.sock (Press CTRL+C to quit)
Apr 24 18:01:27 be088a opentrons-api[52694]: Using directory /var/lib/opentrons-robot-server for persistence.
Apr 24 18:01:27 be088a opentrons-api[52694]: Migrated database from schema 1 to version 1
Apr 24 18:01:27 be088a opentrons-api[52694]: Updating instrument model cache
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 32, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: loaded: gripperV1, gripper offset: GripperCalibrationOffset(offset=Point(x=0.0, y=0.0, z=0.0), source=<SourceType.default: 'default'>, status=CalibrationStatus(markedBad=False, source=None, markedAt=None), last_modified=None)
Apr 24 18:01:27 be088a opentrons-api[52694]: Calibrations for P50SV3420230114A02 on LEFT does not exist.
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 96, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: Error response: 503 - LegacyError -
Apr 24 18:01:27 be088a opentrons-api[52694]: loaded: p50_single_v3.4, pipette offset: (0.0, 0.0, 0.0)
Apr 24 18:01:27 be088a opentrons-api[52694]: Calibrations for P50MV3420230329A04 on RIGHT does not exist.
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 112, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: loaded: p50_multi_v3.4, pipette offset: (0.0, 0.0, 0.0)
Apr 24 18:01:27 be088a opentrons-api[52694]: The present devices are now {<NodeId.pipette_left: 96>, <NodeId.gripper: 32>, <NodeId.gantry_x: 48>, <NodeId.gantry_y: 64>, <NodeId.head: 80>, <NodeId.pipette_right: 112>, <USBTarget.rear_panel: -1>}
Apr 24 18:01:27 be088a opentrons-api[52694]: Checking for firmware updates
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 96, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 64, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 32, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 48, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 80, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 112, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for -1, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: No firmware updates required.
Apr 24 18:01:27 be088a opentrons-api[52694]: Updating instrument model cache
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 32, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: Calibrations for P50SV3420230114A02 on LEFT does not exist.
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 96, sha 79db2655 matches and not forced
Apr 24 18:01:27 be088a opentrons-api[52694]: Calibrations for P50MV3420230329A04 on RIGHT does not exist.
Apr 24 18:01:27 be088a opentrons-api[52694]: No update required for 112, sha 79db2655 matches and not forced
Apr 24 18:01:28 be088a opentrons-api[52694]: The present devices are now {<NodeId.gantry_y: 64>, <NodeId.gripper: 32>, <NodeId.gantry_x: 48>, <NodeId.head: 80>, <NodeId.pipette_left: 96>, <NodeId.pipette_right: 112>, <USBTarget.rear_panel: -1>}
Apr 24 18:01:28 be088a opentrons-api[52694]: Done with firmware updates
Apr 24 18:01:28 be088a opentrons-api[52694]: Setting gantry load to GantryLoad.LOW_THROUGHPUT
root@be088a:~# Apr 24 18:01:28 be088a opentrons-api[52694]: Updating the window switch status: open
Apr 24 18:01:28 be088a opentrons-api[52694]: Homing Z axes
Apr 24 18:01:28 be088a opentrons-api[52694]: Homing [<OT3Axis.Z_L: 2>, <OT3Axis.Z_R: 3>, <OT3Axis.Z_G: 4>]
Apr 24 18:01:28 be088a opentrons-api[52694]: Opentrons hardware API initialized
Apr 24 18:01:30 be088a opentrons-api[52694]: Malformed calibrations for P1KSV3420230114A03 on LEFT. Please factory reset your calibrations.
Apr 24 18:01:30 be088a opentrons-api[52694]: Malformed calibrations for P1KSV3420230114A02 on LEFT. Please factory reset your calibrations.
```

And here's the output of `journalctl -u opentrons-robot-server` for the same period:
```
Apr 24 18:01:01 be088a systemd[1]: Starting Opentrons Robot HTTP Server...
Apr 24 18:01:25 be088a python3[52694]: INFO:     Started server process [52694]
Apr 24 18:01:25 be088a python3[52694]: INFO:     Waiting for application startup
.
Apr 24 18:01:25 be088a python3[52694]: /data/robot_settings.json not found. Load
ing defaults
Apr 24 18:01:26 be088a python3[52694]: /data/robot_settings.json not found. Load
ing defaults
Apr 24 18:01:26 be088a opentrons-api[52694]: API server version: 0.4.0
Apr 24 18:01:26 be088a opentrons-api[52694]: Robot Name: FlexyMCFlexFace
Apr 24 18:01:27 be088a opentrons-api[52694]: /data/robot_settings.json not found
. Loading defaults
Apr 24 18:01:27 be088a opentrons-api[52694]: CAN connect: socketcan-can0-500000
Apr 24 18:01:27 be088a opentrons-api[52694]: Application startup complete.
Apr 24 18:01:27 be088a opentrons-api[52694]: Uvicorn running on unix socket /run/aiohttp.sock (Press CTRL+C to quit)
Apr 24 18:01:27 be088a opentrons-api[52694]: Using directory /var/lib/opentrons-robot-server for persistence.
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: BEGIN (implicit)
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: PRAGMA main.table_info("migration")
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: [raw sql] ()
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: PRAGMA main.table_info("protocol")
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: [raw sql] ()
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: PRAGMA main.table_info("analysis")
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: [raw sql] ()
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: PRAGMA main.table_info("run")
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: [raw sql] ()
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: PRAGMA main.table_info("action")
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: [raw sql] ()
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: COMMIT
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: BEGIN (implicit)
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: PRAGMA main.table_xinfo("run")
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: [raw sql] ()
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: SELECT migration.id, migration.created_at, migration.version
                                                                               FROM migration ORDER BY migration.version DESC
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: [generated in 0.00105s] ()
Apr 24 18:01:27 be088a opentrons-api[52694]: Migrated database from schema 1 to version 1
Apr 24 18:01:27 be088a /opt/opentrons-robot-server/uvicorn/__main__.py[52694]: COMMIT
(etc)
```

**Comment by sfoster1** [comment]
It will also get comms logs for can and so on injected in there, it's really the everything log

**Review by SyntaxColoring — APPROVED** [review]
Interesting, thanks. Let's try it! 🌳 

I think I need to learn more about the difference between journalctl units and syslog idents. I thought they always basically matched.

Our logging config is getting pretty complicated. It would be nice if we could find a way to enable the useful filtering with `journalctl` that you mention, without having to enumerate all these special cases in a logger dictconfig. For example, maybe we could find a way to automatically set the syslog ident to the Python package name (or would that be weird?). Or, maybe we can get `systemd.journal.JournalHandler` to stash that info in some custom [journal field](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html), if it isn't doing that already.

**Comment by sfoster1** [comment]
Yeah absolutely it's a back of mind thing. I think there's a journalctl field for like log source that could be the logger name.

**Pull request merged**
