### PR TITLE
chore(release): 6.2.1

### PR DESCRIPTION
**Pull request by SyntaxColoring**
# Overview

Merge the `hotfix_6.2.1` branch into the `release` branch.

# Plan

Following the instructions in `RELEASING.md`, after this PR is approved, I will fast-forward-merge it into the `release` branch. This will bring the commits that are already in the `hotfix_6.2.1` branch into the `release` branch, with no changes.

Afterwards, I will tag the last commit as `v6.2.1` to release it into production.

# Review requests

* Is the above plan correct?
* Look over the commit log to make sure there's nothing unexpected there.
* Is this PR properly named? My understanding is that it won't show up anywhere permanent, like a commit message, but still.

### CODE REVIEW

**Review by nusrat813 — APPROVED** [review]
LGTM

**Comment by SyntaxColoring** [comment]
Reminder to self not to click the GitHub "Squash and merge" button.

**Review by sfoster1 — APPROVED** [review]
This looks correct to me! The sequence of actions is also correct.

**Review by sanni-t — APPROVED** [review]
LGTM!

**Pull request merged**
