### PR TITLE
refactor(api): remove dead RPC API code

### PR DESCRIPTION
**Pull request by mcous**
## Overview

End of an era. PR is self-explanatory and cathartic.

## Changelog

- refactor(api): remove dead RPC API code

## Review requests

- [ ] Nothing strange happens to your local dev environment
- [ ] Smoke test `opentrons_execute` and `opentrons_simulate`

## Risk assessment

Low

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
YAAAAAYYYYY

**Review by sfoster1 — APPROVED** [review]
If you wanted to go farther I'm pretty sure this removes the need for the hardware manager in the protocol API, since the only reason we needed that was to reuse the same context object for calibration here

**Review by sfoster1 — COMMENTED** [review]
At the very least, `ProtocolContext.temp_connect`

**Comment by sfoster1** [comment]
Maybe the protocol context command caching and linking actually. unless you're using that broker object for something else

**Comment by mcous** [comment]
Just tried messing around with removing the `HardwareManager`, `temp_connect`, et. al., and it got pretty dicey. I'm gonna leave it to its own PR

**Pull request merged**
