### PR TITLE
test(labware-library): fix end to end tests after vite migration

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview

This PR fixes Labware Library e2e tests from the vite migration. I'll fix up PD e2e tests in a follow up.

Closes [AUTH-85](https://opentrons.atlassian.net/jira/software/c/projects/AUTH/issues/AUTH-85)

# Changelog

- Fix Labware Library e2e tests

# Review requests

Make sure LL e2e tests are passing

# Risk assessment

Low

[AUTH-85]: https://opentrons.atlassian.net/browse/AUTH-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by koji** [comment]
pd's e2e is failing.
https://github.com/Opentrons/opentrons/actions/runs/8236235001/job/22523320030?pr=14615#step:8:25

**Review by koji — APPROVED** [review]
The changes look good to me.
Thank you for fixing this!

**Review by jerader — APPROVED** [review]
nice, LL e2e tests look good

**Comment by shlokamin** [comment]
> pd's e2e is failing. https://github.com/Opentrons/opentrons/actions/runs/8236235001/job/22523320030?pr=14615#step:8:25

yep, will fix those in a follow up. i wanna merge this now to unblock LL deploys though

**Pull request merged**
