### PR TITLE
feat(ot3-gravimetric): ot3 gravimetric test project

### PR DESCRIPTION
**Pull request by amitlissack**
# Overview

An alternative to https://github.com/Opentrons/Mechanical-Test/pull/17

Opting for putting the ot3-gravimetric-test project into monorepo. Reasons:
- Scaffolding is there for pushing python package to ot3. 
- Development is better with editable `opentrons` and `robot-server` package dep.
- Easy integration with docker in monorepo
- This is where our python is!

# Changelog

- Add `hardware-testing` directory in monorepo
- add `ot3-gravimetric-test` project.

# Review requests

**Do not review code in this PR. The drivers are moved over as is from `Mechanical-Test`. I want them here in their raw and working form as a baseline. They'll be slightly refactored to match OT code style in the future.** 

Names.

# Risk assessment

None

### CODE REVIEW

**Review by sfoster1 — COMMENTED** [review]
I do like this being in here. I wonder though, and maybe this is bikeshedding, if the best place for this is under `hardware/`, or in fact as `opentrons_hardware.testing.gravimetric` or `opentrons_hardware.third_party` or something.

Pros are that I think it natively fits there, and it'll just be present on all the robots. Don't need a new project, don't need to worry about distribution...

Cons are that it's kind of annoying to get to I guess, long import chains.

**Comment by amitlissack** [comment]
> I do like this being in here. I wonder though, and maybe this is bikeshedding, if the best place for this is under `hardware/`, or in fact as `opentrons_hardware.testing.gravimetric` or `opentrons_hardware.third_party` or something.
> 
> Pros are that I think it natively fits there, and it'll just be present on all the robots. Don't need a new project, don't need to worry about distribution...
> 
> Cons are that it's kind of annoying to get to I guess, long import chains.

That was my first inclination which I suggested that in slack. You and @Laura-Danielle disagreed.

**Comment by Laura-Danielle** [comment]
> > I do like this being in here. I wonder though, and maybe this is bikeshedding, if the best place for this is under `hardware/`, or in fact as `opentrons_hardware.testing.gravimetric` or `opentrons_hardware.third_party` or something.
> > Pros are that I think it natively fits there, and it'll just be present on all the robots. Don't need a new project, don't need to worry about distribution...
> > Cons are that it's kind of annoying to get to I guess, long import chains.
> 
> That was my first inclination which I suggested that in slack. You and @Laura-Danielle disagreed.

I still prefer it to not be in `opentrons_hardware` because to me that implies that it's an opentrons-hardware project. I wonder, though, if it would make sense to call this new project just 'third party hardware' or something to that effect so that we could potentially put other drivers in here as well.

**Comment by Laura-Danielle** [comment]
> 

my preference would be for this to be:

`thirdparty-hardware/<name of scale we're using>/ot3-gravimetric-test` or something to that effect.

**Comment by amitlissack** [comment]
> 

While the drivers are what's in this project right now, that's not what it's really about. It's about having all the support code for the gravimetric test protocols on the robot. That means drivers, data storage, and protocol logic. 

`hardware-testing/ot3-gravimetric` makes sense for all that i listed. 

If we want to take the drivers and put them in a `third-party-drivers` project that can work too.

**Review by sfoster1 — APPROVED** [review]
Well heck let's do it then. Assume you don't want to add it to top-level make and ci yet because it wouldn't pass, right? Given that we'll do that as a followup, let's get it going.

**Pull request merged**
