### PR TITLE
fix(scripts): setuptools v71 removed the need for extern

### PR DESCRIPTION
**Pull request by ryanthecoder**
# Overview
Version 71.0.0 removed the setuptools.extern package and release on 07/18/2024

With this we no longer need to use `from setuptools.extern import packaging` and we can just `import packaging`
However depending on the version of 3.10 you may still have 70.3.0 and packaging < 24.0 so we need to navigate around the old and new.

# Test Plan

# Changelog

# Review requests

# Risk assessment

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
Great. If it works I'm all down with it.

**Comment by SyntaxColoring** [comment]
> With this we no longer need to use from setuptools.extern import packaging and we can just import packaging

FYI I do not think `packaging` is guaranteed to be present. If this works, we're probably relying on it being there because it's a subdependency of some other thing that happens to be installed.

For example, here's what a clean environment looks like:

```bash
$ python3 -m venv venv
$ source venv/bin/activate
$ pip freeze --all
pip==21.2.4
setuptools==58.0.4
$ pip install --upgrade setuptools
$ pip freeze --all
pip==21.2.4
setuptools==71.0.3
$ python -c 'import packaging'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'packaging'
```

I agree that we should merge this if it works.

**Comment by ryanthecoder** [comment]
setuptools >71.0.0 forces the requirement for packaging >=24
https://github.com/pypa/setuptools/blob/5b5dc40b17b9501a6d971fce3101bb033da8eff5/pyproject.toml#L106

**Comment by SyntaxColoring** [comment]
Only with the `[core]` extra. I don't really understand who is intended to install `[core]` or when—*maybe* it's guaranteed for us by Pipenv, but I think my example shows it's not the underlying default, at least.

**Pull request merged**
