### PR TITLE
fix(components): fix dropdownmenu expand direction

### PR DESCRIPTION
**Pull request by koji**
# Overview
update handlePositionCalculation to solve the issue.

close RQA-3771

## Review requests
medium

### CODE REVIEW

**Comment by alexjoel42** [comment]
Screenshot 2024-12-06 at 11 53 38 AM

**Comment by alexjoel42** [comment]
[After moving a labware, the labware's location stops being tracked between modules (1).json](https://github.com/user-attachments/files/18041229/After.moving.a.labware.the.labware.s.location.stops.being.tracked.between.modules.1.json)

Protocol I used

**Review by jerader — APPROVED** [review]
works well on my end. I smoke tested every PD usage of DropdownMenu and everything is looking good!

**Comment by jerader** [comment]
nice!

https://github.com/user-attachments/assets/ccc4f3e1-447e-46e9-bffa-39f9a894f653

**Pull request merged**
