### PR TITLE
refactor(api): re-add unsafe movement flagging to legacy instrument core simulator

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR fixes an unreleased regression caused in `edge` by #11632. We moved unsafe movement flagging for legacy protocols out of the public `InstrumentContext` and into the legacy instrument core.

I forgot to make this same change in the legacy instrument simulating core, which meant that invalid movements to / around modules stopped getting flagged by analysis.

Closes RCORE-552

## Test Plan

Since this problem is limited to protocol analysis, it can be tested on the dev server rather than actual hardware.

The below protocol should raise an error due to the Heater-Shaker latch being open:

```python
metadata = {
    'protocolName': 'Heater-shaker test protocol w/ blocking commands',
    'author': 'Opentrons <protocols@opentrons.com>',
    'apiLevel': '2.13'
}

def run(context):
	# Load Heater-shaker module
	hs_mod = context.load_module("heaterShakerModuleV1", "1")

	# Load adapter + labware on module. Available labware:
	# - opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat
	# - opentrons_96_pcr_plate_adapter_nest_wellplate_100ul_pcr_full_skirt
	# - opentrons_96_deepwell_adapter_nest_wellplate_2ml_deep
	# - opentrons_flat_plate_adapter_corning_384_wellplate_112ul_flat
	hs_plate = hs_mod.load_labware("opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat")

	# tiprack_300ul = [context.load_labware('opentrons_96_tiprack_300ul', 3)]
	# p20 = context.load_instrument('p300_single', 'right', tip_racks=tiprack_300ul)

	tiprack_10ul = [context.load_labware('opentrons_96_tiprack_10ul', 5)]
	p20 = context.load_instrument('p20_single_gen2', 'right', tip_racks=tiprack_10ul)

	reservoir = context.load_labware('agilent_1_reservoir_290ml', 4)

	hs_mod.open_labware_latch()
	hs_mod.set_and_wait_for_temperature(celsius=80)  # Waits until H/S is at 80C

	p20.pick_up_tip()
	p20.aspirate(10, reservoir['A1'])
	p20.dispense(10, hs_plate['A1'])
	p20.drop_tip()

	hs_mod.close_labware_latch()
	hs_mod.set_and_wait_for_shake_speed(rpm=500)	# Waits until H/S has reached 500rpm speed

	context.delay(minutes=1)

	hs_mod.deactivate_shaker()
	hs_mod.deactivate_heater()
```

## Changelog

- refactor(api): re-add unsafe movement flagging to legacy instrument core simulator

## Review requests

See test plan, no other special requests.

## Risk assessment

Low, bug fix to protocol analysis with PAPI <= v2.13

### CODE REVIEW

**Review by SyntaxColoring — COMMENTED** [review]
👍 My results in the test plan match yours.

Can we move this some place shared instead of duplicating the code across `core.simulator` and `core.protocol_api`, even if it's just a new file containing nothing but this function? I worry about the implementations drifting over time, for the same reasons it was easy to make the original mistake of adding this to one of the cores but not the other.

**Comment by mcous** [comment]
> Can we move this some place shared instead of duplicating the code across core.simulator and core.protocol_api, even if it's just a new file containing nothing but this function? I worry about the implementations drifting over time, for the same reasons it was easy to make the original mistake of adding this to one of the cores but not the other.

I can try, but I don't think it's worth the effort given that both these files will be effectively frozen in time for the PAPI 2.14 release, so the risk of drift is very low

**Review by SyntaxColoring — APPROVED** [review]
The duplication still worries me, but this works for me to fix the bug if you're confident that it it won't leave us vulnerable to subtle drift.

**Review by sanni-t — APPROVED** [review]
This makes sense!
This doesn't fully fix the thermocycler lid status issue pointed out by the science team in the slack thread but I believe that buggy behavior already existed in legacy API. The `flag_unsafe_move` function relies on simulated TC driver, which initializes with a `lid_status = OPEN`. Which means that the simulator is not able to catch movement errors before the first lid command is issued in the protocol. I don't know if we want to address it in a follow-up PR or let the legacy simulation be as is.

**Pull request merged**
