### PR TITLE
fix(app): fix navigate condition issue

### PR DESCRIPTION
**Pull request by koji**
# Overview
update the condition for setup tab

RQA-3009

There might be another issue since the codebase may not yet be fully compatible with react-router-dom v6 even we followed the migration guide.

https://github.com/user-attachments/assets/c20bccf3-87ec-4d98-a0f1-a2cbb12967b2

## Changelog
- modify the redirect's condition and modify the test
- remove unnecessary `useFeatureFlag` from test 

## Risk assessment
low

### CODE REVIEW

**Review by mjhuff — COMMENTED** [review]
I think this likely won't work well on runs that are current but haven't yet started, since those runs can be created on the ODD or another desktop app. In those circumstances, we probably want users to route to the Run Setup tab.

I think the check we want here is something along the lines of "if the run has not begun running". I think the `useRunHasStarted` hook works?

**Comment by koji** [comment]
> I think this likely won't work well on runs that are current but haven't yet started, since those runs can be created on the ODD or another desktop app. In those circumstances, we probably want users to route to the Run Setup tab.
> 
> I think the check we want here is something along the lines of "if the run has not begun running". I think the `useRunHasStarted` hook works?

@mjhuff thank you for your suggestion. I'll try that tomorrow.

**Review by mjhuff — APPROVED** [review]
Tested and this is working great! Thank you for fixing!

**Comment by koji** [comment]
> Tested and this is working great! Thank you for fixing!

thank you for your help!

**Pull request merged**
