### PR TITLE
fix(labware-library): fix various naming and display data for labware

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

Include heater shaker in display names of hs specific adapters. Include OT-2 in display names of
OT-2 tip racks.  Add images for flex tip racks and opentrons tough plate and flex 96 tip rack
adapter.

Closes [RLAB-110](https://opentrons.atlassian.net/browse/RLAB-110), Closes [RLAB-333](https://opentrons.atlassian.net/browse/RLAB-333), Closes [RLAB-360](https://opentrons.atlassian.net/browse/RLAB-360), Closes [RLAB-361](https://opentrons.atlassian.net/browse/RLAB-361)

# Review requests

# Risk assessment

[RLAB-110]: https://opentrons.atlassian.net/browse/RLAB-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RLAB-333]: https://opentrons.atlassian.net/browse/RLAB-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RLAB-360]: https://opentrons.atlassian.net/browse/RLAB-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RLAB-361]: https://opentrons.atlassian.net/browse/RLAB-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jerader — APPROVED** [review]
lgtm!

**Comment by skyewindsor** [comment]
Is there anything we can do to add detail to the top down SVG for some of the adapters? The blank rectangles might get visually confusing for users:
Screenshot 2023-10-19 at 2 58 18 PM

**Comment by b-cooper** [comment]
@skyewindsor That's a great callout. As far as the scope of this PR, that is the expected behavior.  The `LabwareRender` abstraction has served us well for a very long time with only a small amount of special casing (tip racks look a little different).  If we want to have higher fidelity 2d renderings for labware in general, we will need to think through a larger solution. It would be great to capture this feature request as a ticket in the RAUT backlog.

**Comment by ecormany** [comment]
Love it, especially that we'll be able to link to an Adapters filter view from docs.

**Comment by skyewindsor** [comment]
LGTM, i'll log a ticket in the sustaining backlog to cover a solution to my question above

**Pull request merged**
