### PR TITLE
refactor(api): remove unused and redundant labware loading code

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR does a code removal pass after the addition of labware loading for the PE-based PAPI core. It does two main things:

- Ensures anything that creates `Labware` PAPI objects lives in `opentrons.protocol_api`
- Cuts `opentrons.protocols.labware` down to _only_ caring about labware definitions

## Changelog

- Remove unused and redundant labware loading code

## Review requests

- [ ] Smoke tests of regular protocol running flows
- [ ] Smoke tests of calibration flows
  - Turns out these flows load PAPI labware objects in the robot-server
  - Awesome.

## Risk assessment

Should be pretty low, if CI is green and smoke tests pass

### CODE REVIEW

**Comment by mcous** [comment]
Current dependencies on/for this PR:
* edge
  * **PR #11423** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11423" target="_blank">Graphite</a> 
    * **PR #11430** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11430" target="_blank">Graphite</a> 
      * **PR #11432** <a href="https://app.graphite.dev/github/pr/Opentrons/opentrons/11432" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11432?utm_source=stack-comment).

**Review by sfoster1 — APPROVED** [review]
excellent

**Comment by mcous** [comment]
Smoke tested this branch against real hardware:

- [x] Deck calibration
- [x] Calibration check
- [x] Pipette offset
- [x] Tip length calibration
- [x] PAPIv2 protocol analysis + run w/ feature-flag off
- [x] PAPIv2 protocol analysis + run w/ feature-flag on
    - Found that fixed-trash loading not yet implemented and in the happy path
    - Will address in another PR

**Comment by mcous** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Opentrons/opentrons/11432?utm_source=stack-comment).


Job Reference: IgqrdFXk0AJpc1mZNhvM

**Pull request merged**
