### PR TITLE
fix(shared-data): remove deprecated 'ot3' tip rack defs 

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

In favor of the new flex tip rack definitions, remove the old ot3 definitions

BREAKING CHANGE: all usage of "opentrons_ot3_96_tiprack_*" labware loadnames should be replaced by
"opentrons_flex_96_tiprack_*"

### CODE REVIEW

**Review by SyntaxColoring — APPROVED** [review]
✂️

**Review by Laura-Danielle — DISMISSED** [review]
@b-cooper , to make this less of a headache we should keep a look-up table around for the old def names.

Happy to do this for you quickly if you're busy :)

**Comment by b-cooper** [comment]
@Laura-Danielle That would be great if you could add that in. Thank you!

**Review by vegano1 — APPROVED** [review]
Nice

**Review by TamarZanzouri — APPROVED** [review]
tested on an OT-3. old names and new names work as expected.

**Pull request merged**
