### PR TITLE
fix(opentrons-ai-client): fix ChatContainer layout issue

### PR DESCRIPTION
**Pull request by koji**
# Overview
fix ChatContainer layout issue.
update the ChatContainer layout.

### after
Screenshot 2024-05-14 at 3 43 26 PM

close AUTH-397

# Test Plan
1. `make -C opentrons-ai-client dev`
2. type something and send button
3. repeat step 2 a couple of times
Check all your messages are displayed correctly.

# Changelog

# Review requests

# Risk assessment
low

### CODE REVIEW

**Comment by Elyorcv** [comment]
@koji When I continue submit again and again, it does not create scroll bar. Instead, it gets long 
Screenshot 2024-05-14 at 10 34 44 PM

**Comment by koji** [comment]
> @koji When I continue submit again and again, it does not create scroll bar. Instead, it gets long Screenshot 2024-05-14 at 10 34 44 PM

Did you set any specific settings on your Mac like [this](https://opentrons.slack.com/archives/CSCLVUW3C/p1715608748517049?thread_ts=1715607449.608269&cid=CSCLVUW3C)?

I think the app always shows the scrollbar because of the side bar's height.

**Comment by Elyorcv** [comment]
need to choose `always`?
image

**Comment by Elyorcv** [comment]
> > @koji When I continue submit again and again, it does not create scroll bar. Instead, it gets long Screenshot 2024-05-14 at 10 34 44 PM
> 
> Did you set any specific settings on your Mac like [this](https://opentrons.slack.com/archives/CSCLVUW3C/p1715608748517049?thread_ts=1715607449.608269&cid=CSCLVUW3C)?
> 
> I think the app always shows the scrollbar because of the side bar's height.

I tried `default` and `always` versions, but the same effect

**Comment by koji** [comment]
> > > @koji When I continue submit again and again, it does not create scroll bar. Instead, it gets long Screenshot 2024-05-14 at 10 34 44 PM
> > 
> > 
> > Did you set any specific settings on your Mac like [this](https://opentrons.slack.com/archives/CSCLVUW3C/p1715608748517049?thread_ts=1715607449.608269&cid=CSCLVUW3C)?
> > I think the app always shows the scrollbar because of the side bar's height.
> 
> I tried `default` and `always` versions, but the same effect

hmm, I cannot reproduce the issue.
Are you using Chrome?

**Comment by Elyorcv** [comment]
> > > > @koji When I continue submit again and again, it does not create scroll bar. Instead, it gets long Screenshot 2024-05-14 at 10 34 44 PM
> > > 
> > > 
> > > Did you set any specific settings on your Mac like [this](https://opentrons.slack.com/archives/CSCLVUW3C/p1715608748517049?thread_ts=1715607449.608269&cid=CSCLVUW3C)?
> > > I think the app always shows the scrollbar because of the side bar's height.
> > 
> > 
> > I tried `default` and `always` versions, but the same effect
> 
> hmm, I cannot reproduce the issue. Are you using Chrome?

To be clear, there are two scrollbars: one is outside chat container which belong to chrome; another one is for the chat container itself. My problem is for the chat container. When you send many messages, it just extends without scrollbar.

**Review by y3rsh — APPROVED** [review]
Looked good in the demo branch.

**Pull request merged**
