### PR TITLE
fix(app): disable instrument card controls when run is active

### PR DESCRIPTION
**Pull request by smb2268**
# Overview

This PR fixes a few small bugs for release 7.0.1:
RQA-1380, RQA-1515, and RQA-1575
# Test Plan
1. Look at instrument card overflow menu when a run is active and see that the controls are disabled
2. Calibrate a module on ODD and see that the exit button is right aligned
3. After updating the robot, see the height of the update success screen is now accurate

# Changelog
1. Disable pipette and gripper card overflow menu items that launch wizard flows when a run is in progress
2. Right align exit button for module calibration success screen on ODD, use SmallButton if on device
3. Edit icon size and padding for the Robot Update success screen according to the figma designs

# Review requests
Ensure code looks sound

# Risk assessment
Low

### CODE REVIEW

**Review by mjhuff — COMMENTED** [review]
Successful update modal doesn't appear to be working as expected
Screenshot 2023-09-20 at 9 29 26 AM

**Review by mjhuff — COMMENTED** [review]
The exit button is a bit smaller than it should be

[IMG_5673.HEIC.zip](https://github.com/Opentrons/opentrons/files/12673743/IMG_5673.HEIC.zip)

**Comment by smb2268** [comment]
> Successful update modal doesn't appear to be working as expected

@mjhuff I addressed this and made a few other updates to this modal to bring each screen more in line with the Figma: 

Screen Shot 2023-09-21 at 11 56 13 AM
Screen Shot 2023-09-21 at 11 50 32 AM
Screen Shot 2023-09-21 at 11 50 15 AM

**Review by mjhuff — APPROVED** [review]
Code works and looks sound. Thanks for fixing this!

**Pull request merged**
