### PR TITLE
fix(api): cal check: use real trash labware

### PR DESCRIPTION
**Pull request by sfoster1**
This uses the actual labware definition for the trash and forces a move
to xy center critical point to drop tips in the correct location.

### CODE REVIEW

**Review by b-cooper — APPROVED** [review]
Tested on robot, works as expected. I like the `_info_for_mount` helper too

**Comment by Laura-Danielle** [comment]
Aren't some of these changes from https://github.com/Opentrons/opentrons/pull/5663/files? Did the rebase do something weird

**Comment by sfoster1** [comment]
> Aren't some of these changes from https://github.com/Opentrons/opentrons/pull/5663/files? Did the rebase do something weird

no, `_move` shows up in the diff because this pr moves (heh) it from `CalibrationCheckSession` to `CalibrationSession`, since it's now called directly by `_trash_tip`. There's also some changes to it to allow callers to override the critical point, since `_trash_tip` needs tto move to `CriticalPoint.XY_CENTER`.

**Review by Laura-Danielle — APPROVED** [review]
LGTM

**Pull request merged**
