### PR TITLE
feat(app): Add React Query Devtools

### PR DESCRIPTION
**Pull request by mjhuff**
# Overview

Adds React Query Devtools to the desktop app & ODD, hidden behind a FF.

Lazy loading is required to properly render the devtools on the physical ODD. Because it is its own UI element (and because they are accessible in prod builds), a dev feature flag is included.

Note that this requires `QueryClientProvider` context to function, which is why the tools are placed where they are in the app/ODD render tree. [See setup docs here.
](https://tanstack.com/query/v4/docs/framework/react/devtools)
### Desktop

https://github.com/user-attachments/assets/6a411196-d69b-4db7-aff2-d6381c3682ad

### ODD

https://github.com/user-attachments/assets/0d185dcb-28ff-48e4-a2ca-0cd22a84082b

## Test Plan and Hands on Testing
- See videos

## Review requests
- I created a new `tools` dir for this. Is this an ok place for devtools like this?

## Risk assessment
low

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
I'm surprised having this in `devDependencies` works when running a bundled app, I guess I need to adjust my mental model of how that works

**Review by koji — APPROVED** [review]
this is great!
thank you for adding this.
one quick question, when we open the dev tool via remove dev tools, does it show the same result as well as ODD?

**Comment by mjhuff** [comment]
> when we open the dev tool via remove dev tools, does it show the same result as well as ODD?

Yes, they appear to work the same!

**Comment by mjhuff** [comment]
@sfoster1 technically this won't be bundled in deployment environments that specifically exclude devDependencies (or installed with `npm i --production`). I don't think this is actually an issue given our CI workflows, but I'm happy to adjust this if this could be problematic for any reason.

**Pull request merged**
