### PR TITLE
refactor(robot-server): Robot server model refactor v4

### LINKED ISSUE #6849: refactor(robot-server): http - flatten payloads and remove unused attributes

### PR DESCRIPTION
**Pull request by amitlissack**
# Overview

Simplify http v2 models for version 4.

See https://github.com/Opentrons/opentrons/issues/6847 for details.

closes #6849 

# Changelog

- Remove `type` and `meta` fields. 
- Eliminate `attributes` level in responses and requests.
- Delete backwards compatibility for calibration check commands that do not have a namespace.

# Review requests

Please look at the integration tests to review the new schema. 

# Risk assessment

High. This introduces breaking changes in the API. Only v4 will support.

```
Affected endpoints:

1. GET /sessions
2. POST /sessions
3. GET /sessions/{session_id}
4. DELETE /sessions/{session_id}
5. POST /sessions/{sessionId}/commands/execute
6. GET /labware/calibrations
7. GET /labware/calibrations/{calibrationId}
8. DELETE /labware/calibrations/{calibrationId}
9. GET /protocols
10. POST /protocols
11. GET /protocols/{protocolId}
12. POST /protocols/{protocolId}
13. DELETE /protocols/{protocolId}
14. GET /calibration/pipette_offset
15. DELETE /calibration/pipette_offset
16. GET /calibration/tip_length
17. DELETE /calibration/tip_length
18. GET /system/time
19. PUT /system/time

```

### CODE REVIEW

**Review by sfoster1 — COMMENTED** [review]
Looks absolutely great!

**Review by mcous — COMMENTED** [review]
API side looking good

**Review by sanni-t — COMMENTED** [review]
LGTM! I'll add comments if I find anything as I refactor the app-side

**Review by sfoster1 — APPROVED** [review]
Code looks really good!

**Comment by sanni-t** [comment]
Tested the calibration (labware, pipette offset, tip length) and time endpoints on a robot. All requests returned expected response shape and calibrations completed without any errors. Someone from HMG should probably also verify that the calibrations' responses are actually correct.

**Pull request merged**
