### PR TITLE
feat(hardware-testing): grav script on ot3

### PR DESCRIPTION
**Pull request by andySigler**
# Overview

# Test Plan

# Changelog

# Review requests

# Risk assessment

### CODE REVIEW

**Review by sfoster1 — CHANGES_REQUESTED** [review]
We need to split this PR up into multiple and figure something out for the merges that are baked in and inflate the diff.

I think some of these changes are because it merged in edge a couple times and got some other PRs or something?

Let's have separate PRs for
- Changing blowout to take a volume
   -  We need to rework this one to store shaft diameter in configuration rather than code
- Changing the default motion parameters
- Adding the temperature and humidity function
- Changing the way homing works
- Whatever happened with the change to cache instruments
- Whatever's going on with fast home
- The pipette configuration changes

We also need to somehow separate out
- the tip overlap fix that was in a separate pr I think

**Comment by Laura-Danielle** [comment]
@sfoster1 tip overlap fix is in the release branch right now.

**Comment by Laura-Danielle** [comment]
@andySigler As discussed in our meeting earlier this week, I think I would prefer that any new functionality we want to support in the gravi test should live in a function _inside_ the script. I would consider the blow out by volume to also be new functionality and we shouldn't be making any changes to the hardware controller for this.

We can try to keep parity by making sure those functions 1. use most of the underlying mechanisms in the hardware controller and 2. by talking with each other.

As we bring up that functionality in software, we can slowly switch the gravi script to use the hardware controller/protocol api again.

**Comment by andySigler** [comment]
Yes sry wasn't expecting to get eyes on this right away, should have labelled as draft, am going to remove all non hardware-testing changes for all the reasons you guys said and will ping you, thanks for taking a look!

**Review by sfoster1 — APPROVED** [review]
Okay this all makes a lot of sense to me now! Thanks for doing the changes.

**Review by Laura-Danielle — APPROVED** [review]
This all looks fine to me.

**Pull request merged**
