### PR TITLE
refactor(app): wire up gripper attach/detach/recalibrate flows to protocol engine

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

Replace stubbed out robot commands within the gripper wizard flow logic with real calls to new run
commands to support calibration, attach, and detach.

Closes [RLAB-272](https://opentrons.atlassian.net/browse/RLAB-272)

# Review requests

- [ ] launch "attach" flow from the gripper card on the device detail page
- [ ] launch "recalibrate" flow from the gripper card on the device detail page 
- [ ] launch "detach" flow from the gripper card on the device detail page

# Risk assessment
low

[RLAB-272]: https://opentrons.atlassian.net/browse/RLAB-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ahiuchingau — COMMENTED** [review]
Not sure if the following is in the scope of this PR:

####  Gripper image shows a tiprack:
Screen Shot 2023-03-23 at 7 11 46 PM

### Screen doesn't update after calibration has begun
This screen stays like this until robot stops moving and ready for the next step. The button seems to be active the entire time as well (changes color when hovered). I'd expect the "Robot is in motion" screen to happen here.
Screen Shot 2023-03-23 at 6 50 27 PM


#### Weird behavior i found on English Breakfast:
Immediately after the front probe calibration, the robot homed (as expected) and went back to calibrate the front probe again. The screen is already showing the next step at this point. 

After it finishes the second time, it proceeded normally to the next step and let me remove and put the screen to the rear. And the rest of the flow ran normally and only once. 

I tried to reproduce the double front-probe calibration using the same instrument and robot, but to no avail, so maybe it was nothing?

**Comment by b-cooper** [comment]
@ahiuchingau Yeah that's correct, we don't have the thumbnail image of the gripper yet. As far as the loading state between steps, I have to rework that, I noticed the same thing. Depending on how involved that loading state refactor is, I may sneak it in after merging this. I haven't noticed the double front probe behavior yet, but good to keep an eye out for.

**Comment by sanni-t** [comment]
> Immediately after the front probe calibration, the robot homed (as expected) and went back to calibrate the front probe again. The screen is already showing the next step at this point.

@b-cooper is it possible that the 'Begin calibration' button was clicked twice by mistake which would probably queue up the same command twice? I'm just drawing conclusion from @ahiuchingau 's observation above this one that says the button is active while calibration is in progress.

**Comment by b-cooper** [comment]
@sanni-t  That is very possible. I just added back in a loading state that should prevent that double-click as a possibility

**Review by ahiuchingau — APPROVED** [review]
🦀🦀🦀

**Comment by sanni-t** [comment]
> @sanni-t That is very possible. I just added back in a loading state that should prevent that double-click as a possibility

Sweet!

**Review by sanni-t — APPROVED** [review]

**Pull request merged**
