### PR TITLE
refactor: Rename Pydantic v1 methods to their v2 counterparts

### PR DESCRIPTION
**Pull request by SyntaxColoring**
## Overview

Some trivial renames, for the Pydantic v1->v2 upgrade. Closes EXEC-1063.

## Test Plan and Hands on Testing

Just CI.

## Changelog

* Do a bunch of global find+replaces to rename Pydantic methods according to [their migration guide](https://docs.pydantic.dev/latest/migration/#changes-to-pydanticbasemodel).

* In every project that runs on a robot, try to configure pytest to fail a test if it detects that it raised a Pydantic deprecation warning. This is intended to prevent us from using the old method names, which are less type-safe.

  This appears to only work for some warnings, but it works for the warnings that I care about and understand, so I didn't look into it further.

## Review requests

None in particular.

## Risk assessment

Low.

## Merging

This is based atop PR #14871. It should merge into `edge` shortly after that PR.

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
This is so annoying, thank you!

**Review by vegano1 — APPROVED** [review]
lol not sure why they made these changes

**Review by jbleon95 — APPROVED** [review]
Annoying but straightforward. Thanks for also adding an error to pick up using the old methods, I'll definitely make that mistake at least once.

**Comment by SyntaxColoring** [comment]
> lol not sure why they made these changes

I think they were trying to namespace all of their stuff under `model_*` so they'd have room to expand without stepping on user code.

Amusingly, `model_*` was an unfortunate prefix for them to choose because users wanted to use it for their own machine learning stuff. So they later narrowed the namespace a bit in https://github.com/pydantic/pydantic/issues/10315.

**Pull request merged**
