### PR TITLE
chore(release): Merge changes from 5.0.0 into edge

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

Merge changes from 5.0.0 release into edge

### CODE REVIEW

**Comment by mcous** [comment]
Here's my pass at merge conflict fixes. Please 👍 this post if it looks good to you. GitHub isn't able to highlight everything super well, so look for `- `, ` -`, and `++` lines for conflict resolutions

```diff
diff --cc api/src/opentrons/protocol_api/module_contexts.py
index 4bc3b0ff5,31f75aaac..000000000
--- a/api/src/opentrons/protocol_api/module_contexts.py
+++ b/api/src/opentrons/protocol_api/module_contexts.py
diff --cc api/src/opentrons/protocol_engine/__init__.py
index 5a2181daf,ce76425f5..000000000
--- a/api/src/opentrons/protocol_engine/__init__.py
+++ b/api/src/opentrons/protocol_engine/__init__.py
@@@ -9,7 -9,7 +9,7 @@@ from .create_protocol_engine import cre
  from .protocol_engine import ProtocolEngine
  from .errors import ProtocolEngineError, ErrorOccurrence
  from .commands import Command, CommandParams, CommandCreate, CommandStatus, CommandType
- from .state import State, StateView, CommandSlice, EngineConfigs
 -from .state import State, StateView, CommandSlice, CurrentCommand
++from .state import State, StateView, CommandSlice, CurrentCommand, EngineConfigs
  from .plugins import AbstractPlugin
  
  from .types import (
diff --cc api/src/opentrons/protocol_runner/legacy_command_mapper.py
index c5e773dc4,e64163aff..000000000
--- a/api/src/opentrons/protocol_runner/legacy_command_mapper.py
+++ b/api/src/opentrons/protocol_runner/legacy_command_mapper.py
diff --cc api/src/opentrons/protocols/context/protocol.py
index b600606be,3ac11a0bf..000000000
--- a/api/src/opentrons/protocols/context/protocol.py
+++ b/api/src/opentrons/protocols/context/protocol.py
diff --cc api/src/opentrons/protocols/context/protocol_api/protocol_context.py
index 1a9090028,9e91d72b5..000000000
--- a/api/src/opentrons/protocols/context/protocol_api/protocol_context.py
+++ b/api/src/opentrons/protocols/context/protocol_api/protocol_context.py
@@@ -3,14 -3,19 +3,12 @@@ from typing import Dict, List, Optional
  from collections import OrderedDict
  
  from opentrons import types
- from opentrons.protocols.api_support.types import APIVersion
 -
 -from opentrons.hardware_control import ThreadManager, SynchronousAdapter
 +from opentrons.hardware_control import SyncHardwareAPI, SynchronousAdapter
  from opentrons.hardware_control.modules import AbstractModule, ModuleModel
  from opentrons.hardware_control.types import DoorState, PauseType
 -
  from opentrons.protocols.api_support.definitions import MAX_SUPPORTED_VERSION
- from opentrons.protocols.geometry.deck import Deck
- from opentrons.protocols.geometry import module_geometry
- from opentrons.protocols.geometry.deck_item import DeckItem
+ from opentrons.protocols.api_support.types import APIVersion
 -from opentrons.protocols.api_support.util import (
 -    AxisMaxSpeeds,
 -    HardwareToManage,
 -    HardwareManager,
 -)
 -
++from opentrons.protocols.api_support.util import AxisMaxSpeeds
  from opentrons.protocols.context.protocol_api.instrument_context import (
      InstrumentContextImplementation,
  )
@@@ -21,8 -26,15 +19,11 @@@ from opentrons.protocols.context.protoc
      InstrumentDict,
      LoadModuleResult,
  )
- from opentrons.protocols.api_support.util import AxisMaxSpeeds
 -
+ from opentrons.protocols.geometry import module_geometry
+ from opentrons.protocols.geometry.deck import Deck
+ from opentrons.protocols.geometry.deck_item import DeckItem
 -
  from opentrons.protocols.labware import load_from_definition, get_labware_definition
+ 
 -from opentrons.protocols.types import Protocol
 -
  from opentrons_shared_data.labware.dev_types import LabwareDefinition
  
  
diff --cc api/tests/opentrons/protocol_runner/test_legacy_context_plugin.py
index 0b2e88450,aea4ed499..000000000
--- a/api/tests/opentrons/protocol_runner/test_legacy_context_plugin.py
+++ b/api/tests/opentrons/protocol_runner/test_legacy_context_plugin.py
diff --cc app/src/assets/localization/en/protocol_info.json
index da7ae1f09,106dd9c5e..000000000
--- a/app/src/assets/localization/en/protocol_info.json
+++ b/app/src/assets/localization/en/protocol_info.json
@@@ -56,7 -53,6 +56,7 @@@
    "labware_positon_check_complete_toast_with_offsets": "Labware Position Check complete. {{count}} Labware Offset created.",
    "labware_positon_check_complete_toast_with_offsets_plural": "Labware Position Check complete. {{count}} Labware Offsets created.",
    "protocol_loading": "Opening Protocol On {{robot_name}}",
-   "protocol_finishing": "Closing Protocol On {{robot_name}}",
+   "protocol_finishing": "Finishing Protocol On {{robot_name}}",
 -  "cancel_run": "Cancel Run"
 +  "cancel_run": "Cancel Run",
 +  "valid_file_types": "Valid file types: Python files (.py), Protocol Designer files (.json), or .zip files"
  }
```

**Review by mcous — APPROVED** [review]
LGTM, but I'll wait for someone else to check my conflict resolution work before proceeding

**Comment by sanni-t** [comment]
> diff --cc api/src/opentrons/protocol_runner/legacy_command_mapper.py
index c5e773dc4,e64163aff..000000000
--- a/api/src/opentrons/protocol_runner/legacy_command_mapper.py
+++ b/api/src/opentrons/protocol_runner/legacy_command_mapper.py
diff --cc api/src/opentrons/protocols/context/protocol.py

There doesn't seem to be any conflict with `legacy_command_mapper.py` though

**Comment by mcous** [comment]
> > diff --cc api/src/opentrons/protocol_runner/legacy_command_mapper.py
> > index c5e773dc4,e64163aff..000000000
> > --- a/api/src/opentrons/protocol_runner/legacy_command_mapper.py
> > +++ b/api/src/opentrons/protocol_runner/legacy_command_mapper.py
> > diff --cc api/src/opentrons/protocols/context/protocol.py
> 
> There doesn't seem to be any conflict with `legacy_command_mapper.py` though

Yeah it's weird that it doesn't show up in GH. Definitely showed up when I tried to merge in locally, though. Resolved locally by keeping `edge`, so maybe that's why GH isn't showing it

**Pull request merged**
