### PR TITLE
style(app): App fix style attached pipette slideout

### LINKED ISSUE #10806: 6.0 Feedback: About pipette slideout -> Serial Number is too small
### Overview

image

### Current Behavior

``` html
<div class="Flex-sc-1qhp8l7-0 kGbeCT">
  <h6 data-testid="AboutPipetteSlideout_serial_number_text_P20SV222021040709" class="Text-sc-1wb1h0f-0 StyledText-sc-1knpqbk-0 GRqUe">Serial Number</h6>
  <h6 data-testid="AboutPipetteSlideout_serial_P20SV222021040709" class="Text-sc-1wb1h0f-0 StyledText-sc-1knpqbk-0 cxIxqz">P20SV222021040709</h6>
</div>
```

Computed is smaller than the `<h6>` though:

image

### Expected Behavior

Size is a bit more easy to read.

### Steps To Reproduce

_No response_

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This PR will fix #10806.
Figma https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx?node-id=1297:106103#213345421

Screen Shot 2022-06-21 at 7 22 57 PM

# Changelog
- Update the text styling

# Review requests
- `serial number` is upper case
- serial number's font is `p`

# Risk assessment
low

### CODE REVIEW

**Review by jerader — COMMENTED** [review]
I saw the slack thread regarding the discussion to increase the font size of the serial number. Makes sense to me. However, I think we should get Mel's approval on this before it is merged.

**Comment by koji** [comment]
> I saw the slack thread regarding the discussion to increase the font size of the serial number. Makes sense to me. However, I think we should get Mel's approval on this before it is merged.

Actually, the design is in Figma.
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx?node-id=1297:106103#213345421

**Review by vabruzzo — APPROVED** [review]
lgtm 👍

**Review by jerader — APPROVED** [review]
🚀

**Comment by mmencarelli** [comment]
- [x] (1) 'x' icon to be 24px wide
- [x] (2) missing "close" primary button


Screen Shot 2022-06-21 at 12 54 48 PM

**Comment by mmencarelli** [comment]
font size looks good though!

**Comment by koji** [comment]
@mmencarelli Could you check this PR?

**Pull request merged**
