### PR TITLE
feat(shared-data): add custom & default thermocycler overlap offsets for labware

### PR DESCRIPTION
**Pull request by sanni-t**
# Overview

Closes RSS-353

- Adds the `stackingOverlapWithModule` for Biorad & NEST PCR plates on TC Gen2.
- Also adds a default overlap for any labware placed on a thermocycler on the OT2 such that the final height of the labware is the same as what it would have been prior to introducing stacking overlaps for thermocycler labware.

# Test Plan

The ticket above has a protocol attached for testing. That protocol places a nest PCR plate, a biorad plate and a custom pcr plate on the thermocycler one ofter the other to check for location precision. You will need to create and upload a custom PCR plate definition as mentioned in the protocol.

1. Upload this protocol to a Flex and check that:
    - [ ] when you run LPC, the pipette moves to accurate z-positions for the NEST and Biorad plates, and moves too high for the custom pcr plate
    - [ ] during the protocol run the gripper is able to move the NEST & biorad plates correctly but can't move the custom pcr plate because the gripper moves too high

2. Adjust the protocol for running on OT2 and upload to an OT2:
    - [ ] when you run LPC, the pipette moves to accurate z-positions for the NEST and Biorad plates, and an okay position for custom pcr plate (unless it happens to be based on an armadillo plate). Also note that positional accuracy of the OT2 for labware on modules is not as high as the Flex so I wouldn't stress too much if there is an offset of a couple of mm.

# Changelog

- updated Biorad & NEST PCR plate definitions
- added backwards-compatible stacking overlap for OT2 based TC in `state.labware. get_module_overlap_offsets()`

# Review requests

- Do above tests on both Flex & OT-2
- Do we need to bump labware definition revision number for this?

# Risk assessment

Low. Just adds the missing overlap values. Low risk if tests show expected results.

### CODE REVIEW

**Comment by SyntaxColoring** [comment]
Measurements look good so far on an OT-2.
Screenshot 2023-09-22 at 3 08 39 PM

**Comment by sanni-t** [comment]
> Measurements look good so far on an OT-2. 

🙌 Thanks for the thorough testing! @SyntaxColoring

**Comment by jbleon95** [comment]
Measurements look good on the Flex
Screen Shot 2023-09-25 at 12 35 14 PM

**Review by SyntaxColoring — APPROVED** [review]
LGTM if CI passes—does this need updates to G-code tests?

**Comment by sanni-t** [comment]
> LGTM if CI passes—does this need updates to G-code tests?

Not sure. Checking now. Did we resolve the g-code test failure issues on the release branch?

The PD & Labware library tests are failing on all PRs because of some CI chrome version issue so going to ignore those failures.

**Comment by SyntaxColoring** [comment]
> Not sure. Checking now. Did we resolve the g-code test failure issues on the release branch?

Yes, as far as I know.

> The PD & Labware library tests are failing on all PRs because of some CI chrome version issue so going to ignore those failures.

👍 Yep. https://github.com/Opentrons/opentrons/pull/13705#pullrequestreview-1655643496

**Pull request merged**
