### PR TITLE
refactor(app): make use of generic calibration panels in deck calibration

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

Replace deck calibration flow child components with generic calibration panel components. update the
deck cal parent component and control component to manage loading states and chained actions with
new useDispatchApiRequests hook

# Changelog

- Replace all deck calibration child component "panels" with their shared calibration flow generic equivalent
- update the deck calibration flow parent component and control to use the new `useDispatchApiRequests` machinery that prevents race conditions between actions and avoids orphaned sessions.
- In order to totally ditch the css stylesheet, give a new `innerProps` prop to the aging `ModalPage` components library component

# Review requests

- Ensure new Deck Calibration flow still works as expected

# Risk assessment

relatively low, still all behind feature flag

### CODE REVIEW

**Review by sfoster1 — COMMENTED** [review]
What a diffstat!

**Review by sfoster1 — APPROVED** [review]
Code changes look good, love the diffstat. Haven't tested yet though.

**Review by sfoster1 — APPROVED** [review]
Tested on my robot, looks good

**Review by ahiuchingau — APPROVED** [review]
LGTM!

**Review by Laura-Danielle — APPROVED** [review]

**Pull request merged**
