### PR TITLE
refactor(app): update select a security type screen

### PR DESCRIPTION
**Pull request by koji**
# Overview
[design]
https://www.figma.com/file/AoTLAYuWawlaWItB1umOjr/Release%3A-Opentrons-Flex-Touchscreen-Designs?type=design&node-id=7147-91175&t=5GnnXgUB53osSDy6-0

https://www.figma.com/file/AoTLAYuWawlaWItB1umOjr/Release%3A-Opentrons-Flex-Touchscreen-Designs?type=design&node-id=8342-130075&t=21ngMyJAvbxPwTmv-0

update select a security type screen and related components and tests and add AlternativeSecurityTypeModal

# Test Plan
1. Tap `Settings`
2. Tap `ODD menu`
3. Tap `Network setup menu`
4. Tap `Wi-Fi`
5. Tap `Join other network`
6. Put any ssid name in the text field and tap `Continue`
The screen matches the design and when tapping a radio button the selected item is switched correctly.

# Changelog
- update SelectAuthenticationType component and test
- add AlternativeSecurityTypeModal and test

# Review requests

# Risk assessment
low

### CODE REVIEW

**Comment by ewagoner** [comment]
I clicked "None" while trying to connect to my network and the ODD froze. Is that in scope for this PR?

**Comment by koji** [comment]
> I clicked "None" while trying to connect to my network and the ODD froze. Is that in scope for this PR?

Does the network you tried to connect exist?
Also this pr is just updating the UI.

**Comment by ewagoner** [comment]
> Does the network you tried to connect exist? Also this pr is just updating the UI.

It does exist, but I'll just review the UI since functionality is out of scope.

**Comment by ewagoner** [comment]
Screenshot 2023-05-15 at 5 59 00 PM

The modal isn't centered on the screen.

**Comment by koji** [comment]
> Screenshot 2023-05-15 at 5 59 00 PM
> 
> The modal isn't centered on the screen.

i think current a modal is not centralized and that will be fixed later.

**Review by ewagoner — APPROVED** [review]

**Pull request merged**
