### PR TITLE
feat(app, shared-data): use new lower position for mounting plate attachment

### PR DESCRIPTION
**Pull request by smb2268**
# Overview
Utilize the new `maintenancePosition` that will move both mounts to the bottom of the gantry for unscrewing right mount and attaching/detaching the mounting plate

# Test Plan
Run through the 96-channel attach and detach flows and see that both mounts move to the bottom. The right mount shouldn't fall when unscrewed and you shouldn't have to hold it up to screw in the mounting plate

# Changelog
Add optional `maintenancePosition` param to `moveToMaintenancePosition` command type
Utilize this command in the 96-channel attach and detach flows

# Review requests
Test this out once Tamar's changes go in

# Risk assessment
Low

### CODE REVIEW

**Comment by TamarZanzouri** [comment]
Testing this with the both mounts PE change. after "unscrewing" the right z-axis carrige and pressing continue the right mount homes. Is this intended? 
Tested both left and right 1/8c. attach flow works fine. when trying to detach I am getting at error in the modal but not seeing anything in the netwrok tab or in the console.

**Comment by smb2268** [comment]
This has been tested for attach detach and calibrate for all pipettes and is working as expected!

**Comment by smb2268** [comment]
>Testing this with the both mounts PE change. after "unscrewing" the right z-axis carrige and pressing continue the right mount homes. Is this intended? 

This is expected! We home the right mount after the user confirms they have detached it from the motor.

**Review by b-cooper — APPROVED** [review]
🍽️

**Pull request merged**
