### PR TITLE
feat(shared-data): initial heater-shaker definition

### LINKED ISSUE #9496: heater-shaker: add heater-shaker geometry definition
## Overview

As a heater shaker operator, I would like my robot to be able to access labware that is loaded on top of a heater-shaker module. In order for the system to understand how to do this, it must have a geometry definition for the heater-shaker module.

## Acceptance criteria

- [ ] System has a V3 module definition for heater shaker
    - `shared-data/module/definitions/3/heaterShakerModuleV1.json`
- [ ] Definition specs `"moduleType": "heaterShakerModuleType"`
- [ ] Definition specs `"model": "heaterShakeModuleV1"`
- [ ] Definition specs geometry data
 
## Implementation notes

- We do not have to include front-end visualization data at this time; this will require a separate ticket
- It looks like existing `v3` module definitions spec an incorrect schema identifier; this is worth fixing

### PR DESCRIPTION
**Pull request by pmoegenburg**
This is an initial pass at the definition. Dimensions will need to be refined, with module deck slot clamps and plate latch factored in.

### CODE REVIEW

**Comment by sfoster1** [comment]
> This is an initial pass at the definition. Dimensions will need to be refined, with module deck slot clamps and plate latch factored in.

If I understand from offline discussions correctly, the key problem here is that the labware's _center_ is fixed relative to the module geometry, no matter the size of the labware(/labware-adapter pair). Our current definitions and geometry system are all built around assuming the labware's _bottom left corner_ is fixed relative to the module's geometry. For the heater/shaker, if labwares or labware-adapter combos are different sizes, their origins will be in different positions.

IMO we need a schema change here that allows modules to specify a `labwareCenterOffset`, which shall be a vector from the module slot interface origin to the center of the labware interface.

**Comment by pmoegenburg** [comment]
Correct. The deck slot clamps also need to be considered, which locate the module in the bottom right of the deck slot as opposed to the top left.

**Review by mcous — APPROVED** [review]
LGTM. We're adaptable to schema changes at this point, so happy to merge this in and continue to figure out schema changes necessary for correct center positioning

**Review by sfoster1 — APPROVED** [review]
if cpx is good with it, it looks good to me

**Pull request merged**
