### PR TITLE
fix(shared-data): swap X/Y spacing for 24-well nest tuberacks

### LINKED ISSUE #4238: opentrons_24_tuberack_nest_* definitions are wrong
# Overview

The `opentrons_24_tuberack_nest_1.5ml_screwcap` labware appears to have a problem with both its x-spacing and y-spacing.

The tip will correctly be positioned in A1. However, in D6, the position is noticeably off. Very sloppily measuring with calipers, I'd say the tip is 2 mm too close to the front of the robot and 3 mm too far to the left.

The same tube rack with different tubes, `opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap`, does *not* have this issue.

# Reproducing

This is an APIv2 demo script, but the issue applies equally to APIv1. I ran this without any labware calibration.

```python
from opentrons import protocol_api

metadata = {
    'protocolName': 'Tube rack offset test',
    'author': 'Max Marrone',
}

def run(protocol: protocol_api.ProtocolContext):
    tip_rack = protocol.load_labware('opentrons_96_tiprack_300ul', '1')
    tube_rack_1 = protocol.load_labware('opentrons_24_tuberack_nest_1.5ml_screwcap', '7') # Shows problem.
    tube_rack_2 = protocol.load_labware('opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap', '8') # Does not show problem.

    pipette = protocol.load_instrument('p300_single', 'left', tip_racks=[tip_rack])

    pipette.pick_up_tip()

    for tube_rack in [tube_rack_1, tube_rack_2]:
        pipette.move_to(tube_rack.well("A1").top())
        context.comment("Should be centered in A1.")
        context.pause()
        pipette.move_to(tube_rack.well("D6").top())
        context.comment("Should be centered in D6.")
        context.pause()
```

# Other notes

* I haven't tested to see if the height of the labware is correct.
* I haven't tested any of the other `opentrons_24_tuberack_*` labware.

### PR DESCRIPTION
**Pull request by ahiuchingau**
## overview
The X/Y spacing of the 24-well NEST tube racks are swapped, as pointed out by @SyntaxColoring.

This PR ~~bumps the version of the definitions to `2` and~~ resolves spacing issues in version 1. [@SyntaxColoring edit for posterity: this PR ended up editing the v1 definitions in-place without bumping them to v2.]

closes #4238

## changelog
- swap the x/y spacing
- update the y-offset value (from 10.08 to 10.07) to match other 24-well tube racks (see opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap)

## review
Test on robot to see that the grid spacing has been corrected

### CODE REVIEW

**Comment by mcous** [comment]
Marking this as a do not merge because of  #4217 (see #4179 for more details, which is blocked for the same reason)

**Comment by SyntaxColoring** [comment]
Unless we expect a quick turnaround on #4217, could we temporarily remove the broken NEST labware from the Labware Library?

- Protocols that are somehow currently using the labware successfully will still be able to, because we're not touching the definitions.
- New people won't fall into the hole.

**Comment by sfoster1** [comment]
#4266 supercedes this if we're going to do a hotfix

**Review by mcous — COMMENTED** [review]
**I have not tested these on a robot**, so merge should still be gated on someone doing that. I can confirm that spacing and offsets now match in the LL sandbox across all 24 tuberacks, so the data change looks correct

**Review by nusrat813 — APPROVED** [review]
Robot position is still off on the y axis 1-2 mm, x ~ 0.5 mm after CLI and tip probe 
Robot unable to hit center of deck slot 3 cross after CLI and tip probe, off ~1mm 
After labware calibration, no issues found

**Pull request merged**
