### PR TITLE
fix(app): scroll to top of screen whenever route is changed

### PR DESCRIPTION
**Pull request by smb2268**
fix RQA-3153, RQA-3139

# Overview
Currently when loading a scrollable page on the app, the scroll position from the previous page is maintained so we aren't always dropped on the top of a newly loaded page. It may be worth investigating a better approach down the line so that this automatic scroll doesn't make the scrollbar show up, but for now I've implemented a `scrollTo` the top of the screen at the top level of the app whenever the route changes.

## Test Plan and Hands on Testing
Move between scrollable screens (settings, and protocols and quick transfer if you have more than 5 loaded) and see that you are scrolled to the top of the newly rendered page 

https://github.com/user-attachments/assets/f90a091f-6d01-4805-b722-111b46461e97

## Changelog
Whenever the current path changes, scroll to the top of the ODD window

## Review requests
Let me know if you think there's a better way to do this! This is what I came up with after a day or so of playing around with scrolling.

## Risk assessment
Low

### CODE REVIEW

**Review by brenthagen — APPROVED** [review]
works as expected, no additional rerenders ✔️

**Review by mjhuff — COMMENTED** [review]
Is it possible to  `useMatch` on the QT route and just conditionally run this if the page is QT?

If we want this behavior generally, I guess we could blacklist routes...I'm just trying to think of a way to get the scrollbar not to appear when we go to something like `/setup`

**Comment by smb2268** [comment]
> Can you `useMatch` on the QT route and just conditionally run this if the page is QT?
> 
> If we want this behavior generally, I guess we could blacklist routes...I'm just trying to think of a way to get the scrollbar not to appear when we go to something like `/setup`

@mjhuff we're currently seeing this issue across all scrollable pages, so that includes /robot-settings, /protocols, and now /quick-transfers. I'm planning to make a follow up ticket to try to figure out why the scroll position isn't 0 after a route change even when you were scrolled to the top of the previous page but since I don't think this issue is new, design agreed that the scrollbar appearing temporarily is an okay interim fix. 

Is `/setup` scrollable? And without this change, do we always land on the top? I haven't seen the scrollbar appear on any routes that aren't scrollable, like `/instruments` or an empty `/protocols` state

**Comment by mjhuff** [comment]
> Is `/setup` scrollable? And without this change, do we always land on the top? I haven't seen the scrollbar appear on any routes that aren't scrollable, like `/instruments` or an empty `/protocols` state

Ah gotcha. No, `/setup` shouldn't be scrollable, but it looks like the scroll appears briefly in the video you linked. IDK if this is really a problem, though. We do always land on the top of that page, since it's not supposed to be scrollable.

Anyway, don't let my comments block you from merging!

**Pull request merged**
