### PR TITLE
refactor(app,api): Map legacy comment commands to modern Protocol Engine ones

### PR DESCRIPTION
**Pull request by SyntaxColoring**
# Overview

Formerly, Python `comment()`s were reported as legacy commands because Protocol Engine didn't have a `comment` command. With #11965, now it does, so we can fix that.

# Changelog

* When a Python protocol backed by Protocol Engine does `comment()`, generate a Protocol Engine `comment` command.
* When a Python protocol backed by the legacy backend does `comment()`, map it into a Protocol Engine `comment` command.

# Review requests

* Are there any versioning concerns with changing how the server reports comments in Python protocols?
* `LegacyCommandMapper`'s tests are split across two files. Did I put the new test in the correct one?
    * `tests/opentrons/protocol_runner/test_protocol_runner.py` has the usual unit test setup.
    * `tests/opentrons/protocol_runner/smoke_tests/test_legacy_command_mapper.py` is more end-to-end. It specifically has tests for PAPI commands that go through the legacy broker, which are usually prohibitively difficult to test in the usual unit test setup.
    * `protocol.comment()` is a little unusual because it uses the legacy PAPI message broker, but it *is* easy to construct its messages in a unit test setting. So, I can see it going either way.

# Risk assessment

Low. Changes are well-covered by tests.

### CODE REVIEW

**Comment by SyntaxColoring** [comment]
~~I need to think through the testing strategy here.~~

* ~~Some of the tests currently use legacy comments as arbitrary placeholder commands for testing things like nesting. Those can either be changed to use some other unknown legacy fallthrough command to maintain their current path through the production code, or they can be changed to use modern Protocol Engine comments. If they're changed to use modern Protocol Engine comments, we need a new test to cover legacy fallthrough behavior.~~
* ~~All of the other broker-passed commands are tested integration-style because most of those commands are too hard to set up in an isolated way. We can either put the comment testing there, for consistency, or put it in the unit tests, for isolation.~~
    * ~~Aside: those integration tests could use a check that `result != None`, to cover a mistake that's easy to make in `LegacyCommandMapper`.~~

**Review by mcous — DISMISSED** [review]
LGTM

**Comment by SyntaxColoring** [comment]
Re-drafting: Looks like I have some TypeScript type-checking errors to look into.

**Comment by SyntaxColoring** [comment]
Discussed with App+UI people in person:

The code in the run log that this touches currently uses TypeScript bindings to the v6 schema. This is sort of blocked behind us changing that to be the v7 schema, instead. (Because this new `comment` command would be added to v7 and not v6.)

I'm closing this for now to declutter the PR list because we have higher-priority things going on.

**Pull request closed without merging**
