### PR TITLE
refactor(app): add buttonCategory for border-radius

### PR DESCRIPTION
**Pull request by koji**
# Overview
update MediumButton to add buttonCategory for border-radius

the thread about this change
https://www.figma.com/file/AoTLAYuWawlaWItB1umOjr?node-id=7276:111948#444652108

# Test Plan

# Changelog
- add buttonCategory to MediumButton
- add a test for the above update
- update stories

# Review requests

# Risk assessment
low

### CODE REVIEW

**Review by jerader — APPROVED** [review]
lgtm! The 2 category types are the same for `SmallButton` so maybe you can export the type and use it for both `SmallButton` and `MediumButton`. Up to you though!

**Review by ewagoner — APPROVED** [review]

**Comment by koji** [comment]
> lgtm! The 2 category types are the same for `SmallButton` so maybe you can export the type and use it for both `SmallButton` and `MediumButton`. Up to you though!

yeah, that sounds good.
I updated that part.

**Comment by ewagoner** [comment]
> yeah, that sounds good. I updated that part.

Just a nit: I would have put the shared type in index.tsx and then imported it into the two buttons that use it.

**Comment by koji** [comment]
> > yeah, that sounds good. I updated that part.
> 
> Just a nit: I would have put the shared type in index.tsx and then imported it into the two buttons that use it.

I think basically we create `types.ts` for types that are used by multiple components but for this we just need only one type.

**Pull request merged**
