### PR TITLE
chore(api): remove unused code

### PR DESCRIPTION
**Pull request by amitlissack**
# Overview

Removing unused code in the drivers package.

# Changelog

- removed `get_serial_ports_list` and `Connection` from `opentrons.drivers`. These are not used anywhere.

# Review requests

Am I wrong that these are unused?

# Risk assessment

Almost none.

### CODE REVIEW

**Comment by SyntaxColoring** [comment]
They're not used for hardware testing, are they?

**Comment by amitlissack** [comment]
> They're not used for hardware testing, are they?

I don't believe so. I think they use the smoothie driver directly. Whom should I ask?

**Review by SyntaxColoring — COMMENTED** [review]
This PR makes sense to me.

It's unclear to me whether this code is in use for hardware testing, though. I think someone from HMG who's more familiar with our responsibilities there needs to give final approval.

**Review by SyntaxColoring — COMMENTED** [review]
[Edit: Oops, accidental duplicate review.]

**Review by sfoster1 — CHANGES_REQUESTED** [review]
We should definitely remove `Connection` now that it's not used - I'm confident in that - but I need to run `get_serial_ports_list` by some people.

**Review by sfoster1 — APPROVED** [review]
Cleared it up, all good!

**Pull request merged**
