### PR TITLE
refactor: Delete the opentrons repository

### PR DESCRIPTION
**Pull request by SyntaxColoring**
# Overview

This PR deletes everything in this repository.

Closes all tickets except for #8085.

# Changelog.

* Delete everything.

# Review requests

Please test this on a real OT-2. Use `make push` to push it and make sure nothing works.

# Risk analysis.

Medium.

This touches a lot of code. However, the new code is well-covered by unit tests.

### CODE REVIEW

**Comment by y3rsh** [comment]
CI looks clean.  I may want to start answering all the recruiters in my linkedIn.  I'm not sure what to work on after this merges.  Maybe we can get [The Button](https://github.com/Opentrons/opentrons/issues/8085) to send tweets or start my roomba or something.

# 😊  🤣

**Comment by mcous** [comment]
Finally hit 100% code coverage

**Comment by sanni-t** [comment]
Please resolve merge conflicts 🤪

**Comment by DerekMaggio** [comment]
Can't break if there is nothing there

**Comment by SyntaxColoring** [comment]
Closing without merging.

After further investigation, I've determined that even after deleting this repository, other repositories full of code still exist in the world. Will return to this once I figure out how to delete all of those, too.

**Pull request closed without merging**
