### PR TITLE
feat(shared-data): add heater-shaker labware w/ adapter definitions

### LINKED ISSUE #9443: heater-shaker: add adapter+labware definitions
# Overview

Heater shaker is set to have these officially supported labware + adapters:

1. 96 Well, Deep Well, 2mL, Square well, V bottom, Full skirt (NEST 503501) + Deep Well Adapter
2. 96 Well, 0.2mL, Round well, Flat bottom, Full skirt (NEST 701011) + Flat Bottom Adapter
3. 96 Well, 0.1mL, Round well, V bottom, Full skirt (NEST 402501) + PCR Adapter
4. Universal Adapter (a generic flat plate that will heat up, compatible with generic labware - it's the default adapter)

Add the labware definitions for the top 3 combinations in shared-data. Universal adapter usage will be dealt with in a separate ticket.

# Implementation details

- Get dimension measurements and build the combo labware using custom labware creator. [More info on labware here](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3192422432/H+S+Labware+Adapter+info)

### PR DESCRIPTION
**Pull request by sanni-t**
Closes #9443 

# Overview

Adds definitions for labware+adapters from [this doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3192422432/H+S+Labware+Adapter+info)

# Changelog

Added:
- `opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat`
- `opentrons_96_pcr_plate_adapter_nest_wellplate_100ul_pcr_full_skirt`
- `opentrons_96_deepwell_adapter_nest_wellplate_2ml_deep`
- `opentrons_flat_plate_adapter_corning_384_wellplate_112ul_flat`

# Review requests

- Are the names fine?
- Are the shapes of the definitions fine? I have based them on existing aluminum block+labware definitions.
- ~Had to add a new category `heaterShakerAdapter` since these adapters aren't the same structurally as the aluminum blocks used for tempdecks (see drawings in the doc above). Is that okay? Or would that require schema update & version bump? (Looks like it would..)~ Reverted to using `aluminumBlock` since it is only used for UI purposes to indicate presence of a 2-part labware.
- The measurements for all three combos should be the same as the labware in each combination, except for measurements along the z-axis. If anyone has time to verify those values it'd be helpful.
- OR, if someone has access to these adapters+labware, try loading them in a run and see if a well-calibrated pipette goes to the correct locations when performing any `moveTo` or well-access commands.

# Risk assessment

Low. Doesn't affect anything existing.

### CODE REVIEW

**Review by TamarZanzouri — APPROVED** [review]
Calculated z for all files. It matches the details in the Confluences - v1 schema definition depth. checked calculations for random wells (checked distance for X and Y axis). Looks good to me! The file names do not match the Confluence proposed combo name but this could just be updated. I am approving this but would love to wait for a hardware approval.

**Review by mcous — COMMENTED** [review]
Definitions look good! Do we need to add these to a block-list anywhere to prevent them from showing up in the Labware Library / App v5.1 prematurely?

CC @shlokamin @b-cooper

**Comment by shlokamin** [comment]
> Do we need to add these to a block-list anywhere to prevent them from showing up in the Labware Library / App v5.1 prematurely?

We'll want them to go out for the next LL release anyways so I think we're fine

**Comment by sanni-t** [comment]
Had a quick chat with @shlokamin @anthonywilleee and @SyntaxColoring and decided that it is preferable to merge the definitions first and then test because that will allow the testing team to get the latest PD changes from edge as we work towards getting everything working, and will also unblock labware library & any client work to gate the use of these labware. It is also safe to merge since we don't anticipate anyone using these definitions.

**Pull request merged**
