### PR TITLE
feat(api): Include self-resolution guidance for multichannel transfer error #6140

### PR DESCRIPTION
**Pull request by Benedict-Carling**
# Overview
Hello!
This pull request addresses the open issue #6140 
To provide a more detailed error message in the case described in the Issue.
And to offer a likely solution inside the error message 🚀

# Changelog
Adds three lines of constant text description below the error message to explain more.
The text chosen in taken directly from the issue page.
The formatting uses single line strings inside a list to handle the multiline string

# Review requests
Please review it will be grately appreciated 👋
>Possible undesirable formatting

# Risk assessment
Low Risk

### CODE REVIEW

**Review by sfoster1 — COMMENTED** [review]
Thanks for the pull! I think this may not quite be the right place for the change though - it's in a section that's only executed if the API version _is_ 2.2 or higher, and should trigger in the case that a multichannel transfer was requested using row 3 or subsequent. Do you have a minimal reproducing example protocol for the issue?

**Comment by Benedict-Carling** [comment]
Thanks for letting me @sfoster1 know i'll double check next time, I don't have a minimal reproducing example protocol I was just making an accompanying PR for the issue, thanks for getting back quickly! 👋 Ben

**Comment by sfoster1** [comment]
No problem! I think in fact that issue was opened in error - looks like #5085 is the underlying issue.

**Comment by sfoster1** [comment]
@Benedict-Carling Not sure what's going on with the commit log in this PR at this point - I think merging edge in has really confused github. Would you mind rebasing the commits onto the branch?

**Comment by Benedict-Carling** [comment]
Closed, for git commit errors

**Pull request closed without merging**
