### PR TITLE
fix(app): remove nav focus state on app load

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
This will remove the focus state in the nav on app load. According to the following issue in the w3c css working group, the `focus-visible` state on page load is expected behavior: https://github.com/w3c/csswg-drafts/issues/5885 (i think, this discussion is not always easy to follow)
This is because on page load the app is programmatically moving focus to this element via react router and for accessibility reasons if focus is moved programmatically when no prior element is focused (such as on page load) the focus-visible selector is active. At least that's how I understand the discussion there.

We can keep the focus-visible on load, or implement some solution such as I've done here, which is to remove the focus-visible from the currently active item. A better fix would be to prevent react router from focusing on the nav element but i havent found a way to do that yet.

# Changelog
- removes focus-visible from active nav item

# Review requests
Check that on app load nav item is not in focus-visible state

# Risk assessment
Low

### CODE REVIEW

**Review by jerader — COMMENTED** [review]
Does this also remove the ability to focus on the current `Navbar` selection? (`Protocols` doesn't have a `focus-visible` state now)

https://user-images.githubusercontent.com/66035149/178276899-1f5fc826-546e-461c-a4fd-b5d29ac78829.mov

**Comment by vabruzzo** [comment]
> Does this also remove the ability to focus on the current `Navbar` selection? (`Protocols` doesn't have a `focus-visible` state now)
> 
>  Screen.Recording.2022-07-11.at.9.36.31.AM.mov

yeah it does unfortunately. i havent been able to come up with an actual fix.

**Comment by vabruzzo** [comment]
> > Does this also remove the ability to focus on the current `Navbar` selection? (`Protocols` doesn't have a `focus-visible` state now)
> > Screen.Recording.2022-07-11.at.9.36.31.AM.mov
> 
> yeah it does unfortunately. i havent been able to come up with an actual fix.

Correction, it doesnt remove the ability to focus on the current item, it removes the focus state when one does focus on the current item. this might be an acceptable tradeoff since there really isnt much of a reason to click on the currently active tab

**Review by b-cooper — APPROVED** [review]
This is an acceptable compromise for now. Thanks for investigating!

**Pull request merged**
