### PR TITLE
chore(build): Do not pass -i to ssh when there is no identity file

### PR DESCRIPTION
**Pull request by SyntaxColoring**
# Overview

This fixes these warnings when running `make push`:

```
Warning: Identity file  not accessible: No such file or directory.
```

These warnings happen when we're not using any SSH identity file, such as when we're pushing to OT-3s. We're passing `-i ""` but we should just not pass `-i` at all.

Parts of `scripts/push.mk` already account for this, but it looks like we missed a few spots.

# Test Plan

I've tested this by doing a top-level `make push-ot3 host=foo` to an OT-3.

# Review requests

I'm copy-pasting the `$(if ...)` expression from elsewhere in this file. Is there a good way to do this with less duplication?

Is the quoting correct, or at least good enough?

# Risk assessment

No risk to production code, but I'm sure a lot of Opentrons people will be very annoyed if this breaks.

### CODE REVIEW

**Review by sfoster1 — APPROVED** [review]
Looks good. You can make a new subfunction for this like
```
define idfile
   $(if $(1),"-i $(1)")
endef
```
and then use it like
```
scp $(idfile $(2))
```

**Comment by SyntaxColoring** [comment]
> You can make a new subfunction for this like...

I might have been doing it wrong, but I couldn't get this to work. Doing `$(idfile $(2))` from within `push-python-package` and friends keeps evaluating to the empty string.

**Comment by sfoster1** [comment]
> > You can make a new subfunction for this like...
> 
> I might have been doing it wrong, but I couldn't get this to work. Doing `$(idfile $(2))` from within `push-python-package` and friends keeps evaluating to the empty string.

Oh yeah sorry it would be `scp $(call id-file-arg,$(2))` - you have to use the [call function](https://www.gnu.org/software/make/manual/html_node/Call-Function.html) to do the argument-substitution

**Comment by SyntaxColoring** [comment]
> Oh yeah sorry it would be `scp $(call id-file-arg,$(2))` - you have to use the [call function](https://www.gnu.org/software/make/manual/html_node/Call-Function.html) to do the argument-substitution

Aha, that did the trick. Thanks!

**Comment by SyntaxColoring** [comment]
Tested on an OT-2 with a top-level `make push` and on an OT-3 with a top-level `make push-ot3`.

**Pull request merged**
