### PR TITLE
feat(app): confirm pick up tip button style

### LINKED ISSUE #8961: Confirm tip pick up primary CTA style
# Overview

 The buttons on the "Did the pipette pick up the tip successfully" modal within Labware Position Check are currently both secondary buttons.  The main "Confirm ..." CTA should be a primary button instead of a secondary button.

### PR DESCRIPTION
**Pull request by jerader**
closes #8961

# Overview

This PR fixes the CTA button styling when you confirm tip pick up in LPC

# Changelog

- changes some button stylings mentioned in the ticket

# Review requests

- I tested on my robot - in addition to fixing the styling, I also changed the colors of the buttons to be blue (as shown in figma). Please review to make sure everything looks ok.

Screen Shot 2021-12-02 at 13 57 54

# Risk assessment

low, behind ff

### CODE REVIEW

**Review by b-cooper — CHANGES_REQUESTED** [review]
Comparing this to the designs, it looks like we shouldn't be using the legacy `AlertModal` component here at all. It's `buttons` prop is old and inflexible (it only renders legacy `OutlineButton`s).  It also renders the warning icon with a grey titlebar, which isn't a part of the design.  Would you mind replacing this with a `BaseModal` instance and pass the `PrimaryBtn` and `SecondaryBtn` as children?

**Comment by jerader** [comment]
> Comparing this to the designs, it looks like we shouldn't be using the legacy `AlertModal` component here at all. It's `buttons` prop is old and inflexible (it only renders legacy `OutlineButton`s). It also renders the warning icon with a grey titlebar, which isn't a part of the design. Would you mind replacing this with a `BaseModal` instance and pass the `PrimaryBtn` and `SecondaryBtn` as children?

@b-cooper oh yeah, good call. I made the change. It should be good now but I'm not able to test how it looks in the LPC flow since i'm not by a robot.

**Comment by sakibh** [comment]
@b-cooper I just tested this out and it looks good. However, it looks like using `Modal` looks better stylistically, more responsive, and resembles the Figma design compared to `BasedModal`.

`BaseModal`:
Screen Shot 2021-12-06 at 3 56 51 PM

`Modal`:
Screen Shot 2021-12-06 at 4 04 06 PM

**Comment by sakibh** [comment]
Ended up using the `BaseModal` component since the `Modal` component is also legacy. Passed in `borderRadius` and `overlayColor` props and now it looks good.

Screen Shot 2021-12-07 at 2 23 19 PM

**Review by b-cooper — APPROVED** [review]
🎟️

**Pull request merged**
