### PR TITLE
fix(app): fix buttons disabled conditions when estop is not disengaged

### PR DESCRIPTION
**Pull request by koji**
# Overview
Add a new hook to check estop status to control buttons' disabled on Desktop app.
This might go into `edge`.

~~Currently the target is `7.1.0` release branch but this fix was moved to 7.2.0 so the target will be switched to `edge` one `7.1.0` is merged into `edge`. Probably I will need to solve conflicts since this PR changes a lot of tests.~~
https://opentrons.slack.com/archives/C05R5390YR3/p1702938902854579

All buttons are disabled (got confirmation from Mike and Rob)
Restart robot, RobotSettings in RobotOverflowmenu , and the toggle button in Privacy tab are enabled when an e-stop button is pressed.

close RQA-2110

related thread
https://opentrons.slack.com/archives/C05R5390YR3/p1702669338799859?thread_ts=1702586313.100579&cid=C05R5390YR3

# Test Plan
### Flex
1. Go to Device Details page
2. Press the robot's e-stop button

### OT-2
The above disabled buttons are not disabled.

# Changelog

# Review requests

# Risk assessment

### CODE REVIEW

**Comment by koji** [comment]
- [x] define the range for `useIsEstopNotDisengaged` -> all buttons are disabled (got confirmation from Mike and Rob)
- [x] use `useIsEstopNotDisengaged` for buttons

**Comment by koji** [comment]
- [x] check this branch with OT-2
- [x] fix tests

**Comment by koji** [comment]
- [x] fix tests

**Review by brenthagen — APPROVED** [review]
everything disables as intended when the e-stop is pressed, but we should also consider disabling:
1) the pipette card overflow menu
2) various items on the protocol run page when there is a current run - start run, cancel run, setup calibrations, etc

for protocol run setup, something similar to the run started "setup is view only" message might be helpful

**Comment by koji** [comment]
- [x] pipette card overflow menu button
- [x] gripper card overflow menu button
- [x] pipette card (remove calibrate link button)
- [x] gripper card (remove calibrate link button)
- [x] align the width of banners (pipette card and gripper card)
- [x] module card (remove calibrate link button)

**Pull request merged**
