### PR TITLE
fix(hardware): handle timeout finding pipettes

### PR DESCRIPTION
**Pull request by sfoster1**
Without doing this, starting the robot server without pipettes attached
won't work.

### CODE REVIEW

**Review by Laura-Danielle — APPROVED** [review]
cool

**Review by Laura-Danielle — CHANGES_REQUESTED** [review]
There is already a `not_present` test. Should we remove this test and/or modify the functionality a bit? Also, where do we plan to use the `ToolDetector` class and shouldn't we bias towards using this class instead? Once we've detected instruments are attached, then we could query for the instrument information.

Deciding on when to use the two classes definitely doesn't need to be addressed in this PR, but the test should.

**Comment by sfoster1** [comment]
> There is already a `not_present` test. Should we remove this test and/or modify the functionality a bit? Also, where do we plan to use the `ToolDetector` class and shouldn't we bias towards using this class instead? Once we've detected instruments are attached, then we could query for the instrument information.
> 
> Deciding on when to use the two classes definitely doesn't need to be addressed in this PR, but the test should.

The class really can only be used once we have fully reactive tool presence detection, I think. Until then it's the one-shot.

As for the tests, I think the change that needs to be made there is just the test name - this test checks "hey if it look like there's something there but there's not let's not crash". I can call it like `test_handles_no_instrument_info_response` or something

**Review by Laura-Danielle — APPROVED** [review]
lgtm

**Pull request merged**
