### PR TITLE
feat(app,app-shell): add config and routing for app on device

### PR DESCRIPTION
**Pull request by brenthagen**
# Overview

this is initial work to add a config boolean indicating that the app is running on a device screen, i.e. OT-3. routing is updated to omit the devices landing page and change the 'Devices' link in the nav bar to 'Device'

the dev app can be launched in "on device" mode with: `make -C app dev OT_APP_IS_ON_DEVICE=1`

TODO: breadcrumb refactor

# Changelog

 - Adds app isOnDevice config boolean

# Review requests

# Risk assessment

low

### CODE REVIEW

**Review by koji — APPROVED** [review]
Looks good to me.
Maybe we can modify app-shell/src/ui.ts to align with the app to on-device ui(optionl).
Ex, window size `1024x600`, `frame` option.

In terms of `frame` option, adding it later would be better since we can not move the app window on our laptop easily.

**Review by sfoster1 — CHANGES_REQUESTED** [review]
image (3)

If you run this with nothing in your discovery cache for `localhost` the device page whitescreens. We should probably have some basic error message or something here

**Comment by brenthagen** [comment]
> If you run this with nothing in your discovery cache for `localhost` the device page whitescreens. We should probably have some basic error message or something here

@sfoster1 as requested, here is an ascii otie error screen:

Screen Shot 2022-08-10 at 11 23 47 AM

**Review by sfoster1 — APPROVED** [review]
Nice, fixes my issue!

**Pull request merged**
