### PR TITLE
fix(app, protocol-designer): align left_right mount text

### PR DESCRIPTION
**Pull request by koji**
# Overview
change text from `Left+Right` -> `Left + Right`

[thread](https://opentrons.slack.com/archives/C07E9T2NAQK/p1730919881442329)

## Risk assessment
should be low

### CODE REVIEW

**Review by ecormany — APPROVED** [review]
Looks good assuming the tests all pass.

**Review by mjhuff — APPROVED** [review]
lgtm!

I unfortunately can't open the slack thread, so sorry if I'm missing context. @ecormany , in some spots for labware in the TC location, we show "Slot A1+B1". Should this be reformatted as well?

**Comment by koji** [comment]
> lgtm!
> 
> I unfortunately can't open the slack thread, so sorry if I'm missing context. @ecormany , in some spots for labware in the TC location, we show "Slot A1+B1". Should this be reformatted as well?

actually, that is a good point.

@mjhuff oops sorry about the link issue.
The question: should we align Left+Right and Left + Right? PD uses both of them right now.

Ed's answer
>in the monorepo (excluding tests) there are 8 with spaces, 5 without. let’s include the spaces.


@ecormany `A1+B1` should be `A1 + B1`?

**Comment by ecormany** [comment]
Hmm. It's a little inconsistent, but I would say to leave the slot copy as is. Unless, @mjhuff can you think of an example where both of these appear on a single screen?

**Comment by mjhuff** [comment]
> Hmm. It's a little inconsistent, but I would say to leave the slot copy as is. Unless, @mjhuff can you think of an example where both of these appear on a single screen?

No, I don't think there are any shared screens!

**Comment by koji** [comment]
@ecormany @mjhuff 

`A1+B1` is hard coded in shared-data and PD. 
app uses the term from shared-data.

For app,
LabwareListItem 
SetupModuleList
LabwareStackModal
SetupFixtureList
SetupModulesList
MoveLabwareInterventionContent
ProtocolSetupLabware
FixtureTable
ModuleTable
Hardware in ProtocolDetails (ODD)

For PD, the component is the current production code so it will be removed eventually.

`A1 + B1` is also hard coded in LocationConflictModal.

From the components, maybe `Deck Hardware` screen?

I think the possibility would be very low so I will merge this into edge.

**Pull request merged**
