### PR TITLE
fix(labware-library): correct typo

### PR DESCRIPTION
**Pull request by koji**
# Overview
Correct typo (labware-library/src/components/website-navigation/nav-data.js)   
https://github.com/Opentrons/opentrons/blob/edge/labware-library/src/components/website-navigation/nav-data.js#L188

# Changelog

# Review requests
This PR only needs to confirm the spelling is correct.
`recieved` --> `received`

# Risk assessment

### CODE REVIEW

**Review by shlokamin — APPROVED** [review]
Good catch, thank you @koji!

**Review by mcous — APPROVED** [review]
🎈

**Review by IanLondon — APPROVED** [review]
@koji thank you for this, good catch! We just finished a major refactor of Labware Library from Flow to TS so there's a merge conflict here. Sorry about that. Would you want to resolve the conflict?

**Comment by koji** [comment]
@IanLondon Nice!
Yeah sure, I will resolve the conflict.

**Comment by koji** [comment]
@IanLondon
merged Opentrons/opentrons edge into this branch.
Now the modified file is `.ts`.

**Pull request merged**
