### PR TITLE
feat(labware-designer): add prototype react-based sandbox-style live labware editor

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

This prototype grew out of pairing and conversations with @StevenPlonk , @sakibh , @ncdiehl11 , and @ramifarawi !

Create a basic graphical interface  (via `labware-designer` dev server) to the two internal labware creation methods, `createRegularLabware` and `createIrregularLabware`.

It has small affordances to:
- switch between 'regular' and 'irregular' labware creation
- change the slot that the labware renders to
- choose to render labware onto deck, or standalone

Also, migrated source to TypeScript.

Here's what it looks like:

https://user-images.githubusercontent.com/4731953/123345423-0129fd00-d524-11eb-826b-11fd5cb4666c.mov

### Good Next UX Steps

- Instead of "silently" logging errors to the console, it would be great if errors were surfaced in the UI. Perhaps using a component like the `AlertItem` from `@opentrons/components`.
- It'd be great to have the output definition validated against the schema.

# Changelog

- add React root to project
- build out basic `CreateLabwareSandbox` component
- migrate source to typescript
- update readme
- add basic unit test for expected component functionality

# Review requests

- Give it a try and see if it's easy enough to use
- think about what would make it better
- call out anything that looks fishy in the code

# Risk assessment

low, this is an only internal utility for now

### CODE REVIEW

**Review by StevenPlonk — APPROVED** [review]

**Review by StevenPlonk — APPROVED** [review]

**Review by shlokamin — APPROVED** [review]
Very cool! Nice work @b-cooper. Seems like this will be a powerful tool for apps eng. Now that this is here they can also take it further and add more functionality if they want which is awesome

**Review by sakibh — APPROVED** [review]
Extremely helpful tool and thank you so much for the prototype @b-cooper! I tested out various definitions including regular, very irregular, and also tip racks. They are all displaying properly and outputting the right JSON definition. I did notice one thing, the "Input" text box only accepts JSON. All my definitions were made using JS Objects (so the keys are not in quotations) because this is what the labware-designer README suggested. This is not an issue at all as converting it is very simple. Just wondering if this was by design. Thank you again and I'm looking forward to using this regularly.

**Review by ramifarawi — APPROVED** [review]
thanks so much @b-cooper !!!! This tool is awesome. I just have one note: would it be possible to render the well names on the labware as it does in PD? This can be especially helpful to double check column strides/row strides in the tool. This can be especially useful with really irregular labware, and knowing which wells are which when writing code. This isn't a huge deal as I can take the outputted .json file and check in PD. Anyways, thanks again!

**Comment by b-cooper** [comment]
@sakibh Copying a raw JS object into the console to interact with the `createIrregularLabware` function directly doesn't necessarily translate well to a form. Forms in general like to deal with `strings` and there are many utilities available within JS for parsing and manipulating JSON objects. It's possible to make the input take a JS Object instead of a JSON object though there is a bit of extra leg work necessary to have the indentation etc. that makes it more readable. If it is more convenient to manipulate the input object as a JS object than a JSON object, that would be a neat little feature you could implement as a follow up within this tool.

@ramifarawi I've added in the well labels, there is a prop on the `LabwareRender` component called `showLabels` that controls whether or not the labels render.  Feel free to play around with the other props that `RobotWorkspace` and `LabwareRender` get in this file `labware-designer/src/organisms/CreateLabwareSandbox/index.tsx`

**Pull request merged**
