### PR TITLE
fix(app): show InfoScreen under RunPreview for a run canceled before start

### PR DESCRIPTION
**Pull request by ncdiehl11**
Closes RQA-2717

# Overview

Show a 'Run was never started' InfoScreen under RunPreview for a terminal run that was never started (has 0 commands)

# Test Plan

- Begin protocol setup
- Cancel run before starting
- Verify that 'Run was never started' info screen shows
Screenshot 2024-05-14 at 11 52 24 AM

# Changelog

- show appropriate info screen if no commands exist on the run (consistent with parameters tab)
- fallback to analysis commands while commands from `runs/{runId}/commandsAsPreSerializedList` are loading so we don't get weird json as a step

# Review requests

auth js

# Risk assessment

low

### CODE REVIEW

**Review by koji — APPROVED** [review]
The changes look good to me.
Thank you for fixing this issue!

**Review by shlokamin — APPROVED** [review]
code looks good to me!

**Comment by ncdiehl11** [comment]
@shlokamin @koji I just pushed a commit to better address fallback logic. There was an issue that after a run is made terminal, we read from the _run_ commands rather than analysis commands, but for a moment, those run commands are `null`. Rather than fall back to analysis commands during the null reading, I think we should fallback to "Loading data..." as we do at protocol setup for consistency and reduced confusion.

https://github.com/Opentrons/opentrons/assets/47604184/727046ed-8c0f-4ef8-818e-e59c13be00fb

**Review by koji — APPROVED** [review]
lgtm!

**Review by sfoster1 — APPROVED** [review]
Approving the logic stuff - it's gross and we should look at it later, but good for now.

**Comment by ncdiehl11** [comment]
updated behavior. TODO: fix the run canceled banner flickering. unrelated to this component.
https://github.com/Opentrons/opentrons/assets/47604184/6f6050da-1545-44b3-aff7-4860791bbce5

**Pull request merged**
