### PR TITLE
fix(app): fix temperature module wait for temp text

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

The wait for target temperature command for the temperature module improperly interpolates a temperature value, despite the fact that only the target temperature previously set will be awaited

Closes RQA-749

### CODE REVIEW

**Review by sanni-t — COMMENTED** [review]
Ah! Forgot to mention one minor detail though. Some protocols (mainly PD protocols) can still specify a different, non-target temperature for the temp module using `await_temperature`, so the app will need to show that temperature if it's present in the command's parameters.

This is less of a concern using TC or H/S because we don't have `await_temperature` API for those. I forget if PD allows the TC or H/S to set a custom temperature to wait for.

**Comment by sanni-t** [comment]
Just checked, there's no way to specify custom wait for temp for TC in engine, but H/S waitForTemp can take a temperature param so maybe we should selectively show the custom temperature vs 'target temperature' text for both temp module & H/S

**Review by jerader — APPROVED** [review]
lgtm

**Review by sanni-t — APPROVED** [review]
Thanks for making the changes! The run preview text now correctly displays the specified temperature to wait for or 'target temperature' when no temperature is specified.

**Pull request merged**
