### PR TITLE
fix(app-shell-odd): make sd-notify actually work

### PR DESCRIPTION
**Pull request by sfoster1**
This is a fixup of https://github.com/Opentrons/opentrons/pull/12266 ( ab851712e14502800abac6d968a4dccda9223ee7 ) and more detail can be found there.

This fixes the issue I should have remembered that we really can't use node extensions because they don't get cross-compiled correctly, so now we just shell out to the command-line executable. Requires some different flags (specifically https://github.com/Opentrons/oe-core/pull/63/files#diff-ec32fa0cac503403c1384b437fe44635c404ad5616d1711595f5c4c5b82073b8R14 ) but works fine once you do that.

As with #12266 , we can merge this whenever we want, but shouldn't merge https://github.com/Opentrons/oe-core/pull/63 until this PR is merged.

### CODE REVIEW

**Review by Laura-Danielle — APPROVED** [review]
This should also be reviewed by a JS person, but lgtm from what I can tell.

**Comment by koji** [comment]
@sfoster1 One quick question on this PR.
In #12266 has yarn.lock in changes (because added the sd-notify), but this PR doesn't include the yarn.lock.
Do you know why this happens?

**Comment by sfoster1** [comment]
> @sfoster1 One quick question on this PR. In #12266 has yarn.lock in changes (because added the sd-notify), but this PR doesn't include the yarn.lock. Do you know why this happens?

I probably didn't rerun whatever changes yarn.lock, I'll do that - good catch!

**Comment by sfoster1** [comment]
Should be fixed up @koji !

**Review by koji — APPROVED** [review]
The changes look good to me!

**Pull request merged**
