### PR TITLE
refactor(app): remove splash screen

### PR DESCRIPTION
**Pull request by koji**
# Overview
remove splash screen since we don't need this any more.

# Test Plan
none

# Changelog
- remove the related components

# Review requests

# Risk assessment
low

### CODE REVIEW

**Review by brenthagen — COMMENTED** [review]
with the initial splash removed, we need either a route or a redirect to match `/`. like in the desktop app, we could add a `Redirect` from `/` to whatever page we want to show on load (`/dashboard`? `/get-started`?). another option would be to change one of those routes to `/`.

**Comment by koji** [comment]
> with the initial splash removed, we need either a route or a redirect to match `/`. like in the desktop app, we could add a `Redirect` from `/` to whatever page we want to show on load (`/dashboard`? `/get-started`?). another option would be to change one of those routes to `/`.

I guess `/dashboard` would be reasonable since it has links to protocols, instruments and robot settings？

@shlokamin 👆
What do you think?

**Comment by koji** [comment]
- [x] update the redirect path

**Review by brenthagen — APPROVED** [review]
🌊

**Pull request merged**
