### PR TITLE
test(hardware): replace pytest-aiohttp with pytest-asyncio 

### PR DESCRIPTION
**Pull request by amitlissack**
# Overview

Just like #10012 and #9981 we should replace pytest-aiohttp with pytest-asyncio. It's faster.

# Changelog

- replace pytest-aiohttp with pytest-asyncio 
- remove loop fixture usage
- lint

# Review requests

- Tested locally included integration tests using sim_sock_can

# Risk assessment

None

### CODE REVIEW

**Review by SyntaxColoring — APPROVED** [review]
Code changes make sense to me, and running `make -C hardware test` works. 🧪 I'm not sure how `make test-with-emulator` works, so I couldn't verify that.

**Comment by amitlissack** [comment]
> Code changes make sense to me, and running `make -C hardware test` works. 🧪 I'm not sure how `make test-with-emulator` works, so I couldn't verify that.

I verified `make test-with-emulator`.  It requires either ot3 docker emulation or locally running firmware and virtual CAN network,

**Review by Laura-Danielle — APPROVED** [review]

**Review by sotaoverride — APPROVED** [review]

**Comment by SyntaxColoring** [comment]
Looks like there's a hanging test:

```
Wed, 20 Apr 2022 13:41:21 GMT  tests/opentrons/hardware_control/test_poller.py ......                   [ 33%]
Wed, 20 Apr 2022 14:02:36 GMT  Error: The operation was canceled.
```

😬

**Comment by amitlissack** [comment]
> Looks like there's a hanging test:
> 
> ```
> Wed, 20 Apr 2022 13:41:21 GMT  tests/opentrons/hardware_control/test_poller.py ......                   [ 33%]
> Wed, 20 Apr 2022 14:02:36 GMT  Error: The operation was canceled.
> ```
> 
> 😬

I am merging this PR, because the hanging test issue is in `api` not `hardware`.

**Pull request merged**
