### PR TITLE
fix(app): App fix design feedback navbar

### LINKED ISSUE #10203: 6.0 Feedback [Design QA]:  Global Component, navbar, #10147
### Overview

This issue references the overarching 'Global Components' ticket, #10147

---

### Current Behavior

n/a

### Expected Behavior

Screen Shot 2022-05-03 at 3 19 37 PM

- [x] Add dark-grey/hover (#24313F) to the library
- [x] Add dark-grey/selected (#24313F) to the library
- [x] Update the .Navbar__NavbarLink :hover to the dark-grey/hover
- [x] Update the .Navbar__NavbarLink :selected to the dark-grey/selected 
- [x] Update the icon color (#e3e3e3)

### Steps To Reproduce

n/a

### Operating system

_No response_

### Robot setup or anything else?

n/a

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10203 and #10147

`Protocols`: hover
`Devices`:  selected
Screen Shot 2022-05-24 at 6 44 41 PM

# Changelog
- Add `#24313F` as `darkGreyHover`
- Change hover and selected color to `darkGreyHover`
- Change the icon color to `#e3e3e3` from `white`

# Review requests
- The color matches the design feedback

# Risk assessment
low

### CODE REVIEW

**Review by jerader — APPROVED** [review]
lgtm!

**Review by b-cooper — APPROVED** [review]
🖌️

**Comment by mmencarelli** [comment]
My b, Koji, I gave you the wrong hex code for the selected! 

Could you update our darkGreySelected to #39495B.

**Comment by koji** [comment]
> #39495B
@mmencarelli 
We have `export const darkBlackSelected = '#39495B'` so I switch back the selected color to that one.

Could you check it out?

**Comment by mmencarelli** [comment]
perfect!

**Pull request merged**
