### PR TITLE
fix(api): Speed up LLD by reducing the post-success raise.

### PR DESCRIPTION
**Pull request by ryanthecoder**
# Overview

Right now if we successfully detect liquid we raise (slowly) the entire max pass distance. this takes a while, especially on the 96 channel since it's calculated off the max plunger speed. 
This reduces the post-success raise to the "safe plunger prep" distance which we know is a safe distance from the liquid to prevent unwanted capillary action or adhesion to the outside of the tip.

### CODE REVIEW

**Review by sfoster1 — CHANGES_REQUESTED** [review]
I don't think we should do this because if the probe failed to trigger for whatever reason this would make the situation much worse by doing an uncommanded aspiration.

Can we instead speed up the retract so it's not super slow?

**Comment by ryanthecoder** [comment]
This doesn't move the plunger it just moves the Z up. And this move only happens when there is a successful detection

**Comment by sfoster1** [comment]
> This doesn't move the plunger it just moves the Z up. And this move only happens when there is a successful detection

right, but presumably the next thing that happens is a plunger prep, since otherwise we wouldn't have to do it at all, right? and a successful detection doesn't necessarily mean it was a successful detection right at the meniscus. I know we tested the hell out of this, but if we're designing for robustness here then we can avoid unforeseen problems.

**Comment by ryanthecoder** [comment]
The next move is actually another Z move to the top of the well + the safe plunger distance, before the plunger prep, so the observed behavior is that it taps the liquid, raises way out of the well, moves back to the top of the well and then does plunger prep

**Review by sfoster1 — APPROVED** [review]
Okay, this looks good then. But why do this move at all? Just to be slower to avoid external droplets?

**Comment by ryanthecoder** [comment]
> Okay, this looks good then. But why do this move at all? Just to be slower to avoid external droplets?

Yea we saw extra external droplets if we stay touching the meniscus too long, and ethanol has a nasty habit of starting to capillary action up into the tip very quickly after the plunger stops dispensing.

**Pull request merged**
