### PR TITLE
style(app): app_fixed_spacing_for_calibration_modals

### PR DESCRIPTION
**Pull request by aptrons22**
# Overview

Corrected branch issue, removed code from DirectionControl.tsx and refactored the spacing calibration modals code to reside in the JogControls component instead.

#10677

 

# Changelog
Refactored the following files to include marginBottom spacing set to marginBottom={SPACING.spacing5}
- MeasureNozzle.tsx
- MeasureTip.tsx
- SaveXYPoint.tsx
- SaveZPoint.tsx
- TipPickUp.tsx

# Review requests
Low

# Risk assessment
Low

### CODE REVIEW

**Review by jerader — CHANGES_REQUESTED** [review]
The changes look good, the only thing is now that you are merging into `release_6.0.0`, you should see the `marginBottom={SPACING.spacing5}` reflected in `JogControls`. After you remove that, this PR should be good to go 🚀

**Review by jerader — APPROVED** [review]
This looks good to me! 🚀 We may want design approval from Mel when she gets back next week before merging though.

**Review by vabruzzo — APPROVED** [review]
looks good 👍

**Review by b-cooper — APPROVED** [review]
This fix looks good.  When Mel is back in town, we'll also want to get her approval on the visuals.

**Review by koji — COMMENTED** [review]
The changes look good to me.
You are not replacing any old `SPACING_`s. Is there any specific reason?

**Pull request merged**
