### PR TITLE
ci(workflows): cancel in progress workflows on new trigger

### PR DESCRIPTION
**Pull request by y3rsh**
# Overview

```gherkin
Given I push, make a PR, or merge a PR
When a workflow "on" condition is matched
Then the workflow will queue to run
But already running workflows from the same trigger, that may now be redundant, continue running
```

> I make a PR but immediately see a typo so I fix it and push.  All the triggered workflows from my PR creation keep running but don't need to, I only want the workflows running against my new commit to run.  

image

[GitHub Workflow Concurrency Documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)

# Review requests

## Questions

- Are there exceptions to this where we don't want to cancel previously running workflows?
  - On a merge to `edge`, if a subsequent merge to edge happens before the workflows to build finish, they will be cancelled.  This results in states of the edge branch with no built assets.  Do we want to make an exceptions for `edge`?
  - Scenarios with the `release*` branches where this may have side effects?
  - Side effects from re-running a workflow?
- Other considerations?
-  Instead of doing this in all workflows, pick a couple to prove the concurrency group is restrictive enough?

# Risk assessment

Medium, this needs 👀 as it is hard to map all the workflows and triggers conceptually to understand any side effects.

### CODE REVIEW

**Review by sfoster1 — CHANGES_REQUESTED** [review]
I like these changes for devs but we should definitely not apply them to tag builds and probably edge builds. i think we _should_ apply them to release-branch builds because the "oh god i made a typo" thing is extremely common in, for instance, release-branch bump commits.

**Comment by y3rsh** [comment]
> I like these changes for devs but we should definitely not apply them to tag builds and probably edge builds. i think we _should_ apply them to release-branch builds because the "oh god i made a typo" thing is extremely common in, for instance, release-branch bump commits.

Makes sense.  I have added expressions to detect when the branch name is `edge` and for any push of a tag.  When these are detected, the `github.run_id` is added to the concurrency group string.  [The only time a `github.run_id` would stay the same between runs is on a re-run](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).  If you somehow started 2 re-runs one after another (which doesn't seem possible) a cancellation on an edge or tag triggered workflow run might happen.

I proved the expressions out in this [repo](https://github.com/y3rsh/action_time/actions)

**Comment by SyntaxColoring** [comment]
> I like these changes for devs but we should definitely not apply them to tag builds

Just curious: why don't we want to auto-cancel tag builds?

**Comment by sfoster1** [comment]
> > I like these changes for devs but we should definitely not apply them to tag builds
> 
> Just curious: why don't we want to auto-cancel tag builds?

Everything about nonstandard or surprising aspects of release management should be manual, in my opinion. It's fine and a good idea to automate happy paths, but anything that gets weird really needs human oversight.

**Review by sfoster1 — APPROVED** [review]
Looks good to me!

**Pull request merged**
