### PR TITLE
feat(app, labware-library): add adapter and adapter + labware combo imgs

### PR DESCRIPTION
**Pull request by jerader**
closes [RUXD-1109](https://opentrons.atlassian.net/browse/RUXD-1109)

# Overview

This adds images to the adapters in app + labware-library except for the tiprack adapter which is only compatible for the 96-channel which isn't supported until 7.1. (follow up ticket for tiprack adapter: https://opentrons.atlassian.net/browse/RAUT-765)

Additionally, this adds the images to the adapter + labware combos as well. While users wont' be using these definitions anymore, they can still have the definitions in older protocols.

# Test Plan

Check in the app that the adapters's images look good. Check in labware-library as well! (`make -C labware-library dev`)

# Changelog

- add images to both app and labware library
- add to the labware images record in both app and labware library

# Review requests

see test plan

# Risk assessment

low

[RUXD-1109]: https://opentrons.atlassian.net/browse/RUXD-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jbleon95** [comment]
We probably want to also add an image for the `opentrons_96_well_aluminum_block` temperature module adapter as well

**Comment by jerader** [comment]
> We probably want to also add an image for the `opentrons_96_well_aluminum_block` temperature module adapter as well

@jbleon95, that image is already in the repo as `opentrons_96_aluminumblock_side_view.jpg`

**Comment by koji** [comment]
reduced the images' size a little bit.
[images.zip](https://github.com/Opentrons/opentrons/files/12766447/images.zip)

one quick question about images
One is .png and the others are .jpg. Don't we need to unify the image format? (.png no background, jpg white background)

**Comment by jerader** [comment]
> reduced the images' size a little bit. [images.zip](https://github.com/Opentrons/opentrons/files/12766447/images.zip)
> 

@koji  Thanks! I will update these images.

> one quick question about images One is .png and the others are .jpg. Don't we need to unify the image format? (.png no background, jpg white background)

No idea if we have a standardized format, I've seen both. I was lazy and just used the png for the one since it was already a png when i downloaded it 😅

**Review by koji — APPROVED** [review]
The changes make sense to me.

**Comment by sanni-t** [comment]
🙌🏎️

**Pull request merged**
