### PR TITLE
fix(labware-library): make labware creator accessible via external links

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview
This PR adds an HTML resource for labware creator that will get served when hitting labware.opentrons.com/create. all this HTML file does is route users to the correct hash route that gets picked up by react router.

This is necessary because we have external links that users use to access labware creator directly without going through the top level of labware library. 

It also replaces labware library's browser router with a hash router so that requests to `/create` do not get sent to the server, since labware creator is served client side via react router. 

Fixes https://opentrons.atlassian.net/browse/RESC-339

## Test Plan and Hands on Testing

- Go to http://sandbox.labware.opentrons.com/ll_update-build-base and make sure the page loads correctly (CSS will be messed up, this will be fixed by https://github.com/Opentrons/opentrons/pull/16502
- Navigate to LC (if you scroll to the bottom of the page theres a button that should be clickable), make sure the page loads
- In a new browser window, hit http://sandbox.labware.opentrons.com/ll_update-build-base/create directly (without going through the root of LL). Make sure the page loads correctly

## Changelog

- Add top level resource for Labware Creator so it can be accessed via external links

## Review requests

See test plan above

## Risk assessment

Medium, but also fixes a bug

### CODE REVIEW

**Comment by alexjoel42** [comment]
# Good news, the main issue is fixed after reviewing testing 

- LC loads through the bottom page LL
- The web page is accessible by just pasting http://sandbox.labware.opentrons.com/ll_update-build-base 
- I also tested it using ` make -C labware-library serve ` which worked 



## Please ignore, this is fixed in the CSS udpate
Screenshot 2024-10-17 at 11 30 26 AM 



## Complicated news, the font is different. This might be the CSS change

# New 

Screenshot 2024-10-17 at 11 29 23 AM



# Old 
Screenshot 2024-10-17 at 11 29 45 AM

**Comment by shlokamin** [comment]
@alexjoel42 yep the CSS issues (which include font differences) are to be expected until koji's PR merges

**Comment by koji** [comment]
> # Good news, the main issue is fixed after reviewing testing
> * LC loads through the bottom page LL
> * The web page is accessible by just pasting http://sandbox.labware.opentrons.com/ll_update-build-base
> * I also tested it using `make -C labware-library serve` which worked
> 
> ## Please ignore, this is fixed in the CSS udpate
> Screenshot 2024-10-17 at 11 30 26 AM
> ## Complicated news, the font is different. This might be the CSS change
> # New
> Screenshot 2024-10-17 at 11 29 23 AM
> # Old
> Screenshot 2024-10-17 at 11 29 45 AM

@alexjoel42 Shlok's PR is to fix white screen issue. The CSS part should be fixed my PR Shlok mentioned in overview.
1. go to http://sandbox.labware.opentrons.com/fix_labware-library-css-bundle-issue/
2. click go to labware creator button

**Review by koji — APPROVED** [review]
the changes make sense to me.
thank you for fixing this!
hopefully we won't get any react-router issues any more 😁

**Comment by alexjoel42** [comment]
@koji , I checked the CSS link and it works! Please keep me in the loop if you want me to test it as well.

**Pull request merged**
