### PR TITLE
docs(api): add more gripper-supported labware

### PR DESCRIPTION
**Pull request by ecormany**
# Overview

Expands the table in the Supported Labware § of Moving Labware to include all 18 labware whose definitions currently include gripper parameters.

# Test Plan

- Check formatting [in the sandbox](http://sandbox.docs.opentrons.com/docs-more-grippable-labware/v2/moving_labware.html#supported-labware).
- Check that the table lists all and only the labware that include grip force and offset info added to internal-release in #13233

# Changelog

- update list-table in `moving_labware.rst`

# Review requests

@sanni-t @andySigler @ChrisYarka Confirm which labware we want to include in this section _on August 21_:
- [ ] `biorad_96_wellplate_200ul_pcr`
- [ ] `nest_96_wellplate_100ul_pcr_full_skirt`
- [ ] `biorad_384_wellplate_50ul`
- [ ] `corning_12_wellplate_6.9ml_flat`
- [ ] `corning_48_wellplate_1.6ml_flat`
- [ ] `corning_96_wellplate_360ul_flat`
- [ ] `corning_384_wellplate_112ul_flat`
- [ ] `nest_1_reservoir_195ml`
  
 
# Risk assessment

Nil, docs.

### CODE REVIEW

**Comment by skyewindsor** [comment]
@ecormany I am pretty sure nest_96_wellplate_100ul_pcr_full_skirt is not compatible with the gripper because the plastic is too flimsy. I might want to run this augmented list by the team before we officially merge the new labware listing. 

Also, what part of the labware definition were you looking at to include them in this revised list? I'm not finding gripper params in these new definitions

**Comment by ecormany** [comment]
> @ecormany I am pretty sure nest_96_wellplate_100ul_pcr_full_skirt is not compatible with the gripper because the plastic is too flimsy. I might want to run this augmented list by the team before we officially merge the new labware listing.
> 
> Also, what part of the labware definition were you looking at to include them in this revised list? I'm not finding gripper params in these new definitions

All of these new modified labware definitions have been merged to `internal-release_0.14.0` but not yet into `edge`.

Here's the info in the NEST PCR plate definition: https://github.com/Opentrons/opentrons/blob/ffc64e6f54c63972da8743f139d90791466a7452/shared-data/labware/definitions/2/nest_96_wellplate_100ul_pcr_full_skirt/2.json#L32-L33

**Review by jwwojak — APPROVED** [review]
A thumbs-up and ship it! from me.

As an aside, in the note below the table, text mentions the "force that the gripper uses to pick up the labware." I'm just curious about this force unit or measurement. Do we need to mention what "force" is? Newtons, Joules? This is more an item of minor curiosity on my part than anything.

**Comment by ecormany** [comment]
Playing it safe and holding off on adding many more labware at this point. We can always follow up to add more. Merging to include useful new info in the note below the chart.

**Pull request merged**
