### PR TITLE
refactor(app): refactor enable dev tools section

### PR DESCRIPTION
**Pull request by koji**
# Overview
refactor enable dev tools section

close [RAUT-938](https://opentrons.atlassian.net/browse/RAUT-938) partially

# Test Plan
Go to Advanced Settings in App Settings
- Check Enable Dev Tools section is rendered correctly
- The config value is updated when clicking the toggle button

# Changelog
- create a new component for Enable Dev Tools section
- create a new test for Enable Dev Tools section
- update AdvancedSettings component and test

# Review requests

# Risk assessment
low

[RAUT-938]: https://opentrons.atlassian.net/browse/RAUT-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RAUT-938]: https://opentrons.atlassian.net/browse/RAUT-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mjhuff — COMMENTED** [review]
I'm actually having a bit of difficulty with this one. The toggle doesn't appear to be working for me:

https://github.com/Opentrons/opentrons/assets/64858653/d8101063-d9a7-436b-a2e4-2e73db68069a

Looks like you have the dispatch and selector...maybe something isn't wired up correctly elsewhere?

**Comment by koji** [comment]
> I'm actually having a bit of difficulty with this one. The toggle doesn't appear to be working for me:
> 
> 
> 
> https://github.com/Opentrons/opentrons/assets/64858653/d8101063-d9a7-436b-a2e4-2e73db68069a
> 
> 
> 
> Looks like you have the dispatch and selector...maybe something isn't wired up correctly elsewhere?

Actually dev tools toggle button is different from others.
We need to build the app.
But the config value is updated isn't it?

**Comment by mjhuff** [comment]
> Actually dev tools toggle button is different from others. We need to build the app. But the config value is updated isn't it?

Oh interesting, I didn't know it worked that way!

**Review by mjhuff — APPROVED** [review]
LGTM after clarification!

**Pull request merged**
