### PR TITLE
Debugging: hanging analysis after an HTTP protocol upload

### PR DESCRIPTION
**Pull request by SyntaxColoring**
Experimental code changes to investigate #8625.

### CODE REVIEW

**Comment by SyntaxColoring** [comment]
super_long_protocol.py: redacted for user privacy concerns. Message me on Slack.
[fast_protocol.py.zip](https://github.com/Opentrons/opentrons/files/7427887/fast_protocol.py.zip)

Observations:

* With fast sim *disabled*...
    * `super_long_protocol.py` has correctly completed analysis every time I've tried it. But it takes 10 minutes each time, so I haven't tried that many times.
* With fast sim *enabled*...
    * `super_long_protocol.py` hangs maybe 20% of the time with all these logging statements added. More frequently if the logging statements are removed.
    * `fast_protocol.py` I have never seen hang.

**Comment by SyntaxColoring** [comment]
My current hypothesis is that this is this:

https://github.com/Opentrons/opentrons/blob/c7006f011f7b3ba36d46d6c022ce8eb4be72b359/api/src/opentrons/protocol_runner/legacy_context_plugin.py#L18-L29

**Comment by SyntaxColoring** [comment]
An interesting trace with the log messages above:

```
[upload super_long_protocol.py]

WARNING:opentrons.config.robot_configs:/Users/maxpm/.opentrons/robot_settings.json not found. Loading defaults
WARNING:opentrons.config.robot_configs:/Users/maxpm/.opentrons/deck_calibration.json not found. Loading defaults
2021-10-26 14:28:25,830 uvicorn.access INFO [Line 440] 127.0.0.1:52279 - "POST /protocols HTTP/1.1" 201
WARNING:root:MAX:ProtocolRunner:run() started
WARNING:root:MAX: _load_legacy()
WARNING:root:MAX:ProtocolRunner:run() loaded
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.start()
WARNING:root:MAX:ProtocolRunner:run() played
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _run_started_event
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _run_task maybe
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker._run_commands(): starting
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker._run_commands(): awaiting next queued command
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _run_func()
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: in _run() finally-block
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _cleanup_func()
WARNING:root:MAX:protocol_engine.stop(): dispatching stop action
WARNING:root:MAX:StateView: Handling StopAction.
WARNING:root:MAX:StateView: Handled StopAction.
WARNING:root:The next queued is:
WARNING:root:Next queued raised exception: ProtocolEngineStoppedError('Engine was stopped')
WARNING:root:MAX:protocol_engine.stop(): awaiting self._queue_worker()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join(): awaiting worker_task
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join(): passing caught exception: Engine was stopped
WARNING:root:MAX:protocol_engine.stop():awaiting self._hardware_api.stop()
WARNING:root:MAX:protocol_engine.stop():done
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: exiting _run() finally-block
WARNING:root:MAX:ProtocolRunner:run() joined

[success]

[upload super_long_protocol.py a second time]

WARNING:opentrons.config.robot_configs:/Users/maxpm/.opentrons/robot_settings.json not found. Loading defaults
WARNING:opentrons.config.robot_configs:/Users/maxpm/.opentrons/deck_calibration.json not found. Loading defaults
2021-10-26 14:28:40,217 uvicorn.access INFO [Line 440] 127.0.0.1:52281 - "POST /protocols HTTP/1.1" 201
WARNING:root:MAX:ProtocolRunner:run() started
WARNING:root:MAX: _load_legacy()
WARNING:root:MAX:ProtocolRunner:run() loaded
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.start()
WARNING:root:MAX:ProtocolRunner:run() played
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _run_started_event
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _run_task maybe
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker._run_commands(): starting
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker._run_commands(): awaiting next queued command
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _run_func()
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: in _run() finally-block
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _cleanup_func()
WARNING:root:MAX:protocol_engine.stop(): dispatching stop action
WARNING:root:MAX:StateView: Handling StopAction.
WARNING:root:MAX:StateView: Handled StopAction.
WARNING:root:The next queued is:
WARNING:root:Next queued raised exception: ProtocolEngineStoppedError('Engine was stopped')
WARNING:root:MAX:protocol_engine.stop(): awaiting self._queue_worker()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join(): awaiting worker_task

[hang]
```

In the hanging upload, note that when the stop action is dispatched, getting the next queued command to print in the debug log correctly raises `ProtocolEngineStoppedError`. But later, when `QueueWorker.join()` attempts to get the next queued command, it appears to hang there.

**Comment by amitlissack** [comment]
I added this log statement `AMIT: Checking is_done`  after await self._change_notifier.wait()`

```
while not is_done:
             # await asyncio.sleep(1)
             await self._change_notifier.wait()
             logging.warn("AMIT: Checking is_done")
             is_done = predicate()
```

This is a successful run.  I added a log statement that shows every single Action that will call _update_state_views (signal the ChangeNotifier)

```
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:AMIT: Checking is_done
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:AMIT: Checking is_done
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: in _run() finally-block
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _cleanup_func()
WARNING:root:MAX:protocol_engine.stop(): dispatching stop action
WARNING:root:MAX:StateView: Handling StopAction.
WARNING:root:MAX:StateView: Handling StopAction.
WARNING:root:MAX:protocol_engine.stop(): awaiting self._queue_worker()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join(): awaiting worker_task
WARNING:root:AMIT: Checking is_done
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join(): passing caught exception: Engine was stopped
WARNING:root:MAX:protocol_engine.stop():awaiting self._hardware_api.stop()
WARNING:root:MAX:protocol_engine.stop():done
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: exiting _run() finally-block
WARNING:root:MAX:ProtocolRunner:run() joined
```

----

Here is a failed run where the code is changed like so:
```
while not is_done:
            await asyncio.sleep(1)
             await self._change_notifier.wait()
            logging.warn("AMIT: Checking is_done")
             is_done = predicate()
```

```
WARNING:root:AMIT: Checking is_done
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
......
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:root:MAX:StateView: Handling UpdateCommandAction.
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: in _run() finally-block
WARNING:opentrons.protocol_runner.task_queue:MAX:TaskQueue: awaiting _cleanup_func()
WARNING:root:MAX:protocol_engine.stop(): dispatching stop action
WARNING:root:MAX:StateView: Handling StopAction.
WARNING:root:MAX:StateView: Handling StopAction.
WARNING:root:MAX:protocol_engine.stop(): awaiting self._queue_worker()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join()
WARNING:opentrons.protocol_engine.execution.queue_worker:MAX:QueueWorker.join(): awaiting worker_task
```

The …… is to spare you the hundreds of repeated lines .

But notice that `AMIT: Checking is_done` never happens again. What happens is that the StopAction happened during the sleep. So when we went to wait, we cleared the event triggered by the StopAction and then never woke up.

**Comment by SyntaxColoring** [comment]
Closing now that #8625 is closed.

**Pull request closed without merging**
