### PR TITLE
fix(app, shared-data): splice out first set of setup commands from run log only

### PR DESCRIPTION
**Pull request by smb2268**
# Overview

Fix pause, delay commands being spliced out of run log by editing what we pull into the setup commands section

# Changelog

1. Splice out setup commands only until first instance of a non-setup command instead of last instance of a setup command
2. Add `pause` command to schema v6
3. Display pause message in run log if it exists

# Review requests

- [ ] Look over schema v6 changes 
- [ ] Test run flow with a protocol that includes delay command, pause command, and a setup command in the middle of the protocol

# Risk assessment

Low

### CODE REVIEW

**Review by shlokamin — APPROVED** [review]
LGTM, tested on robot and seems to work! Only thing is we should add a `pause` command to `protocol/fixtures/6/simpleV6.json` so that `shared-data/js/__tests__/protocolSchemaV6.test.ts` validates that a `pause` command is actually valid in a protocol.

don't wanna hold up this PR but we should do that in a follow up

Thanks @smb2268!

**Comment by smb2268** [comment]
> Only thing is we should add a `pause` command to `protocol/fixtures/6/simpleV6.json` so that `shared-data/js/__tests__/protocolSchemaV6.test.ts` validates that a `pause` command is actually valid in a protocol.

I went ahead and added one since it was a quick update. I'll merge once CI clears!

**Review by sanni-t — APPROVED** [review]
Thanks for fixing this! Just a couple of nits-
1. When the pause command has a message, I think the run log step should mention that it is a pause command. Right now it only displays the message in the pause. Was this is a conscious choice?
2. When there is no message, the step correctly says 'pause' but is all lowercase, unlike rest of the lines whose text is sentence case. Can we make the pause match this?

**Comment by shlokamin** [comment]
gonna merge this for now, lets talk over @sanni-t's comments with @emilywools  and address in a follow up as needed

**Pull request merged**
