### PR TITLE
fix(robot-server): create maintenance run if there is no protocol run

### PR DESCRIPTION
**Pull request by mjhuff**
Closes RQA-1859

# Overview

The AssertionError case for protocol_run_state should return true (no protocol run exists) instead of false.

# Test Plan
- Perform any type of maintenance run. Confirm that you can move the gantry to the front.

# Changelog
- Fix bug where users can't create maintenance runs if a protocol run doesn't exist.

### CODE REVIEW

**Review by fsinapi — APPROVED** [review]
cool and good 👍

**Review by sanni-t — APPROVED** [review]
We should add a test for this.. not for this PR though. Can you add a todo in there to test this case?

**Review by sfoster1 — COMMENTED** [review]
We sure about this? This code appears to have been this way since maintenance runs were introduced. @sanni-t can you take a look?

**Comment by sanni-t** [comment]
> We sure about this? This code appears to have been this way since maintenance runs were introduced. @sanni-t can you take a look?

That particular line has been there, yes, but we changed the dependency from `get_protocol_run_has_benn_played` to `get_is_okay_to_create_maintenance_run` which changes the assertion.. so changes from 'is it not okay?' to 'is it okay?'

**Review by sfoster1 — APPROVED** [review]
Ah, nice!

**Pull request merged**
