### PR TITLE
refactor(hardware): add can_control script and fix styling

### PR DESCRIPTION
**Pull request by sfoster1**
Some general refactors for can scripts, including
- Making can_mon a little less likely to leave all your terminal text blue forever
- Adding can_control which fuses can_mon and can_comm

## TODO
- [x] Test on a robot
- [x] Test on an emulator setup

### CODE REVIEW

**Review by amitlissack — COMMENTED** [review]
Looks like nice changes, but I tried to run to `can_control` and got a bunch of errors.

```
Traceback (most recent call last):
  File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/logging/handlers.py", line 183, in shouldRollover
    self.stream = self._open()
  File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 1641, in call_exception_handler
    self.default_exception_handler(context)
  File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 1615, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
Message: '_GatheringFuture exception was never retrieved\nfuture: <_GatheringFuture finished exception=CancelledError()>'
Arguments: ()
```

**Comment by sfoster1** [comment]
> Looks like nice changes, but I tried to run to `can_control` and got a bunch of errors.
> 
> ```
> Traceback (most recent call last):
>   File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/logging/handlers.py", line 69, in emit
>     if self.shouldRollover(record):
>   File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/logging/handlers.py", line 183, in shouldRollover
>     self.stream = self._open()
>   File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/logging/__init__.py", line 1116, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)
> NameError: name 'open' is not defined
> Call stack:
>   File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 1641, in call_exception_handler
>     self.default_exception_handler(context)
>   File "/Users/amit/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 1615, in default_exception_handler
>     logger.error('\n'.join(log_lines), exc_info=exc_info)
> Message: '_GatheringFuture exception was never retrieved\nfuture: <_GatheringFuture finished exception=CancelledError()>'
> Arguments: ()
> ```

Uh yeah I should have mentioned I hadn't tested it yet and was about to go do so

**Review by amitlissack — APPROVED** [review]
Tested in emulation setup.

Could use some small niceties, but it's a really nice improvement.

**Comment by DerekMaggio** [comment]
Can you update the README with changes in how the script is called? 
I have makefile targets in `opentrons-emulation` that allow you to call the `can-mon` and `can-comm` scripts on the right container. I want to make sure those will still work

**Review by Laura-Danielle — APPROVED** [review]
lgtm

**Pull request merged**
